import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {Collection,PermissionsBitField,PermissionFlagsBits} from 'discord.js';
import {setTestDatabase,defaultCommunitySettings,defaultApplicationProtection,applicationIdentity,applicationViolation,MusicQueue,defaultMusicSettings,queueMusicJob,verifyAudit} from '../packages/core/src/index';
import {protectApplicationMessage,syncExternalApplicationPermissions} from '../apps/bot/src/application-security';
import {commands} from '../packages/core/src/commands';
import {MusicManager} from '../apps/bot/src/music';
import {verifyAudioEncoding} from '../apps/bot/src/audio-diagnostics';
import {audioURL,publicIPv4} from '../apps/bot/src/audio-source';
process.env.APP_URL='https://turkishpix.example';process.env.DATABASE_URL='postgresql://test.invalid/test';process.env.AUDIT_HMAC_KEY='test-only-key-012345678901234567890123456789';process.env.DISCORD_BOT_TOKEN='test-bot-token';process.env.DISCORD_GUILD_ID='888888888888888888';process.env.DISCORD_LOG_CHANNEL_ID='999999999999999999';process.env.DISCORD_OWNER_IDS='111111111111111111,222222222222222222,333333333333333333,444444444444444444';process.env.DEMO_MODE='false';
const guildId=process.env.DISCORD_GUILD_ID!,channelId='999999999999999998',ownerId='111111111111111111',userId='555555555555555555',installerId='666666666666666666',appId='777777777777777777',botId='123456789012345678';let pg:PGlite;const realFetch=globalThis.fetch;
before(async()=>{pg=new PGlite();setTestDatabase({query:async(sql:string,params:any[]=[])=>{const r=await pg.query(sql,params);return {rows:r.rows as any[],rowCount:r.affectedRows||0};}});for(const v of ['001_initial','003_discord_roles','004_server_setup','005_community','006_voice_presence','007_entertainment','008_chat_moderation','009_community_features','010_music_application_security','011_tickets_giveaways','012_community_expansion','013_level_notifications','014_arcade_currency','015_arcade_games','016_discord_audit','017_role_automation'])await pg.exec(await readFile(new URL('../packages/core/sql/'+v+'.sql',import.meta.url),'utf8'));});
after(async()=>{globalThis.fetch=realFetch;await pg.close();});
function applicationMessage(id:string){const calls:string[]=[];const member:any={id:userId,moderatable:true,roles:{cache:new Collection()},timeout:async()=>calls.push('timeout')};const guild:any={id:guildId,members:{cache:new Collection([[userId,member]]),fetch:async()=>member}};return {calls,member,message:{id,guildId,guild,channelId,author:{id:appId,username:'.gg/json',bot:true},applicationId:appId,webhookId:appId,interactionMetadata:{user:{id:userId,username:'eternal.cpp'},authorizingIntegrationOwners:{'1':installerId}},deletable:true,delete:async()=>calls.push('delete')}};}
test('Dış uygulama sahibiyle tetikleyen üye ayrılır; sunucu botu ve kendi mesajlarımız korunur',()=>{const {message}=applicationMessage('identity'),p=defaultApplicationProtection();assert.equal(applicationIdentity(message,botId).user!.id,userId);assert.equal(applicationViolation(message,p,botId),'USER_INSTALLED_APP');assert.equal(applicationViolation({...message,interactionMetadata:{...message.interactionMetadata,authorizingIntegrationOwners:{'0':guildId}}},p,botId),null);assert.equal(applicationViolation({...message,applicationId:botId},p,botId),null);assert.equal(applicationViolation(message,{...p,allowedApplicationIds:[appId]},botId),null);assert.equal(applicationViolation({...message,interactionMetadata:null,reference:{type:0}},p,botId),null);assert.equal(applicationViolation({author:{id:userId},reference:{type:1}},p,botId),'FORWARDED_MESSAGE');});
test('Bot/webhook dış uygulaması silinir; replay bir kez işlenir, gerçek üye susturulur ve etiketlenir',async()=>{const settings=defaultCommunitySettings();for(let n=0;n<4;n++){const item=applicationMessage('replay-'+n);await Promise.all([protectApplicationMessage(item.message,settings,botId,100000+n*100),protectApplicationMessage(item.message,settings,botId,100000+n*100)]);assert.equal(item.calls.filter(c=>c==='delete').length,1);assert.equal(item.calls.filter(c=>c==='timeout').length,n===3?1:0);}const events=(await pg.query<any>("SELECT user_id,action FROM security_events WHERE reason='USER_INSTALLED_APP'")).rows;assert.equal(events.length,4);assert.ok(events.every(e=>e.user_id===userId));const payload=(await pg.query<any>("SELECT payload FROM community_deliveries WHERE kind='SECURITY_LOG' ORDER BY created_at DESC LIMIT 1")).rows[0].payload;assert.equal(payload.flags,32768);assert.ok(JSON.stringify(payload.components).includes('<@'+userId+'>'));assert.ok(JSON.stringify(payload.components).includes('gg/json'));assert.ok(!JSON.stringify(payload).includes(installerId));assert.equal((await verifyAudit()).valid,true);});
test('Yönlendiren insan sorumlu tutulur; tetikleyici bilgisi olmayan bot hesabına ceza verilmez',async()=>{const settings=defaultCommunitySettings(),f=applicationMessage('human-forward');const human:any={...f.message,author:{id:installerId,username:'forwarder',bot:false},applicationId:null,webhookId:null,interactionMetadata:null,reference:{type:1}};await protectApplicationMessage(human,settings,botId);const event=(await pg.query<any>("SELECT user_id FROM security_events WHERE reason='FORWARDED_MESSAGE'")).rows[0];assert.equal(event.user_id,installerId);const unknown:any={...f.message,id:'unknown-forward',interactionMetadata:null,reference:{type:1}};await protectApplicationMessage(unknown,settings,botId);assert.equal((await pg.query<any>("SELECT user_id FROM security_events ORDER BY created_at DESC LIMIT 1")).rows[0].user_id,'UNKNOWN_APPLICATION');assert.equal(f.calls.filter(c=>c==='timeout').length,0);});
test('Discord izin kilidi açık rol izinlerini kapatır; kapatınca eski üç durumlu izinler ve diğer bitler döner',async()=>{
 const external=PermissionFlagsBits.UseExternalApps,send=PermissionFlagsBits.SendMessages,roleId='444444444444444445';const cache=new Collection<string,any>([[roleId,{id:roleId,type:0,allow:new PermissionsBitField(external|send),deny:new PermissionsBitField(0n)}]]),edits:any[]=[];
 const ch:any={id:channelId,type:0,isThread:()=>false,permissionOverwrites:{cache,edit:async(id:string,changes:any,options:any)=>{const old=cache.get(id)||{id,type:options.type,allow:new PermissionsBitField(0n),deny:new PermissionsBitField(0n)};const allow=new PermissionsBitField(old.allow.bitfield&~external),deny=new PermissionsBitField(old.deny.bitfield&~external);if(changes.UseExternalApps===true)allow.add(external);if(changes.UseExternalApps===false)deny.add(external);cache.set(id,{...old,allow,deny});edits.push(changes);}}};
 const guild:any={id:guildId,ownerId,members:{me:{permissions:new PermissionsBitField(PermissionFlagsBits.ManageChannels)}},roles:{cache:new Collection([[roleId,{permissions:new PermissionsBitField(0n)}]])},channels:{cache:new Collection([[channelId,ch]])}};const client:any={guilds:{cache:new Collection([[guildId,guild]])}},settings=defaultCommunitySettings();assert.equal((await syncExternalApplicationPermissions(client,settings)).state,'ACTIVE');assert.ok(cache.get(guildId).deny.has(external));assert.ok(cache.get(roleId).deny.has(external));assert.ok(cache.get(roleId).allow.has(send));await syncExternalApplicationPermissions(client,settings);assert.equal(edits.length,2);settings.security.applications.nativeBlock=false;assert.equal((await syncExternalApplicationPermissions(client,settings)).state,'OFF');assert.equal(cache.get(guildId).deny.has(external),false);assert.equal(cache.get(guildId).allow.has(external),false);assert.ok(cache.get(roleId).allow.has(external|send));assert.equal((await pg.query('SELECT * FROM application_permission_backups')).rows.length,0);
});
test('Müzik kuyruğu kapasite, üye kotası, tekrar, yeniden sıralama ve tekil oyları uygular',()=>{const p=defaultMusicSettings();p.perUserLimit=2;const q=new MusicQueue(p),track=(n:number,id=userId)=>({id:String(n),url:'https://example.com/'+n+'.mp3',title:'Parça '+n,requesterId:id,radio:false});q.add(track(1));q.add(track(2));assert.throws(()=>q.add(track(3)),/sınır/);q.add(track(3,installerId));assert.equal(q.advance()!.id,'1');q.repeat='TRACK';assert.equal(q.advance()!.id,'1');assert.equal(q.advance(true)!.id,'2');q.repeat='QUEUE';assert.equal(q.advance()!.id,'3');q.add(track(4,ownerId));q.move(2,1);assert.equal(q.tracks[0].id,'4');assert.equal(q.remove(2).id,'2');assert.throws(()=>q.move(1,3));assert.equal(q.vote(userId,[userId,installerId,ownerId]).skip,false);assert.equal(q.vote(userId,[userId,installerId,ownerId]).votes,1);assert.equal(q.vote(installerId,[userId,installerId,ownerId]).skip,true);assert.throws(()=>q.vote('outsider',[userId]));q.advance(true);assert.equal(q.votes.size,0);q.stop();assert.equal(q.current,null);assert.equal(q.tracks.length,0);p.maxQueue=5;p.perUserLimit=20;const capped=new MusicQueue(p);for(let n=0;n<5;n++)capped.add(track(n));assert.throws(()=>capped.add(track(8)),/dolu/);});
test('Medya kaynağı yerel ağ, kimlik bilgileri ve sayfa bağlantılarıyla istismar edilemez',()=>{for(const ip of ['127.0.0.1','10.0.1.2','169.254.169.254','172.19.0.4','192.168.1.1','100.100.100.200','224.0.0.1','198.18.0.1'])assert.equal(publicIPv4(ip),false,ip);assert.equal(publicIPv4('1.1.1.1'),true);for(const url of ['http://example.com/a.mp3','file:///etc/passwd','https://user:secret@example.com/song.mp3','https://host.internal/song.mp3','https://example.com:123/a.mp3','https://youtube.com/watch?v=abc','https://[::1]/a.mp3'])assert.throws(()=>audioURL(url));assert.equal(audioURL('https://cdn.discordapp.com/attachments/a/song.mp3?ex=abc').hostname,'cdn.discordapp.com');});
test('Müzik kontrolü başka kanal ve başkasının parçasını yönetmeye izin vermez; oylama ve owner çalışır',async()=>{const settings=defaultCommunitySettings();const users=[userId,installerId,ownerId].map(id=>({id,user:{bot:false},permissions:new PermissionsBitField(0n),roles:{cache:new Collection()},voice:{channelId}}));const ch:any={id:channelId,members:new Collection(users.map(u=>[u.id,u]))};const guild:any={members:{fetch:async(id:string)=>users.find(u=>u.id===id)},channels:{cache:new Collection([[channelId,ch]])}};const manager=new MusicManager({guilds:{cache:new Collection([[guildId,guild]])}} as any,settings);manager.channelId=channelId;manager.connection={state:{status:'ready'},destroy:()=>{}} as any;manager.queue.current={id:'playing',title:'Parça',url:'https://example.com/track.mp3',requesterId:installerId,radio:false};await assert.rejects(manager.execute('ses',{volume:99},userId,channelId),/DJ/);await assert.rejects(manager.execute('ses',{volume:99},userId,'999999999999999997'),/ses kanalına/);assert.match(await manager.execute('oyla',{},userId,channelId),/1\/2/);assert.match(await manager.execute('ses',{volume:20},ownerId,channelId,true),/%20/);assert.equal(manager.queue.volume,20);await assert.rejects(manager.execute('ses',{volume:101},ownerId,channelId,true));manager.queue.tracks.push({id:'other',title:'Parça',url:'https://example.com/other.mp3',requesterId:installerId,radio:false});await assert.rejects(manager.execute('cikar',{index:1},userId,channelId),/DJ/);await manager.execute('cikar',{index:1},installerId,channelId);assert.equal(manager.queue.tracks.length,0);await manager.shutdown();assert.equal(manager.snapshot().connected,false);});
test('100 kök komut Discord sınırında kalır; 27 ses işleminin tüm seçenekleri geçerlidir',()=>{assert.equal(commands.length,100);assert.ok(commands.length<=100);let actions=0;for(const command of commands.filter(c=>['ses','muzik'].includes(c.name))){for(const sub of command.options||[]){assert.equal(sub.type,1);actions++;let optional=false;for(const option of sub.options||[]){assert.ok(option.name.length<=32);if(option.required)assert.equal(optional,false);else optional=true;}}}assert.equal(actions,27);});
test('Panel müzik işi owner, canlı bot ve doğru sunucu kanalı gerektirir; tek işi kuyruğa kaydeder',async()=>{const actor={id:ownerId,username:'owner'};await assert.rejects(queueMusicJob({id:userId,username:'user'},{channelId,action:'katil'}),/owner/);await assert.rejects(queueMusicJob(actor,{channelId,action:'katil'}),/bağlantısı/);await pg.query("INSERT INTO integration_status(name,status) VALUES('discord',$1)",[{connected:true}]);globalThis.fetch=async()=>Response.json({id:channelId,guild_id:guildId,type:2});const job=await queueMusicJob(actor,{channelId,action:'radyo',station:'chill'});assert.ok(job.id);assert.equal((await pg.query<any>('SELECT status FROM music_jobs WHERE id=$1',[job.id])).rows[0].status,'QUEUED');globalThis.fetch=async()=>Response.json({id:channelId,guild_id:installerId,type:2});await assert.rejects(queueMusicJob(actor,{channelId,action:'katil'}),/sunucudan/);globalThis.fetch=realFetch;});

test('Gerçek FFmpeg ses verisi Opus paketlerine dönüşür',async()=>{const result=await verifyAudioEncoding();assert.ok(result.pcmBytes>0);assert.ok(result.opusPackets>=5);});
