import {test,before,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {Collection,PermissionsBitField,PermissionFlagsBits,ChannelType} from 'discord.js';
import {setTestDatabase,defaultCommunitySettings,defaultDiscordAuditSettings,discordAuditSettings,updateDiscordAuditSettings,captureDiscordMessage,recordDiscordAudit,discordAuditEvent,queueBotJoin,claimBotJoin,finishBotJoin,shouldBlockBot,cleanupDiscordAudit,auditEventCard,auditRowToEvent,hasServerTag,reactionEmojiKey,roleAutomationSettings,saveRoleAutomation,queueRoleChange,claimRoleChange,finishRoleChange,createRoleBulk,activateRoleBulk,cancelRoleBulk,roleBulkStatus,COMPONENTS_V2,communityDeliveryTick,botInviteUrl} from '../packages/core/src/index';
import {controlPanelView,handleControlInteraction,validateAuditChannel} from '../apps/bot/src/control-panel';
import {reconcileMember,runRoleJob,reactionRoleChange,handleRoleAutomationInteraction,automationRole,scanBulk} from '../apps/bot/src/role-automation';
import {enforceNextBotJoin,handleBotJoin} from '../apps/bot/src/discord-audit';
import {commands} from '../packages/core/src/commands';
const guildId='888888888888888888',ownerId='111111111111111111',userId='555555555555555555',botId='999999999999999999',roleId='777777777777777777',tagRoleId='777777777777777778',channelId='666666666666666666';
const actor={id:ownerId,username:'owner',manageGuild:true,guardManager:true};
process.env.DISCORD_GUILD_ID=guildId;process.env.DISCORD_OWNER_IDS=ownerId;process.env.DISCORD_CLIENT_ID=botId;process.env.DISCORD_BOT_TOKEN='test-token';process.env.DEMO_MODE='false';process.env.DATABASE_URL='postgresql://test.invalid/test';process.env.APP_URL='https://turkishpix.example';process.env.AUDIT_HMAC_KEY='test-only-automation-key-012345678901234567890';
let pg:PGlite;const original=globalThis.fetch;
before(async()=>{pg=new PGlite();setTestDatabase({query:async(sql,params=[])=>{const r=await pg.query(sql,params);return {rows:r.rows as any[],rowCount:r.affectedRows||0};}});for(const name of (await readdir(new URL('../packages/core/sql/',import.meta.url))).filter(n=>/^\d+.*\.sql$/.test(n)&&!n.startsWith('002_')).sort())await pg.exec(await readFile(new URL('../packages/core/sql/'+name,import.meta.url),'utf8'));});
beforeEach(async()=>{await pg.exec('DELETE FROM role_bulk_targets;DELETE FROM role_bulk_campaigns;DELETE FROM role_automation_jobs;DELETE FROM role_reaction_panels;DELETE FROM role_automation_settings;DELETE FROM role_scan_state;DELETE FROM discord_audit_events;DELETE FROM discord_audit_settings;DELETE FROM discord_message_snapshots;DELETE FROM bot_join_jobs;DELETE FROM community_deliveries;DELETE FROM community_settings;');await pg.query('INSERT INTO community_settings(guild_id,settings) VALUES($1,$2)',[guildId,defaultCommunitySettings()]);globalThis.fetch=async()=>Response.json({id:userId,primary_guild:{identity_enabled:true,identity_guild_id:guildId}});});
after(async()=>{globalThis.fetch=original;await pg.close();});
function fake(){
 const roles=new Collection<string,any>([[roleId,{id:roleId,managed:false,permissions:new PermissionsBitField()}],[tagRoleId,{id:tagRoleId,managed:false,permissions:new PermissionsBitField()}]]),members=new Collection<string,any>();
 const guild:any={id:guildId,ownerId,name:'TurkishPix',available:true,memberCount:3,roles:{fetch:async(id:string)=>roles.get(id),everyone:{id:guildId},cache:roles},emojis:{cache:new Collection()},members:{fetch:async(input:any)=>members.get(typeof input==='string'?input:input.user),fetchMe:async()=>members.get(botId)}};
 for(const id of [ownerId,userId,botId]){const cache=new Collection<string,any>();members.set(id,{id,user:{id,username:id===ownerId?'owner':'member',bot:id===botId},pending:false,guild,joinedAt:new Date('2026-10-09T00:00:00Z'),joinedTimestamp:1791504000000,kickable:true,permissions:new PermissionsBitField(id===ownerId||id===botId?PermissionsBitField.All:0n),roles:{cache,highest:{comparePositionTo:()=>10},add:async(role:any)=>cache.set(role.id||role,roles.get(role.id||role)),remove:async(role:any)=>cache.delete(role.id||role)},kick:async()=>members.delete(id)});}
 guild.members.me=members.get(botId);
 const channel:any={id:channelId,guildId,type:ChannelType.GuildText,permissionsFor:(member:any)=>new PermissionsBitField(member.id===guildId?0n:PermissionsBitField.All)};guild.channels={fetch:async()=>channel};
 const client:any={isReady:()=>true,user:{id:botId},guilds:{cache:new Collection([[guildId,guild]])}};
 return {guild,roles,members,client,channel};
}
function interaction(guild:any,sub='panel',values:any={},user=ownerId){const replies:any[]=[];const i:any={user:{id:user,username:'owner'},guild,guildId,channelId,channel:{id:channelId},commandName:'topluluk',isChatInputCommand:()=>true,options:{getSubcommandGroup:()=> 'roller',getSubcommand:()=>sub,getRole:()=>values.rol,getString:(name:string)=>values[name],getChannel:()=>values.kanal},deferReply:async()=>{i.deferred=true;},deferUpdate:async()=>{i.deferred=true;},editReply:async(p:any)=>replies.push(p),reply:async(p:any)=>replies.push(p)};return {i,replies};}
function componentNodes(card:any){const found:any[]=[];const visit=(n:any)=>{found.push(n);for(const c of n.components||[])visit(c);if(n.accessory)visit(n.accessory);};for(const c of card.components)visit(c);return found;}
const message={id:'444444444444444444',channelId,authorId:userId,authorName:'member',content:'İlk metin @everyone `kod`'};
test('Mesaj öncesi/sonrası ve silinen içerik kalıcıdır; tekrar aynı mesaj ikinci kayıt açmaz',async()=>{
 const id=await captureDiscordMessage(message,'CREATE');await captureDiscordMessage(message,'CREATE');const edited=await captureDiscordMessage({...message,content:'Yeni metin'},'EDIT');await captureDiscordMessage({...message,content:'Yeni metin'},'EDIT');const deleted=await captureDiscordMessage({...message,content:''},'DELETE');
 assert.equal((await pg.query('SELECT * FROM discord_audit_events')).rows.length,3);assert.equal((await discordAuditEvent(edited!)).before_content,message.content);assert.equal((await discordAuditEvent(deleted!)).before_content,'Yeni metin');assert.equal((await pg.query('SELECT * FROM discord_message_snapshots')).rows.length,0);
 const card=auditEventCard(auditRowToEvent(await discordAuditEvent(id!)));assert.equal(card.flags,COMPONENTS_V2);assert.ok(JSON.stringify(card).includes('＠everyone'));assert.deepEqual(card.allowedMentions,{parse:[]});assert.ok(!JSON.stringify(card).includes('`kod`'));
});
test('Kanal hariç tutma, kategori kapatma, saklama süresi ve eski panel koruması uygulanır',async()=>{
 await updateDiscordAuditSettings(actor,{ignoredChannelIds:[channelId]},0);assert.equal(await captureDiscordMessage(message,'CREATE'),null);await assert.rejects(updateDiscordAuditSettings(actor,{enabled:false},0),/değişmiş/);assert.equal((await discordAuditSettings()).enabled,true);
 await updateDiscordAuditSettings(actor,{ignoredChannelIds:[],logChannelId:channelId,retentionDays:7});assert.equal(await captureDiscordMessage(message,'CREATE'),null);const id=await recordDiscordAudit({key:'blocked',kind:'BLOCKED_MESSAGE',actorId:userId,after:'Yasaklı içerik'});await pg.query("UPDATE discord_audit_events SET created_at=now()-interval '8 days'");await cleanupDiscordAudit();assert.equal(await discordAuditEvent(id!),null);await communityDeliveryTick();assert.equal((await pg.query<any>('SELECT status FROM community_deliveries')).rows[0].status,'CANCELLED');
});
test('Denetim ayarı ve kayıt ayrıntısı yetkisiz veya yabancı guild hesabına açılmaz',async()=>{
 await assert.rejects(updateDiscordAuditSettings({...actor,manageGuild:false},{enabled:false}),/izni/);await assert.rejects(updateDiscordAuditSettings({...actor,guardManager:false},{botGuard:{enabled:false,allowlist:[]}}),/sahibi/);
 const {guild}=fake();await assert.rejects(controlPanelView(interaction(guild,'panel',{},userId).i,'records'),/izni/);await validateAuditChannel(interaction(guild).i,channelId);guild.channels.fetch=async()=>({id:channelId,guildId,type:0,permissionsFor:()=>new PermissionsBitField(PermissionsBitField.All)});await assert.rejects(validateAuditChannel(interaction(guild).i,channelId),/Herkese kapalı/);
 const detail=interaction(guild,'panel',{},userId);detail.i.customId='audit:detail:'+randomUUID();detail.i.isChatInputCommand=()=>false;await handleControlInteraction(detail.i);assert.ok(JSON.stringify(detail.replies.at(-1)).includes('izni'));assert.ok(!detail.replies.at(-1).files);
});
test('Bot engeli kendi botunu, uygulamasını, insanı ve izinli botu korur',async()=>{
 const s=defaultDiscordAuditSettings();assert.equal(shouldBlockBot(botId,true,botId,s,botId),false);assert.equal(shouldBlockBot(userId,false,botId,s,botId),false);s.botGuard.allowlist=[userId];assert.equal(shouldBlockBot(userId,true,botId,s,botId),false);assert.equal(shouldBlockBot(roleId,true,botId,s,botId),true);
 const {guild,members,client}=fake();await handleBotJoin(members.get(botId),botId);assert.equal((await pg.query('SELECT * FROM bot_join_jobs')).rows.length,0);await queueBotJoin({id:botId,name:'self',joinedAt:members.get(botId).joinedAt});await enforceNextBotJoin(client);assert.ok(members.has(botId));
 const foreign={...members.get(userId),user:{id:userId,username:'foreign',bot:true}};foreign.joinedTimestamp=foreign.joinedAt.getTime();members.set(userId,foreign);await handleBotJoin(foreign,botId);await enforceNextBotJoin(client);assert.equal(members.has(userId),false);assert.equal((await pg.query<any>('SELECT status FROM bot_join_jobs WHERE bot_id=$1',[userId])).rows[0].status,'REMOVED');
});
test('Giriş denetimi ekleyen kişiyi sonradan işler; eski iş yeni katılımı tamamlayamaz',async()=>{
 const date=new Date('2026-10-09T00:00:00Z');await queueBotJoin({id:userId,name:'bot',joinedAt:date});await queueBotJoin({id:userId,name:'bot',joinedAt:date,addedBy:ownerId});const job=await claimBotJoin();assert.equal(job.added_by,ownerId);await queueBotJoin({id:userId,name:'bot',joinedAt:new Date(date.getTime()+1000)});await finishBotJoin(job,'REMOVED');assert.equal((await pg.query<any>('SELECT status FROM bot_join_jobs')).rows[0].status,'QUEUED');
});
test('Gerçek guild tagı doğrulanır; nickname taklidi ve eksik kimlik rol kazandırmaz',()=>{
 assert.equal(hasServerTag({username:'TAG kişi'},guildId),null);assert.equal(hasServerTag({primary_guild:null},guildId),false);assert.equal(hasServerTag({primary_guild:{identity_enabled:true,identity_guild_id:guildId}},guildId),true);assert.equal(hasServerTag({primary_guild:{identity_enabled:false,identity_guild_id:guildId}},guildId),false);assert.equal(hasServerTag({primary_guild:{identity_enabled:true,identity_guild_id:botId}},guildId),false);assert.equal(hasServerTag({primary_guild:{}},guildId),null);
 assert.equal(reactionEmojiKey('✅'),'✅');assert.equal(reactionEmojiKey('❤️'),reactionEmojiKey('❤'));assert.equal(reactionEmojiKey('<a:party:'+roleId+'>'),roleId);assert.throws(()=>reactionEmojiKey('hello'));
});
test('Otorol mevcut rolü korur; yeni insan üyeye verir, bot ve doğrulama bekleyeni atlar',async()=>{
 const {members,client}=fake();await saveRoleAutomation(actor,{autoEnabled:true,autoRoleIds:[roleId]});members.get(userId).roles.cache.set(tagRoleId,{});await reconcileMember(members.get(userId));await reconcileMember(members.get(botId));await runRoleJob(client);assert.ok(members.get(userId).roles.cache.has(roleId));assert.ok(members.get(userId).roles.cache.has(tagRoleId));assert.equal(members.get(botId).roles.cache.has(roleId),false);members.get(ownerId).pending=true;await reconcileMember(members.get(ownerId));assert.equal((await pg.query('SELECT * FROM role_automation_jobs WHERE user_id=$1',[ownerId])).rows.length,0);
 await saveRoleAutomation(actor,{tagEnabled:true,tagRoleId});assert.equal((await roleAutomationSettings()).autoEnabled,true);await saveRoleAutomation(actor,{autoEnabled:false});assert.equal((await roleAutomationSettings()).tagEnabled,true);
});
test('Tag alınca rol verilir, silince alınır; eksik API bilgisi mevcut rolü silmez',async()=>{
 const {members,client}=fake();await saveRoleAutomation(actor,{tagEnabled:true,tagRoleId});await reconcileMember(members.get(userId));await runRoleJob(client);assert.ok(members.get(userId).roles.cache.has(tagRoleId));globalThis.fetch=async()=>Response.json({primary_guild:null});await reconcileMember(members.get(userId));await runRoleJob(client);assert.equal(members.get(userId).roles.cache.has(tagRoleId),false);
 members.get(userId).roles.cache.set(tagRoleId,{});globalThis.fetch=async()=>Response.json({username:'member'});await queueRoleChange(userId,tagRoleId,false,'TAG');await runRoleJob(client);assert.ok(members.get(userId).roles.cache.has(tagRoleId));assert.equal((await pg.query<any>('SELECT status FROM role_automation_jobs')).rows[0].status,'QUEUED');
});
test('Emoji ekleme/kaldırma ve eski işlem yarışında en yeni istek korunur',async()=>{
 const {guild,members,client}=fake(),panelId=randomUUID();await pg.query('INSERT INTO role_reaction_panels(id,guild_id,channel_id,message_id,role_id,emoji_key,emoji,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[panelId,guildId,channelId,message.id,roleId,'✅','✅',ownerId]);const reaction={partial:true,emoji:{name:'✅'},message:{id:message.id,guildId,channelId,guild}};
 await reactionRoleChange(reaction,members.get(userId).user,true);const older=await claimRoleChange();await reactionRoleChange(reaction,members.get(userId).user,false);await finishRoleChange(older,'DONE');assert.equal((await pg.query<any>('SELECT status FROM role_automation_jobs')).rows[0].status,'QUEUED');await runRoleJob(client);assert.equal(members.get(userId).roles.cache.has(roleId),false);await reactionRoleChange(reaction,members.get(userId).user,true);await runRoleJob(client);assert.ok(members.get(userId).roles.cache.has(roleId));await reactionRoleChange(reaction,members.get(userId).user,false);await runRoleJob(client);assert.equal(members.get(userId).roles.cache.has(roleId),false);
});
test('Dağıtım onayı tek kullanımlı, iptal kalıcı; ilerleme sonraki rol işlerinden etkilenmez',async()=>{
 const id=await createRoleBulk(ownerId,roleId,20);await activateRoleBulk(ownerId,id);await assert.rejects(activateRoleBulk(ownerId,id),/kullanılmış/);await queueRoleChange(userId,roleId,true,'BULK',{campaignId:id});await queueRoleChange(userId,roleId,true,'AUTO');const job=await claimRoleChange();assert.equal(job.source,'BULK');await finishRoleChange(job,'DONE');assert.equal((await roleBulkStatus())[0].done,1);await queueRoleChange(userId,roleId,true,'AUTO');assert.equal((await roleBulkStatus())[0].done,1);
 await queueRoleChange(botId,roleId,true,'BULK',{campaignId:id});const running=await claimRoleChange();await cancelRoleBulk(ownerId,id);await finishRoleChange(running,'DONE');await queueRoleChange(tagRoleId,roleId,true,'BULK',{campaignId:id});assert.equal((await roleBulkStatus())[0].pending,0);assert.equal((await pg.query('SELECT * FROM role_bulk_targets WHERE user_id=$1',[tagRoleId])).rows.length,0);
});
test('Discord paneli sınırlar içinde; rol menüsü kullanıcıya bağlı, yetkisiz rol vermez',async()=>{
 const {guild,roles,members}=fake();const i=interaction(guild).i;for(const view of ['home','audit','guard','records','chat','welcome','levels','roles','rooms','music','events','support','games','profile']){const card=await controlPanelView(i,view),nodes=componentNodes(card);assert.equal(card.flags,32768,view);assert.ok(nodes.length<=40,view+': '+nodes.length);assert.ok(nodes.filter(n=>n.type===10).reduce((sum,n)=>sum+n.content.length,0)<=4000,view);for(const n of nodes){assert.ok(!n.custom_id||n.custom_id.length<=100);assert.ok(!n.options||n.options.length<=25);}}
 const denied=interaction(guild);denied.i.isChatInputCommand=()=>false;denied.i.customId='rolepanel:'+userId+':autooff:';await handleRoleAutomationInteraction(denied.i);assert.ok(JSON.stringify(denied.replies).includes('sana ait değil'));assert.equal((await roleAutomationSettings()).autoEnabled,false);
 roles.get(roleId).permissions=new PermissionsBitField(PermissionFlagsBits.Administrator);await assert.rejects(automationRole(guild,roleId,members.get(ownerId)),/otomatik verilemez/);
 const root=commands.find(c=>c.name==='topluluk') as any;assert.equal(commands.length,100);assert.ok(root.options.find((g:any)=>g.name==='roller').options.some((s:any)=>s.name==='emoji'));const invite=new URL(botInviteUrl());assert.equal(BigInt(invite.searchParams.get('permissions')!)&PermissionFlagsBits.AddReactions,PermissionFlagsBits.AddReactions);
});
test('Toplu dağıtım tüm üye sayfalarını tarar; geçici hata cursor ve bekleyen işi kaybetmez',async()=>{
 const {client,members}=fake(),id=await createRoleBulk(ownerId,roleId,101);await activateRoleBulk(ownerId,id);const lastId='555555555555555556';members.set(lastId,{...members.get(userId),id:lastId,user:{id:lastId,bot:false},roles:{...members.get(userId).roles,cache:new Collection()}});
 let calls=0;globalThis.fetch=async(input:any)=>{calls++;if(calls===1)return Response.json(Array.from({length:100},(_,n)=>({user:{id:n===0?userId:String(600000000000000000n+BigInt(n)),bot:n>0},roles:[],pending:false})));if(calls===2)throw Error('temporary network failure');assert.ok(String(input).includes('after=600000000000000099'));return Response.json([{user:{id:lastId,bot:false},roles:[],pending:false}]);};
 await scanBulk(client);assert.equal((await roleBulkStatus())[0].status,'SCANNING');await scanBulk(client);assert.equal((await roleBulkStatus())[0].status,'SCANNING');assert.equal((await roleBulkStatus())[0].pending,1);await pg.query('UPDATE role_bulk_campaigns SET available_at=now()');await scanBulk(client);assert.equal((await roleBulkStatus())[0].status,'APPLYING');assert.equal((await roleBulkStatus())[0].pending,2);await runRoleJob(client);await runRoleJob(client);assert.equal((await roleBulkStatus())[0].done,2);assert.ok(members.get(userId).roles.cache.has(roleId));
});
