import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {Collection,PermissionsBitField,PermissionFlagsBits,ChannelType} from 'discord.js';
import {setTestDatabase,config,defaultCommunitySettings,communitySettings,communitySettingsSchema,expansionUsageCount,setAFK,clearAFK,mentionedAFK,setBirthday,birthdayCalendar,validBirthday,saveYouTubeKey,youtubeStatus,searchYouTube,youtubeVideoId,youtubeVideo,saveYouTubeFavourite,youtubeFavourites,createWatchTogether,addFeatureRecord,eventRSVP,eventAttendees,eventMaintenance,editEvent,getFeatureRecord,attachFeatureMessage,scheduledAnnouncement,scheduledList,cancelScheduled,communityDeliveryTick,awardVoiceXP,awardChatXP,memberProfile,changeCustomCommand,customResponse,communityCalendar,createAdvancedEvent,verifyAudit} from '../packages/core/src/index';
import {handleRoomVoiceJoin,ensureVoiceRoomLobby} from '../apps/bot/src/rooms';
import {commands} from '../packages/core/src/commands';
import {helpEntries,commandCategory} from '../apps/bot/src/help';
import {featureRecordView} from '../apps/bot/src/features';
import {handleExpansionInteraction,expansionTick,expansionMessage,expansionVoiceChange} from '../apps/bot/src/expansion';
import {handleYouTubeInteraction,reportYouTubeSearchReady} from '../apps/bot/src/youtube';
process.env.DATABASE_URL='postgresql://test.invalid/test';process.env.DISCORD_GUILD_ID='888888888888888888';process.env.DISCORD_BOT_TOKEN='test-bot-token';process.env.DEMO_MODE='false';process.env.APP_URL='https://turkishpix.example';process.env.AUDIT_HMAC_KEY='test-encryption-only-key-0123456789012345678901';process.env.DISCORD_OWNER_IDS='111111111111111111';delete process.env.YOUTUBE_API_KEY;
const owner={id:'111111111111111111',username:'owner'},member={id:'222222222222222222',username:'member'},other={id:'333333333333333333',username:'other'},third={id:'444444444444444444',username:'third'},guildId='888888888888888888',channelId='999999999999999999',roleId='666666666666666666',botId='555555555555555555',videoId='M7lc1UVf-VE';
let pg:PGlite;const originalFetch=globalThis.fetch;let network:any[]=[];let sequence=0;let key='youtube-test-only-abcdefghijklmnopqrstuvwxyz';
function video(){return {id:videoId,snippet:{title:'Test &amp; video',channelTitle:'YouTube'},contentDetails:{duration:'PT3M'},status:{embeddable:true}};}
before(async()=>{pg=new PGlite();setTestDatabase({query:async(sql,params=[])=>{const r=await pg.query(sql,params);return {rows:r.rows as any[],rowCount:r.affectedRows||0};}});for(const version of ['001_initial','003_discord_roles','004_server_setup','005_community','006_voice_presence','007_entertainment','008_chat_moderation','009_community_features','010_music_application_security','011_tickets_giveaways','012_community_expansion','013_level_notifications','014_arcade_currency'])await pg.exec(await readFile(new URL('../packages/core/sql/'+version+'.sql',import.meta.url),'utf8'));});
beforeEach(async()=>{await pg.exec('DELETE FROM rate_limits; DELETE FROM community_integrations; DELETE FROM community_voice_rooms; DELETE FROM community_role_leases; DELETE FROM community_registrations; DELETE FROM member_utilities; DELETE FROM youtube_library; DELETE FROM youtube_history; DELETE FROM community_deliveries; DELETE FROM feature_records; DELETE FROM feature_receipts; DELETE FROM arcade_sessions;DELETE FROM community_currency_grants;DELETE FROM community_currency_campaigns;DELETE FROM level_up_notifications;DELETE FROM member_profiles; DELETE FROM community_settings;');network=[];globalThis.fetch=async(input:any,init:any={})=>{const url=new URL(String(input));network.push({url:url.href,init});if(url.hostname==='www.googleapis.com'){if(url.pathname.endsWith('/search'))return Response.json({items:[{id:{videoId}}]});return Response.json({items:[video()]});}if(url.pathname.endsWith('/invites'))return Response.json({code:'watch-together-test'});if(url.pathname.includes('/members/'))return Response.json({pending:false,roles:[]});if(url.pathname.endsWith('/messages'))return Response.json({id:'123456789012345678'});if(url.pathname.startsWith('/api/v10/channels/'))return Response.json({id:channelId,guild_id:guildId,type:0});throw Error('Unexpected request: '+url.pathname);};});
after(async()=>{globalThis.fetch=originalFetch;await pg.close();});
test('Eski sunucu ayarları açık yeni modüllerle uyumludur; 100 kök ve 38 ileri kullanım yardımda bulunur',()=>{const old:any=defaultCommunitySettings();delete old.expansion;const s=communitySettingsSchema.parse(old);assert.equal(s.expansion.enabled,true);assert.equal(s.expansion.rooms.enabled,true);assert.equal(s.expansion.registration.memberRoleId,'');assert.equal(commands.length,100);assert.equal(expansionUsageCount,38);assert.equal(helpEntries('gelismis').length,38);assert.ok(helpEntries('gelismis').some(e=>e.key==='topluluk oda devret'));function validate(options:any[]){assert.ok(options.length<=25);let optional=false;for(const option of options){assert.ok(option.name.length<=32);assert.ok(option.description.length<=100);if(option.type===1||option.type===2)validate(option.options||[]);else{if(option.required)assert.equal(optional,false);else optional=true;}}}for(const c of commands)validate((c as any).options||[]);});
test('AFK ve gönüllü doğum günü kayıtları kalıcıdır; geçersiz takvim günü reddedilir',async()=>{await setAFK(member,'Kahve molası','afk');assert.equal((await mentionedAFK([member.id]))[0].afk_reason,'Kahve molası');assert.equal(await clearAFK(member.id),true);assert.equal(await clearAFK(member.id),false);await assert.rejects(setBirthday(member,31,4,'invalid'),/Geçerli/);assert.equal(validBirthday(29,2),true);await setBirthday(member,29,2,'birthday');assert.equal((await birthdayCalendar()).length,1);await setBirthday(member,null,null,'remove');assert.equal((await birthdayCalendar()).length,0);});
test('YouTube anahtarı doğrulanmadan değişmez; şifrelenir ve hiçbir sonuç/audit anahtarı döndürmez',async()=>{await assert.rejects(saveYouTubeKey(member,{apiKey:key}),/owner/);await saveYouTubeKey(owner,{apiKey:key});assert.equal((await youtubeStatus()).configured,true);const secrets=(await pg.query('SELECT secret FROM community_integrations')).rows;assert.ok(!JSON.stringify(secrets).includes(key));assert.ok(!JSON.stringify((await pg.query('SELECT details FROM audit_events')).rows).includes(key));assert.ok(!network[0].url.includes(key));assert.equal(network[0].init.headers['X-Goog-Api-Key'],key);globalThis.fetch=async()=>new Response('',{status:403});await assert.rejects(saveYouTubeKey(owner,{apiKey:'replacement-test-only-abcdefghijklmnopqrstuvwxyz'}),/kurulamadı/);assert.deepEqual((await pg.query('SELECT secret FROM community_integrations')).rows,secrets);assert.equal((await verifyAudit()).valid,true);});
test('YouTube araması yalnızca resmî API’ye gider; gömülebilir videolar seçilir ve arama önbelleğe alınır',async()=>{await saveYouTubeKey(owner,{apiKey:key});network=[];const first=await searchYouTube(member.id,'test video '+(++sequence));const query=new URL(network[0].url);assert.equal(query.hostname,'www.googleapis.com');assert.equal(query.searchParams.get('videoEmbeddable'),'true');assert.equal(query.searchParams.get('type'),'video');assert.equal(first[0].title,'Test & video');assert.equal(first[0].url,'https://www.youtube.com/watch?v='+videoId);assert.ok(!JSON.stringify(first).includes(key));const calls=network.length;await searchYouTube(member.id,'test video '+sequence);assert.equal(network.length,calls);});
test('YouTube bağlantısı için anahtar gerekmez; kimlik doğrulama ve özel ağ taklitleri kabul edilmez',async()=>{assert.equal(youtubeVideoId('https://youtu.be/'+videoId),videoId);assert.equal(youtubeVideoId('https://www.youtube.com/watch?v='+videoId),videoId);for(const link of ['https://youtube.com.evil.test/watch?v='+videoId,'https://127.0.0.1/watch?v='+videoId,'https://name:pass@youtube.com/watch?v='+videoId,'http://youtube.com/watch?v='+videoId,'https://youtube.com/playlist?list=abc'])assert.throws(()=>youtubeVideoId(link));assert.equal((await youtubeVideo('https://youtu.be/'+videoId)).id,videoId);assert.equal(network.length,0);await assert.rejects(searchYouTube(member.id,'key missing '+(++sequence)),/anahtarını/);});
test('Favoriler üye hesabına bağlıdır ve aynı videoyu yeniden seçmek kaydı kaldırır',async()=>{assert.equal((await saveYouTubeFavourite(member,'https://youtu.be/'+videoId)).saved,true);assert.equal((await youtubeFavourites(member.id)).length,1);assert.equal((await youtubeFavourites(other.id)).length,0);assert.equal((await saveYouTubeFavourite(member,videoId)).saved,false);assert.equal((await youtubeFavourites(member.id)).length,0);});
test('Watch Together yalnızca doğru sunucunun ses kanalında davet oluşturur',async()=>{const previous=globalThis.fetch;globalThis.fetch=async(input:any,init:any={})=>String(input).endsWith('/invites')?previous(input,init):Response.json({id:channelId,guild_id:guildId,type:2});const invite=await createWatchTogether(channelId);assert.equal(invite.url,'https://discord.gg/watch-together-test');assert.equal(JSON.parse(network.at(-1).init.body).target_application_id,'880218394199220334');globalThis.fetch=async()=>Response.json({guild_id:'777777777777777777',type:2});await assert.rejects(createWatchTogether(channelId),/sunucudan/);});
test('Kontenjan ve bekleme listesi yeniden teslimde değişmez; ayrılanın yerine ilk bekleyen alınır',async()=>{const r=await addFeatureRecord(owner,'EVENT','Oyun gecesi',{capacity:1},{minutes:60,channelId},'event');assert.equal((await eventRSVP(member,r.id,'GOING',[],'first')).choice,'GOING');assert.equal((await eventRSVP(other,r.id,'GOING',[],'second')).choice,'WAITLIST');assert.equal((await eventRSVP(third,r.id,'GOING',[],'third')).choice,'WAITLIST');assert.equal((await eventRSVP(member,r.id,'LEAVE',[],'first')).choice,'GOING');assert.equal((await eventRSVP(member,r.id,'LEAVE',[],'leave')).count,1);const rows=await eventAttendees(r.id);assert.equal(rows.find(x=>x.user_id===other.id)?.choice,'GOING');assert.equal(rows.find(x=>x.user_id===third.id)?.choice,'WAITLIST');assert.ok(!rows.some(x=>x.user_id===member.id));const view=featureRecordView(r,1);assert.equal(view.components[0].components.length,4);assert.match(view.embeds[0].description!,/kontenjan/);});
test('Etkinlik rol şartı girişte uygulanır; rolünü kaybeden katılımcı da kaydını kaldırabilir',async()=>{const r=await addFeatureRecord(owner,'EVENT','Rol etkinliği',{requiredRoleId:roleId},{minutes:60,channelId},'role-event');await assert.rejects(eventRSVP(member,r.id,'GOING',[],'no-role'),/rol gerekli/);await eventRSVP(member,r.id,'GOING',[roleId],'has-role');assert.equal((await eventRSVP(member,r.id,'LEAVE',[],'remove-after-role')).choice,'LEAVE');});
test('Etkinlik hatırlatmaları bir kere sıraya alınır; vazgeçen kişiye gönderilmez',async()=>{const r=await addFeatureRecord(owner,'EVENT','Yaklaşan etkinlik',{reminders:[15]},{minutes:10,channelId},'reminder-event');await eventRSVP(member,r.id,'GOING',[],'join');const settings=defaultCommunitySettings();await eventMaintenance(settings);assert.equal((await pg.query("SELECT id FROM community_deliveries WHERE kind='SOCIAL'")).rows.length,0);await attachFeatureMessage(r.id,channelId,'123456789012345678');await eventMaintenance(settings);await eventMaintenance(settings);assert.equal((await pg.query("SELECT id FROM community_deliveries WHERE kind='SOCIAL'")).rows.length,1);await eventRSVP(member,r.id,'LEAVE',[],'leave');await communityDeliveryTick();assert.equal(network.filter(r=>r.url.endsWith('/messages')).length,0);assert.equal((await pg.query<any>('SELECT status FROM community_deliveries')).rows[0].status,'CANCELLED');});
test('Etkinlik düzenleme yetki ister; eski hatırlatma iptal olur, günlük tekrar tek yeni kayıt açar',async()=>{const r=await addFeatureRecord(owner,'EVENT','Tekrarlı etkinlik',{repeat:'DAILY',reminders:[15]},{minutes:10,channelId},'repeat-event');await attachFeatureMessage(r.id,channelId,'123456789012345678');await eventRSVP(member,r.id,'GOING',[],'join');await eventMaintenance(defaultCommunitySettings());await assert.rejects(editEvent(member,r.id,60,undefined,false,'not-owner'),/organizatörü/);await editEvent(owner,r.id,60,'Yeni başlık',false,'edit');assert.equal((await pg.query<any>('SELECT status FROM community_deliveries')).rows[0].status,'CANCELLED');await pg.query("UPDATE feature_records SET due_at=now()-interval '2 days' WHERE id=$1",[r.id]);await eventMaintenance(defaultCommunitySettings());await eventMaintenance(defaultCommunitySettings());const next=(await pg.query<any>("SELECT * FROM feature_records WHERE status='OPEN'")).rows;assert.equal(next.length,1);assert.equal(next[0].payload.seriesId,r.id);assert.ok(new Date(next[0].due_at).getTime()>Date.now());assert.equal((await getFeatureRecord(r.id)).status,'DONE');assert.equal((await eventAttendees(next[0].id)).length,0);});
test('Planlı duyuru saatinden önce gönderilmez; yalnızca sahibi iptal edebilir',async()=>{const r=await scheduledAnnouncement(owner,channelId,'Yarın görüşelim',60,'schedule');assert.equal((await scheduledList(owner.id)).length,1);await communityDeliveryTick();assert.equal(network.length,0);await assert.rejects(cancelScheduled(member,r.id,'wrong-owner'),/sana ait/);await cancelScheduled(owner,r.id,'cancel');assert.equal((await scheduledList(owner.id)).length,0);});
test('Ses XP’si tekrar ve günlük toplam sınırını uygular; kişisel araçlarla aynı profil korunur',async()=>{const settings=defaultCommunitySettings();settings.expansion.voiceXP.perMinute=5;settings.features.xpDailyCap=100;assert.equal(await awardVoiceXP(member,settings),true);assert.equal(await awardVoiceXP(member,settings),false);const p=await memberProfile(member.id);assert.equal(p.voice_minutes,1);assert.equal(p.xp,5);await pg.query("UPDATE member_profiles SET last_voice_xp_at=now()-interval '2 minutes',xp_today=100 WHERE user_id=$1",[member.id]);assert.equal(await awardVoiceXP(member,settings),false);settings.expansion.voiceXP.enabled=false;assert.equal(await awardVoiceXP(other,settings),false);});
test('Özel komut değişiklikleri ayarları korur; değişkenler etiket metnini nötrleştirir',async()=>{await changeCustomCommand(owner,{name:'kurallar',response:'{username} · {server}'});await changeCustomCommand(owner,{name:'destek',response:'Destek kanalı'});const settings=await communitySettings();assert.equal(settings.expansion.customCommands.length,2);assert.match(customResponse('{username}',{...member,username:'@everyone'},'guild'),/＠everyone/);await changeCustomCommand(owner,{name:'kurallar'});assert.deepEqual((await communitySettings()).expansion.customCommands.map(c=>c.name),['destek']);});
test('Panel etkinliği doğru sunucu ve owner gerektirir; takvim özel notları içermez',async()=>{await assert.rejects(createAdvancedEvent(member,{title:'Oyun',channelId,minutes:60,requestId:crypto.randomUUID(),options:{}}),/owner/);const r=await createAdvancedEvent(owner,{title:'Oyun, gecesi',channelId,minutes:60,requestId:crypto.randomUUID(),options:{description:'Yeni\nsatır'}});await addFeatureRecord(owner,'NOTE','Gizli not',{},{},'private-note');const calendar=await communityCalendar();assert.match(calendar,/BEGIN:VCALENDAR/);assert.match(calendar,/SUMMARY:Oyun\\, gecesi/);assert.ok(!calendar.includes('Gizli not'));assert.equal((await getFeatureRecord(r.id)).payload.publishPending,true);});
function fakeGuild(){
 const roles=new Collection<string,any>();const channels=new Collection<string,any>();const members=new Collection<string,any>();
 const role={id:roleId,permissions:new PermissionsBitField(0n),editable:true,managed:false};roles.set(roleId,role);
 for(const user of [owner,member,other,third]){const ownRoles=new Collection<string,any>();const perms=new PermissionsBitField(user.id===owner.id?PermissionsBitField.All:0n);members.set(user.id,{id:user.id,user:{...user,bot:false},pending:false,manageable:true,movable:true,bannable:true,kickable:true,moderatable:true,permissions:perms,roles:{cache:ownRoles,highest:{comparePositionTo:()=>user.id===owner.id?10:-1},add:async(id:any)=>ownRoles.set(typeof id==='string'?id:id.id,role),remove:async(id:any)=>ownRoles.delete(typeof id==='string'?id:id.id)},voice:{channelId:null,selfMute:false,selfDeaf:false,serverMute:false,serverDeaf:false,setChannel:async(id:string)=>{members.get(user.id).voice.channelId=id;},disconnect:async()=>{members.get(user.id).voice.channelId=null;}},setNickname:async()=>{},ban:async()=>{},kick:async()=>{},timeout:async()=>{}});}
 const guild:any={id:guildId,ownerId:owner.id,name:'TurkishPix',afkChannelId:null,roles:{fetch:async(id:string)=>roles.get(id)},members:{me:{id:botId,permissions:new PermissionsBitField(PermissionsBitField.All)},fetch:async(id:string)=>members.get(id)},channels:{cache:channels,fetch:async(id?:string)=>id?channels.get(id)||null:channels,create:async(data:any)=>{const id=String(777777777777777770n+BigInt(channels.size));const overwrites=new Collection<string,any>();for(const o of data.permissionOverwrites)overwrites.set(o.id,{id:o.id,allow:new PermissionsBitField(o.allow),deny:new PermissionsBitField(o.deny)});const room:any={...data,id,guildId,type:ChannelType.GuildVoice,members:new Collection(),permissionOverwrites:{cache:overwrites,edit:async(id:string,p:any)=>{const old=overwrites.get(id)||{id,allow:new PermissionsBitField(),deny:new PermissionsBitField()};if(p.Connect===true){old.allow.add(PermissionFlagsBits.Connect);old.deny.remove(PermissionFlagsBits.Connect);}else if(p.Connect===false){old.deny.add(PermissionFlagsBits.Connect);old.allow.remove(PermissionFlagsBits.Connect);}else if(p.Connect===null){old.allow.remove(PermissionFlagsBits.Connect);old.deny.remove(PermissionFlagsBits.Connect);}overwrites.set(id,old);},delete:async(id:string)=>overwrites.delete(id)},delete:async()=>channels.delete(id),setName:async(name:string)=>room.name=name,setUserLimit:async(n:number)=>room.userLimit=n};channels.set(id,room);return room;}}};for(const m of members.values())m.guild=guild;return {guild,channels,members,roles};
}
function interaction(group:string,sub:string,guild:any,user=member,values:any={}){const calls:any[]=[];const i:any={id:'test-expansion-'+(++sequence),guildId,channelId,guild,user,member:guild.members.fetch(user.id),memberPermissions:new PermissionsBitField(user.id===owner.id?PermissionsBitField.All:0n),commandName:'topluluk',isChatInputCommand:()=>true,options:{getSubcommandGroup:()=>group,getSubcommand:()=>sub,getString:(k:string)=>values[k]??null,getInteger:(k:string)=>values[k]??null,getUser:(k:string)=>values[k]??null,getRole:()=>values.rol??null,getChannel:()=>values.kanal??null},deferReply:async(v:any)=>calls.push({defer:v}),editReply:async(v:any)=>calls.push(v)};return {i,calls};}
test('Özel oda gerçek kanal oluşturur, tekrar ikinci oda açmaz; owner dışındaki üye başka odayı yönetemez',async()=>{const {guild,channels}=fakeGuild(),settings=defaultCommunitySettings();const first=interaction('oda','ac',guild);await handleExpansionInteraction(first.i,settings);assert.equal(channels.size,1);assert.deepEqual(first.calls[0].defer,{});await handleExpansionInteraction(first.i,settings);assert.equal(channels.size,1);const wrong=interaction('oda','ad',guild,other,{ad:'Yeni oda'});await handleExpansionInteraction(wrong.i,settings);assert.match(wrong.calls.at(-1).embeds[0].description,/kendi odanı/);const lock=interaction('oda','kilitle',guild);await handleExpansionInteraction(lock.i,settings);assert.equal(channels.first().permissionOverwrites.cache.get(guildId).deny.has(PermissionFlagsBits.Connect),true);await handleExpansionInteraction(interaction('oda','kilitac',guild).i,settings);assert.equal(channels.first().permissionOverwrites.cache.get(guildId).deny.has(PermissionFlagsBits.Connect),false);await pg.query("UPDATE community_voice_rooms SET empty_since=now()-interval '3 minutes'");await expansionTick({guilds:{cache:new Collection([[guildId,guild]])}},settings);assert.equal(channels.size,0);});
test('Oda sahipliği yalnızca odadaki üyeye devredilir; eski sahip tekrar kontrol edemez',async()=>{const {guild,channels,members}=fakeGuild(),settings=defaultCommunitySettings();await handleExpansionInteraction(interaction('oda','ac',guild).i,settings);const room=channels.first();members.get(other.id).voice.channelId=room.id;const transfer=interaction('oda','devret',guild,member,{uye:other});await handleExpansionInteraction(transfer.i,settings);assert.equal((await pg.query<any>('SELECT owner_id FROM community_voice_rooms')).rows[0].owner_id,other.id);const previous=interaction('oda','kapat',guild);await handleExpansionInteraction(previous.i,settings);assert.match(previous.calls.at(-1).embeds[0].description,/kendi odanı/);assert.equal(channels.size,1);});
test('Süreli rol yetkisiz üyede çalışmaz; kalıcı rolü sahiplenmez ve kayıt süresi dolunca rol alınır',async()=>{const {guild,members,roles}=fakeGuild(),settings=defaultCommunitySettings();const denied=interaction('yetkili','surelirol',guild,member,{uye:other,rol:roles.get(roleId),dakika:1});await handleExpansionInteraction(denied.i,settings);assert.match(denied.calls.at(-1).embeds[0].description,/yetkin yok/);assert.equal((await pg.query('SELECT * FROM community_role_leases')).rows.length,0);members.get(other.id).roles.cache.set(roleId,roles.get(roleId));const owned=interaction('yetkili','surelirol',guild,owner,{uye:other,rol:roles.get(roleId),dakika:1});await handleExpansionInteraction(owned.i,settings);assert.match(owned.calls.at(-1).embeds[0].description,/kalıcı rol/);members.get(other.id).roles.cache.delete(roleId);const grant=interaction('yetkili','surelirol',guild,owner,{uye:other,rol:roles.get(roleId),dakika:1});await handleExpansionInteraction(grant.i,settings);assert.equal(members.get(other.id).roles.cache.has(roleId),true);assert.equal((await pg.query<any>('SELECT status FROM community_role_leases')).rows[0].status,'ACTIVE');await pg.query("UPDATE community_role_leases SET expires_at=now()-interval '1 minute'");await expansionTick({guilds:{cache:new Collection([[guildId,guild]])}},settings);assert.equal(members.get(other.id).roles.cache.has(roleId),false);assert.equal((await pg.query<any>('SELECT status FROM community_role_leases')).rows[0].status,'DONE');});
test('Kayıt komutu rol seçilmeden iş yapmaz; seçilmiş rolü verir ve aynı üyeyi ikinci kez saymaz',async()=>{const {guild,members}=fakeGuild(),settings=defaultCommunitySettings();const notConfigured=interaction('kayit','onayla',guild,owner,{uye:member,isim:'Üye'});await handleExpansionInteraction(notConfigured.i,settings);assert.match(notConfigured.calls.at(-1).embeds[0].description,/rolünü seçmeli/);settings.expansion.registration.memberRoleId=roleId;await handleExpansionInteraction(interaction('kayit','onayla',guild,owner,{uye:member,isim:'Üye'}).i,settings);assert.equal(members.get(member.id).roles.cache.has(roleId),true);assert.equal((await pg.query<any>('SELECT status FROM community_registrations')).rows[0].status,'DONE');await handleExpansionInteraction(interaction('kayit','onayla',guild,owner,{uye:member,isim:'Üye'}).i,settings);assert.equal((await pg.query('SELECT * FROM community_registrations')).rows.length,1);});
test('YouTube video komutu herkese görünür kart ve oynatıcı bağlantısı verir; ses dosyası yolunu ele geçirmez',async()=>{const {guild}=fakeGuild();const i=interaction('','video',guild,member,{baglanti:'https://youtu.be/'+videoId});i.i.commandName='muzik';await handleYouTubeInteraction(i.i,defaultCommunitySettings());assert.deepEqual(i.calls[0].defer,{});assert.ok(i.calls.at(-1).components[0].components.some((b:any)=>b.url?.includes('/izle?v=')));const audio=interaction('','oynat',guild,member,{baglanti:'https://example.com/track.mp3'});audio.i.commandName='muzik';assert.equal(await handleYouTubeInteraction(audio.i,defaultCommunitySettings()),false);});
test('Discord rol cevabı belirsiz kalsa da süre kaydı korunur ve verilen rol sonradan kaldırılır',async()=>{const {guild,members,roles}=fakeGuild(),settings=defaultCommunitySettings();const target=members.get(other.id),add=target.roles.add;target.roles.add=async(id:any)=>{await add(id);throw Error('uncertain network response');};await handleExpansionInteraction(interaction('yetkili','surelirol',guild,owner,{uye:other,rol:roles.get(roleId),dakika:1}).i,settings);assert.equal((await pg.query<any>('SELECT status FROM community_role_leases')).rows[0].status,'PENDING');assert.equal(target.roles.cache.has(roleId),true);await pg.query("UPDATE community_role_leases SET expires_at=now()-interval '1 minute'");await expansionTick({guilds:{cache:new Collection([[guildId,guild]])}},settings);assert.equal(target.roles.cache.has(roleId),false);assert.equal((await pg.query<any>('SELECT status FROM community_role_leases')).rows[0].status,'DONE');});
test('Yönetim yetkili rol süreli veya kayıt rolü olarak verilemez',async()=>{const {guild,members,roles}=fakeGuild(),settings=defaultCommunitySettings();roles.get(roleId).permissions=new PermissionsBitField(PermissionFlagsBits.Administrator);await handleExpansionInteraction(interaction('yetkili','surelirol',guild,owner,{uye:other,rol:roles.get(roleId),dakika:1}).i,settings);assert.equal(members.get(other.id).roles.cache.has(roleId),false);assert.equal((await pg.query('SELECT * FROM community_role_leases')).rows.length,0);settings.expansion.registration.memberRoleId=roleId;await handleExpansionInteraction(interaction('kayit','onayla',guild,owner,{uye:other,isim:'Üye'}).i,settings);assert.equal((await pg.query('SELECT * FROM community_registrations')).rows.length,0);});
test('Kutlama silinince bekleyen doğum günü mesajı da gönderilmez; yıl ve yaş saklanmaz',async()=>{await setBirthday(member,9,10,'birthday-opt-in');await pg.query("INSERT INTO community_deliveries(id,guild_id,kind,payload) VALUES(gen_random_uuid(),$1,'SOCIAL',$2)",[guildId,{source:'BIRTHDAY',userId:member.id,channelId,mentionUser:member.id,content:'Kutlama'}]);await setBirthday(member,null,null,'opt-out');await communityDeliveryTick();assert.equal(network.length,0);assert.equal((await pg.query<any>('SELECT status FROM community_deliveries')).rows[0].status,'CANCELLED');const columns=(await pg.query<any>("SELECT column_name FROM information_schema.columns WHERE table_name='member_utilities'")).rows.map(r=>r.column_name);assert.ok(!columns.includes('birthday_year'));});
test('Ses XP’si yalnız veya yeni katılmış üyeye verilmez; iki aktif üye bir dakika sonra kazanır',async()=>{const {guild,channels,members}=fakeGuild(),settings=defaultCommunitySettings(),client={guilds:{cache:new Collection([[guildId,guild]])}};const room=await guild.channels.create({permissionOverwrites:[]});room.members.set(member.id,members.get(member.id));const realNow=Date.now;let clock=realNow();Date.now=()=>clock;try{await expansionTick(client,settings);assert.equal((await memberProfile(member.id)).xp,0);room.members.set(other.id,members.get(other.id));await expansionTick(client,settings);assert.equal((await memberProfile(member.id)).xp,0);clock+=61000;await expansionTick(client,settings);assert.equal((await memberProfile(member.id)).xp,5);assert.equal((await memberProfile(other.id)).xp,5);members.get(other.id).voice.selfMute=true;expansionVoiceChange({channelId:room.id},{id:other.id,channelId:room.id,selfMute:true});clock+=61000;await expansionTick(client,settings);assert.equal((await memberProfile(member.id)).xp,5);}finally{Date.now=realNow;}});

test('Kilit açma mevcut kanal bağlantı yasağını silmez; kilitleme önceki durumu geri yükler',async()=>{const {guild,channels}=fakeGuild(),settings=defaultCommunitySettings();await handleExpansionInteraction(interaction('oda','ac',guild).i,settings);const room=channels.first();await room.permissionOverwrites.edit(guildId,{Connect:false});await handleExpansionInteraction(interaction('oda','kilitac',guild).i,settings);assert.equal(room.permissionOverwrites.cache.get(guildId).deny.has(PermissionFlagsBits.Connect),true);await handleExpansionInteraction(interaction('oda','kilitle',guild).i,settings);await handleExpansionInteraction(interaction('oda','kilitac',guild).i,settings);assert.equal(room.permissionOverwrites.cache.get(guildId).deny.has(PermissionFlagsBits.Connect),true);});

function youtubeInteraction(kind:string,sub='',values:any={},user=member,customId='',message='123456789012345678'){
 const {guild,members}=fakeGuild(),calls:any[]=[];members.get(user.id).voice.channelId=channelId;
 const i:any={id:'youtube-ui-'+(++sequence),guildId,channelId,guild,user,message:{id:message},customId,values:values.selected?[values.selected]:[],fields:{getTextInputValue:()=>values.query||''},options:{getSubcommand:()=>sub,getString:(name:string)=>values[name]||null,getAttachment:()=>values.file||null},isChatInputCommand:()=>kind==='slash',isButton:()=>kind==='button',isStringSelectMenu:()=>kind==='select',isModalSubmit:()=>kind==='modal',deferReply:async(v:any)=>{i.deferred=true;calls.push({defer:v});},deferUpdate:async()=>{i.deferred=true;calls.push({update:true});},showModal:async(v:any)=>calls.push({modal:v}),reply:async(v:any)=>{i.replied=true;calls.push(v);},editReply:async(v:any)=>{calls.push(v);return {id:message};}};i.commandName=kind==='slash'?'muzik':undefined;return {i,calls,members};
}
test('Müzik oynat alan verilmezse public arama düğmesi açar; düğme şarkı adı penceresini gösterir',async()=>{
 const start=youtubeInteraction('slash','oynat');await handleYouTubeInteraction(start.i,defaultCommunitySettings());assert.deepEqual(start.calls[0].defer,{});const button=start.calls.at(-1).components[0].components.find((b:any)=>b.custom_id==='yt:search');assert.ok(button);
 const click=youtubeInteraction('button','',{},other,button.custom_id);await handleYouTubeInteraction(click.i,defaultCommunitySettings());assert.equal(click.calls[0].modal.custom_id,'yt:query');assert.equal(click.calls[0].modal.components[0].components[0].max_length,120);
});
test('YouTube modal araması seçim listesi açar; seçim sahte değer, yabancı üye ve farklı mesajda reddedilir',async()=>{
 await saveYouTubeKey(owner,{apiKey:key});const search=youtubeInteraction('modal','',{query:'Test şarkı'},member,'yt:query');await handleYouTubeInteraction(search.i,defaultCommunitySettings());const view=search.calls.at(-1),menu=view.components[0].components[0];assert.equal(menu.type,3);assert.equal(menu.options[0].value,videoId);assert.ok(view.embeds[0].image.url.includes(videoId));
 for(const [user,value,msg] of [[other,videoId,'123456789012345678'],[member,'AAAAAAAAAAA','123456789012345678'],[member,videoId,'123456789012345679']] as const){const bad=youtubeInteraction('select','',{selected:value},user,menu.custom_id,msg);await handleYouTubeInteraction(bad.i,defaultCommunitySettings());assert.equal(bad.calls.at(-1).flags,64);assert.equal((await pg.query('SELECT * FROM youtube_history')).rows.length,0);}
 const chosen=youtubeInteraction('select','',{selected:videoId},member,menu.custom_id);await handleYouTubeInteraction(chosen.i,defaultCommunitySettings());assert.equal(chosen.calls[0].update,true);assert.match(chosen.calls.at(-1).embeds[0].description,/Seçildi/);assert.equal((await pg.query('SELECT * FROM youtube_history')).rows.length,1);
 await handleYouTubeInteraction(youtubeInteraction('select','',{selected:videoId},member,menu.custom_id).i,defaultCommunitySettings());assert.equal((await pg.query('SELECT * FROM youtube_history')).rows.length,1);
});
test('Seçili videonun favori düğmesi kullanıcıya ait kaydı değiştirir ve ortak oturum izinli ses kanalında açılır',async()=>{
 await saveYouTubeKey(owner,{apiKey:key});const direct=youtubeInteraction('slash','video',{baglanti:'https://youtu.be/'+videoId});await handleYouTubeInteraction(direct.i,defaultCommunitySettings());const row=direct.calls.at(-1).components[0].components,listen=row.find((b:any)=>b.custom_id?.startsWith('yt:listen:')),fav=row.find((b:any)=>b.custom_id?.startsWith('yt:fav:'));
 const favorite=youtubeInteraction('button','',{},member,fav.custom_id);await handleYouTubeInteraction(favorite.i,defaultCommunitySettings());assert.equal((await youtubeFavourites(member.id)).length,1);assert.match(favorite.calls.at(-1).embeds[0].description,/Favorilerine eklendi/);
 const original=globalThis.fetch;globalThis.fetch=async(input:any,init:any={})=>String(input).endsWith('/channels/'+channelId)?Response.json({id:channelId,guild_id:guildId,type:2}):original(input,init);
 const open=youtubeInteraction('button','',{},member,listen.custom_id);await handleYouTubeInteraction(open.i,defaultCommunitySettings());assert.equal(open.calls.at(-1).components[0].components[0].url,'https://discord.gg/watch-together-test');assert.equal(JSON.parse(network.find(r=>r.url.endsWith('/invites')).init.body).target_type,2);
});
test('Süresi dolan arama yeniden kullanılamaz ve kapalı müzik modülünde modal açılmaz',async()=>{
 const direct=youtubeInteraction('slash','video',{baglanti:'https://youtu.be/'+videoId});await handleYouTubeInteraction(direct.i,defaultCommunitySettings());const id=direct.calls.at(-1).components[0].components.find((b:any)=>b.custom_id?.startsWith('yt:fav:')).custom_id;const now=Date.now;Date.now=()=>now()+11*60000;try{const expired=youtubeInteraction('button','',{},member,id);await handleYouTubeInteraction(expired.i,defaultCommunitySettings());assert.match(expired.calls.at(-1).embeds[0].description,/süresi/);assert.equal(expired.calls.at(-1).flags,64);}finally{Date.now=now;}const settings=defaultCommunitySettings();settings.music.enabled=false;const closed=youtubeInteraction('button','',{},member,'yt:search');await handleYouTubeInteraction(closed.i,settings);assert.ok(!closed.calls.some(c=>c.modal));
});
test('Şarkı adı ile dosya birlikte verilmez; dosya akışı YouTube menüsü tarafından ele geçirilmez',async()=>{
 const bad=youtubeInteraction('slash','oynat',{ara:'Şarkı',file:{url:'https://cdn.discordapp.com/test.mp3'}});await handleYouTubeInteraction(bad.i,defaultCommunitySettings());assert.match(bad.calls.at(-1).embeds[0].description,/yalnızca birini/);const file=youtubeInteraction('slash','oynat',{file:{url:'https://cdn.discordapp.com/test.mp3'}});assert.equal(await handleYouTubeInteraction(file.i,defaultCommunitySettings()),false);
});

test('YouTube açılış doğrulaması gerçek arama yolunu kullanır; aynı sürümde kotayı tekrar tüketmez',async()=>{await pg.query("DELETE FROM integration_status WHERE name='youtube-ui'");await saveYouTubeKey(owner,{apiKey:key});const first=await reportYouTubeSearchReady(defaultCommunitySettings()),second=await reportYouTubeSearchReady(defaultCommunitySettings());assert.equal(first.searchVerified,true);assert.equal(second.searchVerified,true);assert.equal(network.filter(r=>r.url.includes('/youtube/v3/search')).length,1);assert.ok(!JSON.stringify(first).includes(key));});

test('Oda oluştur kanalı en çok ses kanalı olan kategoride kurulur; tekrar kurulum yeni kanal açmaz',async()=>{
 const {guild,channels}=fakeGuild(),categoryId='777777777777777760';channels.set(categoryId,{id:categoryId,type:ChannelType.GuildCategory,position:0,permissionOverwrites:{cache:new Collection()}});const voice=await guild.channels.create({permissionOverwrites:[]});voice.parentId=categoryId;
 const first=await ensureVoiceRoomLobby(guild,{actor:owner});const second=await ensureVoiceRoomLobby(guild,{actor:owner});assert.equal(first!.created,true);assert.equal(second!.created,false);assert.equal(first!.id,second!.id);assert.equal(first!.categoryId,categoryId);assert.equal(channels.get(first!.id).name,'➕・Oda Oluştur');assert.equal((await communitySettings()).expansion.rooms.createChannelId,first!.id);assert.equal((await pg.query('SELECT * FROM community_voice_rooms')).rows.length,0);
});
test('Başlangıç ses kanalına katılan üyeye tek oda açılır; mevcut odasına geri taşınır, diğer kanallar etkilenmez',async()=>{
 const {guild,channels,members}=fakeGuild(),settings=defaultCommunitySettings(),lobby=await guild.channels.create({permissionOverwrites:[]});settings.expansion.rooms.createChannelId=lobby.id;const m=members.get(member.id);m.voice.channelId=lobby.id;const state={id:member.id,guild,member:m,channelId:lobby.id,channel:lobby};assert.equal(await handleRoomVoiceJoin({channelId:null},state,settings),true);const row=(await pg.query<any>('SELECT * FROM community_voice_rooms')).rows[0];assert.equal(m.voice.channelId,row.channel_id);assert.equal(channels.get(row.channel_id).name,'🔊・'+member.username);
 m.voice.channelId=lobby.id;await handleRoomVoiceJoin({channelId:row.channel_id},state,settings);assert.equal(m.voice.channelId,row.channel_id);assert.equal((await pg.query('SELECT * FROM community_voice_rooms')).rows.length,1);assert.equal(await handleRoomVoiceJoin({channelId:null},{...state,channelId:row.channel_id},settings),false);settings.expansion.rooms.joinToCreate=false;assert.equal(await handleRoomVoiceJoin({channelId:null},state,settings),false);
});
test('Ses XP’si seviye atlayınca son katkı kanalında duyuru kuyruğuna girer; sohbet sınırı tekrar duyuru çıkarmaz',async()=>{
 const settings=defaultCommunitySettings();await awardChatXP(member,'Önce sohbete bir katkı',settings.features,channelId);await pg.query('UPDATE member_profiles SET xp=95 WHERE user_id=$1',[member.id]);assert.equal(await awardVoiceXP(member,settings),true);const row=(await pg.query<any>('SELECT * FROM level_up_notifications')).rows[0];assert.equal(row.level,1);assert.equal(row.channel_id,channelId);assert.equal(row.xp,100);await pg.query("UPDATE member_profiles SET last_xp_at=now()-interval '2 minutes'");await awardChatXP(member,'Ses seviyesinden sonra katkı',settings.features,channelId);assert.equal((await pg.query('SELECT id FROM level_up_notifications')).rows.length,1);
});
