import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {Collection,PermissionsBitField,PermissionFlagsBits,MessageFlags} from 'discord.js';
import {setTestDatabase,config,defaultCommunitySettings,defaultFeatureSettings,communitySettingsSchema,featureCommands,featureNames,claimDaily,memberProfile,memberRank,transferCoins,purchaseBadge,giveReputation,awardChatXP,levelInfo,addFeatureRecord,listFeatureRecords,updateFeatureRecord,getFeatureRecord,participateFeature,finishGiveaway,attachFeatureMessage,featureOverview,saveAIProvider,aiProviderStatus,assistantAnswer,securityEmbed,communityDeliveryTick,verifyAudit} from '../packages/core/src/index';
import {levelNotificationTick} from '../apps/bot/src/levels';
import {commands} from '../packages/core/src/commands';
import {handleFeatureInteraction,featureTick,featureRecordView} from '../apps/bot/src/features';
process.env.DATABASE_URL='postgresql://test.invalid/test';process.env.APP_URL='https://turkishpix.example';process.env.DISCORD_GUILD_ID='888888888888888888';process.env.DISCORD_BOT_TOKEN='test-only-token';process.env.DEMO_MODE='false';process.env.AUDIT_HMAC_KEY='test-only-audit-key-0123456789012345678901';process.env.DISCORD_OWNER_IDS='111111111111111111,222222222222222222,333333333333333333,444444444444444444';delete process.env.OPENAI_API_KEY;delete process.env.GROQ_API_KEY;
const actor={id:'555555555555555555',username:'citizen'},friend={id:'666666666666666666',username:'friend'},owner={id:'111111111111111111',username:'owner'},channel='999999999999999999',roleId='777777777777777777',messageId='123456789012345678';let pg:PGlite;const realFetch=globalThis.fetch;
before(async()=>{pg=new PGlite();setTestDatabase({query:async(sql:string,params:any[]=[])=>{const r=await pg.query(sql,params);return {rows:r.rows as any[],rowCount:r.affectedRows||0};}});for(const name of ['001_initial','003_discord_roles','004_server_setup','005_community','006_voice_presence','007_entertainment','008_chat_moderation','009_community_features','010_music_application_security','011_tickets_giveaways','012_community_expansion','013_level_notifications','014_arcade_currency','015_arcade_games','016_discord_audit','017_role_automation'])await pg.exec(await readFile(new URL('../packages/core/sql/'+name+'.sql',import.meta.url),'utf8'));});
beforeEach(async()=>{globalThis.fetch=realFetch;await pg.exec('DELETE FROM feature_participants;DELETE FROM feature_records;DELETE FROM feature_receipts;DELETE FROM member_reputation;DELETE FROM arcade_sessions;DELETE FROM community_currency_grants;DELETE FROM community_currency_campaigns;DELETE FROM level_up_notifications;DELETE FROM member_profiles;DELETE FROM feature_channel_locks;DELETE FROM community_deliveries;DELETE FROM community_settings;DELETE FROM community_secrets;DELETE FROM rate_limits;DELETE FROM ai_daily_usage;');});
after(async()=>{globalThis.fetch=realFetch;await pg.close();});
function validateMessage(view:any){let total=0;for(const e of view.embeds||[]){assert.ok(e.title.length<=256);assert.ok((e.description||'').length<=4096);total+=e.title.length+(e.description||'').length;for(const f of e.fields||[]){assert.ok(f.value.length<=1024);total+=f.name.length+f.value.length;}}assert.ok(total<=6000);for(const row of view.components||[])for(const c of row.components){if(c.custom_id)assert.ok(c.custom_id.length<=100);if(c.label)assert.ok(c.label.length<=80);}assert.deepEqual(view.allowedMentions.parse,[]);}
let sequence=0;
function fakeInteraction(name:string,values:any={},extra:any={}){
 const calls:any[]=[],role:any={id:roleId,managed:false,editable:true,permissions:new PermissionsBitField(0n)},member:any={id:actor.id,pending:false,moderatable:true,roles:{cache:new Collection(),highest:{comparePositionTo:()=>1},add:async()=>{},remove:async()=>{}}};
 const ch:any={id:channel,guildId:config().guildId,type:0,topic:'Topluluk',rateLimitPerUser:0,createdTimestamp:1600000000000,isTextBased:()=>true,permissionsFor:()=>new PermissionsBitField(PermissionsBitField.All),permissionOverwrites:{cache:new Collection(),edit:async(...args:any[])=>calls.push({method:'permissions',args})},setRateLimitPerUser:async(...args:any[])=>calls.push({method:'slowmode',args}),bulkDelete:async(n:number)=>{calls.push({method:'delete',n});return {size:n};},send:async(payload:any)=>{calls.push({method:'send',payload});return {id:messageId,url:'https://discord.com/channels/'+config().guildId+'/'+channel+'/'+messageId};},messages:{fetch:async()=>({id:messageId,url:'https://discord.com/channels/'+config().guildId+'/'+channel+'/'+messageId,pin:async()=>calls.push({method:'pin'}),edit:async(payload:any)=>calls.push({method:'refresh',payload})})}};
 const guild:any={id:config().guildId,ownerId:owner.id,members:{me:{permissions:new PermissionsBitField(PermissionsBitField.All)},fetch:async(id:string)=>({...member,id})},roles:{fetch:async()=>role},channels:{cache:new Collection([[channel,ch]]),fetch:async(id?:string)=>id?ch:new Collection([[channel,ch]])}};
 const i:any={id:'feature-interaction-'+(++sequence),commandName:name,user:{...actor,avatar:null,bot:false},channelId:channel,guildId:guild.id,guild,channel:ch,memberPermissions:new PermissionsBitField(PermissionsBitField.All),appPermissions:new PermissionsBitField(PermissionsBitField.All),message:{id:messageId},options:{getString:(key:string)=>values[key]??null,getInteger:(key:string)=>values[key]??null,getUser:()=>values.uye||null,getRole:()=>role,getChannel:()=>null},isChatInputCommand:()=>true,isStringSelectMenu:()=>false,isButton:()=>false,deferReply:async(payload:any)=>{i.deferred=true;calls.push({method:'defer',payload});},reply:async(payload:any)=>{i.replied=true;calls.push({method:'reply',payload});},editReply:async(payload:any)=>{calls.push({method:'edit',payload});return {id:messageId};},update:async(payload:any)=>calls.push({method:'update',payload}),...extra};return {i,calls,ch,role};
}
test('50 benzersiz yeni özellik 100 toplam komuta eklenir; seçenek sırası ve Discord sınırları korunur',()=>{assert.equal(featureCommands.length,50);assert.equal(featureNames.length,50);assert.equal(commands.length,100);assert.equal(new Set(commands.map(c=>c.name)).size,100);for(const c of commands){assert.ok(c.description.length<=100);let optional=false;for(const o of (c as any).options||[]){if(o.required)assert.equal(optional,false,c.name);else optional=true;}}const old:any=defaultCommunitySettings();delete old.features;assert.equal(communitySettingsSchema.parse(old).features.xpDailyCap,500);});
test('Günlük ödül bir kere alınır; transfer tekrar tesliminde iki kez harcanmaz, sanal para korunur',async()=>{const settings=defaultFeatureSettings(),daily=await claimDaily(actor,settings,'daily');assert.equal(daily.reward,100);assert.deepEqual(await claimDaily(actor,settings,'daily'),daily);await assert.rejects(claimDaily(actor,settings,'daily-again'),/Bugünkü/);const move=await transferCoins(actor,friend,30,'transfer');assert.equal(move.coins,70);assert.deepEqual(await transferCoins(actor,friend,30,'transfer'),move);assert.equal((await memberProfile(friend.id)).coins,30);assert.equal((await memberProfile(actor.id)).coins,70);await assert.rejects(transferCoins(actor,friend,71,'bad-transfer'),/yetersiz/);await assert.rejects(transferCoins(actor,actor,1,'self'),/Başka/);assert.equal((await memberProfile(actor.id)).coins+(await memberProfile(friend.id)).coins,100);await assert.rejects(transferCoins(actor,friend,-1,'negative'));assert.equal((await verifyAudit()).valid,true);});
test('Mağazada bakiye düşer ve rozet kalıcıdır; aynı ürün ve günlük ikinci teşekkür reddedilir',async()=>{const policy=defaultFeatureSettings();policy.dailyReward=500;await claimDaily(actor,policy,'daily');const purchase=await purchaseBadge(actor,'kitapkurdu','buy');assert.equal(purchase.coins,350);assert.deepEqual((await memberProfile(actor.id)).inventory,['kitapkurdu']);await assert.rejects(purchaseBadge(actor,'kitapkurdu','buy-again'),/zaten/);await giveReputation(actor,friend,'thanks');assert.equal((await memberProfile(friend.id)).reputation,1);await assert.rejects(giveReputation(actor,friend,'second'),/Günde bir/);});
test('XP yeniden yüklenen günlük kota, bekleme ve tekrar hash’i ile korunur; içerik saklanmaz',async()=>{const policy=defaultFeatureSettings();policy.xpDailyCap=100;assert.equal(await awardChatXP(actor,'Merhaba topluluk',policy,channel),true);assert.equal(await awardChatXP(actor,'Başka bir mesaj',policy,channel),false);await pg.query("UPDATE member_profiles SET last_xp_at=now()-interval '2 minutes'");assert.equal(await awardChatXP(actor,'Merhaba topluluk',policy,channel),false);assert.equal(await awardChatXP(actor,'Yeni bir katkı',policy,channel),true);await pg.query("UPDATE member_profiles SET xp_today=100,last_xp_at=now()-interval '2 minutes'");assert.equal(await awardChatXP(actor,'Kotada başka katkı',policy,channel),false);const p=await memberProfile(actor.id);assert.equal(p.xp,20);assert.equal(p.messages,2);assert.ok(!JSON.stringify(p).includes('Merhaba'));assert.deepEqual(levelInfo(100).level,1);policy.xpEnabled=false;assert.equal(await awardChatXP(friend,'Yeni kullanıcı mesajı',policy,channel),false);});
test('Not, görev ve hatırlatmalar özel kalır; diğer üyeler ve yetkililer kişisel kaydı değiştiremez',async()=>{const note=await addFeatureRecord(actor,'NOTE','Özel not',{}, {},'note'),task=await addFeatureRecord(actor,'TASK','Yapılacak iş',{}, {},'task');assert.equal((await listFeatureRecords('NOTE',actor.id)).length,1);assert.equal((await listFeatureRecords('NOTE',friend.id,true)).length,0);await assert.rejects(updateFeatureRecord(friend,note.id,'CANCELLED',true,'wrong'),/yetkin/);await updateFeatureRecord(actor,task.id,'DONE',false,'done');assert.equal((await getFeatureRecord(task.id)).status,'DONE');const overview=await featureOverview();assert.ok(!JSON.stringify(overview).includes('Özel not'));assert.ok(!JSON.stringify(overview).includes('Yapılacak iş'));});
test('Katılım tekildir, etkinlikte ayrılma çalışır; çekiliş bir kere sonuçlanır ve başkası kapatamaz',async()=>{const raffle=await addFeatureRecord(actor,'GIVEAWAY','Kitap',{}, {minutes:5,channelId:channel},'raffle');await participateFeature(friend,raffle.id,'enter');await participateFeature(friend,raffle.id,'enter-again');assert.equal((await pg.query<any>('SELECT count(*)::int AS n FROM feature_participants')).rows[0].n,1);await assert.rejects(finishGiveaway(friend,raffle.id,false,'draw-wrong'),/organizatör/);const result=await finishGiveaway(actor,raffle.id,false,'draw');assert.equal(result.payload.winner,friend.id);const second=await finishGiveaway(actor,raffle.id,false,'draw-again');assert.equal(second.payload.winner,friend.id);await assert.rejects(participateFeature(friend,raffle.id,'after'),/açık değil/);const event=await addFeatureRecord(actor,'EVENT','Sohbet',{}, {minutes:5,channelId:channel},'event');assert.equal((await participateFeature(friend,event.id,'join')).joined,true);assert.equal((await participateFeature(friend,event.id,'leave')).joined,false);});
test('Yetkili değerlendirmesi özel destek ve öneride sınırlandırılır; destek logu ayrıntıları sızdırmaz',async()=>{const ticket=await addFeatureRecord(actor,'TICKET','Özel destek',{description:'Gizli destek ayrıntısı'}, {},'ticket');assert.equal((await listFeatureRecords('TICKET',friend.id,false)).length,0);assert.equal((await listFeatureRecords('TICKET',friend.id,true)).length,1);await assert.rejects(updateFeatureRecord(friend,ticket.id,'CLOSED',false,'wrong'),/yetkin/);await updateFeatureRecord(owner,ticket.id,'CLOSED',true,'close');const suggestion=await addFeatureRecord(actor,'SUGGESTION','Yeni sohbet kanalı',{}, {channelId:channel},'suggestion');await assert.rejects(updateFeatureRecord(actor,suggestion.id,'APPROVED',false,'self-approve'),/yetkin/);await updateFeatureRecord(owner,suggestion.id,'APPROVED',true,'approve');assert.equal((await getFeatureRecord(suggestion.id)).status,'APPROVED');});
test('Hatırlatıcı yeniden başlatmada bir kere kuyruğa girer; iptal ve modül kapatma gönderimi durdurur',async()=>{const settings=defaultCommunitySettings(),r=await addFeatureRecord(actor,'REMINDER','Özel hatırlatma',{}, {minutes:1},'reminder');await pg.query("UPDATE feature_records SET due_at=now()-interval '1 minute' WHERE id=$1",[r.id]);const fake=fakeInteraction('hatirlat');const client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await featureTick(client,settings);await featureTick(client,settings);assert.equal((await pg.query("SELECT id FROM community_deliveries WHERE kind='REMINDER'")).rows.length,1);await updateFeatureRecord(actor,r.id,'CANCELLED',false,'cancel');await communityDeliveryTick();assert.equal((await pg.query<any>('SELECT status FROM community_deliveries')).rows[0].status,'CANCELLED');});
test('Yeni log embed’i Türkçe işlem ve gerçek etiket kullanır; ham ID alanları ve ihlal metni bulunmaz',()=>{const embed=securityEmbed({userId:actor.id,username:actor.username,channelId:channel,rule:'Genel küfür',action:'NATIVE_BLOCKED + TIMEOUT',hits:3,roleIds:[roleId],caseId:'01234567-abcd-1234'},config().appUrl);assert.equal(embed.fields.find((f:any)=>f.name==='👤 Üye').value,`<@${actor.id}>`);assert.equal(embed.fields.find((f:any)=>f.name==='💬 Kanal').value,`<#${channel}>`);assert.equal(embed.fields.find((f:any)=>f.name==='🎭 Üyenin rolleri').value,`<@&${roleId}>`);assert.ok(!JSON.stringify(embed).includes('NATIVE_BLOCKED'));assert.ok(JSON.stringify(embed).includes('Süreli susturma'));assert.ok(!JSON.stringify(embed).includes('01234567-abcd-1234'));validateMessage({embeds:[embed],allowedMentions:{parse:[]}});});
test('Groq anahtarı şifreli kaydedilir, AI etkinleşir; 429 ücretsizi aşınca ücretli sağlayıcıya geçmez',async()=>{const key='gsk-test-private-key-abcdefghijklmnopqrstuvwxyz';await saveAIProvider(owner,{provider:'GROQ',apiKey:key,activate:true});const status=await aiProviderStatus();assert.equal(status.provider,'GROQ');assert.equal(status.model,'openai/gpt-oss-20b');assert.equal(status.configured,true);assert.ok(!JSON.stringify((await pg.query('SELECT provider FROM community_secrets')).rows).includes(key));const settings=(await pg.query<any>('SELECT settings FROM community_settings')).rows[0].settings.ai;assert.equal(settings.enabled,true);let calls=0;globalThis.fetch=async(input:any,init:any)=>{calls++;assert.equal(String(input),'https://api.groq.com/openai/v1/chat/completions');const body=JSON.parse(init.body);assert.equal(body.messages[0].role,'system');assert.equal(body.model,'openai/gpt-oss-20b');assert.ok(!JSON.stringify(body).includes(key));return Response.json({choices:[{message:{content:'Merhaba topluluk!'}}]});};assert.equal((await assistantAnswer(actor.id,'Topluluk nedir?',settings)).source,'groq');globalThis.fetch=async()=>{calls++;return Response.json({error:{message:'Do not leak'}},{status:429});};await assert.rejects(assistantAnswer(friend.id,'Bir soru',settings),(e:any)=>e.code==='AI_PROVIDER_LIMIT'&&!e.message.includes('Do not leak'));assert.equal(calls,2);assert.equal((await assistantAnswer(friend.id,'2+3',settings)).text,'Sonuç: **5**');});
test('50 gerçek komut yönlendirmesi başarılır; kayıtlar ve Discord mesajları oluşur',async()=>{
 const settings=defaultCommunitySettings();for(const name of featureNames){await pg.exec('DELETE FROM rate_limits;');const values:any={dakika:5,mesaj:'Güzel bir hatırlatma',not:'Kişisel not',gorev:'Yeni görev',odul:'Kitap hediyesi',baslik:'Topluluk haberi',aciklama:'Güzel bir etkinlik',metin:'Topluluk için yeni öneri',konu:'Yardım talebi',sebep:'Sunucu kurallarını hatırlatma',soru:'Nasıl katılırım?',cevap:'Rehber sayfasını aç.',miktar:10,urun:'kitapkurdu',saniye:5,adet:3,uye:{...friend,bot:false},durum:'APPROVED'};
  if(name==='gunluk'||name==='transfer'||name==='satinal'){await pg.exec('DELETE FROM arcade_sessions;DELETE FROM community_currency_grants;DELETE FROM community_currency_campaigns;DELETE FROM level_up_notifications;DELETE FROM member_profiles;');await claimDaily(actor,{...defaultFeatureSettings(),dailyReward:500},'seed:'+name);if(name==='gunluk')await pg.exec('DELETE FROM arcade_sessions;DELETE FROM community_currency_grants;DELETE FROM community_currency_campaigns;DELETE FROM level_up_notifications;DELETE FROM member_profiles;');}
  if(name==='tesekkur')await pg.exec('DELETE FROM member_reputation;');
  const kinds:any={hatirlatmasil:'REMINDER',notsil:'NOTE',gorevtamamla:'TASK',gorevsil:'TASK',cekilissonuc:'GIVEAWAY',cekiliskapat:'GIVEAWAY',etkinlikkapat:'EVENT',oneridurum:'SUGGESTION',destekkapat:'TICKET',uyarikaldir:'WARNING',rolmenukapat:'ROLE_MENU',ssssil:'FAQ'};
  if(kinds[name]){const r=await addFeatureRecord(actor,kinds[name],'Hazır kayıt',{userId:friend.id,roleId,description:'Detay'}, {minutes:5,channelId:channel},'seed-record:'+name);values.kayit=r.id;}
  if(name==='sabitle')values.mesaj=messageId;
  if(name==='kilitac')await pg.query('INSERT INTO users(id,username) VALUES($1,$2) ON CONFLICT DO NOTHING',[actor.id,actor.username]);
  if(name==='kilitac')await pg.query('INSERT INTO feature_channel_locks(guild_id,channel_id,original,locked_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[config().guildId,channel,{send:null,threads:true},actor.id]);
  const fake=fakeInteraction(name,values);assert.equal(await handleFeatureInteraction(fake.i,settings),true,name);const view=fake.calls.filter(x=>x.method==='edit').at(-1)?.payload;assert.ok(view,name);assert.ok(!view.embeds[0].title.includes('tamamlanamadı'),name+': '+JSON.stringify(view));validateMessage(view);if(['notlar','gorevler','destek','hatirlat','uyarilar'].includes(name))assert.equal(fake.calls.find(x=>x.method==='defer').payload.flags,MessageFlags.Ephemeral);if(['ozellikler','rank','seviye','siralama','cuzdan','gunluk','magaza','etkinlik','oner','rolmenu','sss','kanalbilgi'].includes(name))assert.equal(fake.calls.find(x=>x.method==='defer').payload.flags,undefined,name+' kanalda herkese görünmeli');
 }
});
test('Yetkisiz komut, yanlış kayıt düğmesi, tehlikeli rol ve sahte temizleme onayı işlem yapamaz',async()=>{const settings=defaultCommunitySettings();const denied=fakeInteraction('uyar',{uye:friend,sebep:'Test'},{memberPermissions:new PermissionsBitField(0n)});await handleFeatureInteraction(denied.i,settings);assert.ok(denied.calls.at(-1).payload.embeds[0].description.includes('yetkin yok'));const role=fakeInteraction('rolmenu',{baslik:'Kozmetik rol'});role.role.permissions=new PermissionsBitField(PermissionFlagsBits.Administrator);await handleFeatureInteraction(role.i,settings);assert.ok(role.calls.at(-1).payload.embeds[0].description.includes('kozmetik'));const clean=fakeInteraction('',{}, {isChatInputCommand:()=>false,isButton:()=>true,customId:'featureclean:'+actor.id+':'+channel+':3:'+String(Date.now()+60000)+':fake'});await handleFeatureInteraction(clean.i,settings);assert.equal(clean.calls.filter(x=>x.method==='delete').length,0);const record=await addFeatureRecord(actor,'EVENT','Etkinlik',{}, {minutes:5,channelId:channel},'event');await attachFeatureMessage(record.id,channel,messageId);const wrong=fakeInteraction('',{}, {isChatInputCommand:()=>false,isButton:()=>true,customId:`feature:${record.id}:join`,message:{id:'different'}});await handleFeatureInteraction(wrong.i,settings);assert.equal((await pg.query('SELECT * FROM feature_participants')).rows.length,0);});
test('İmzalı temizleme onayı yalnızca bir kez siler; kilit açma eski üç durumlu izinleri korur',async()=>{const settings=defaultCommunitySettings(),start=fakeInteraction('temizle',{adet:4});await handleFeatureInteraction(start.i,settings);const customId=start.calls.find(c=>c.method==='edit').payload.components[0].components[0].custom_id;const click=fakeInteraction('',{}, {isChatInputCommand:()=>false,isButton:()=>true,customId});await handleFeatureInteraction(click.i,settings);await handleFeatureInteraction(click.i,settings);assert.equal(click.calls.filter(c=>c.method==='delete').length,1);assert.equal(click.calls.find(c=>c.method==='delete').n,4);const lock=fakeInteraction('kilitle');await handleFeatureInteraction(lock.i,settings);const unlock=fakeInteraction('kilitac');await handleFeatureInteraction(unlock.i,settings);const changes=unlock.calls.find(c=>c.method==='permissions').args[1];assert.deepEqual(changes,{SendMessages:null,SendMessagesInThreads:null});});

test('Uzun kişisel notlar sayfalanır; işlem makbuzu ham notu saklamaz ve yabancı liste okunamaz',async()=>{const settings=defaultCommunitySettings(),notes=[];for(let n=0;n<5;n++)notes.push(await addFeatureRecord(actor,'NOTE',('Not '+n+' ').padEnd(995,'*'),{}, {},'long-note-'+n));const receipts=JSON.stringify((await pg.query('SELECT result FROM feature_receipts')).rows);assert.ok(!receipts.includes('Not 0'));assert.ok(receipts.includes('__recordId'));assert.equal((await addFeatureRecord(actor,'NOTE','Başka metin',{}, {},'long-note-0')).id,notes[0].id);const start=fakeInteraction('notlar');await handleFeatureInteraction(start.i,settings);const view=start.calls.find(c=>c.method==='edit').payload;assert.equal(view.embeds.length,2);assert.ok(view.embeds[0].description.length>1500);validateMessage(view);const nextId=view.components[0].components[0].custom_id;const next=fakeInteraction('',{}, {isChatInputCommand:()=>false,isButton:()=>true,customId:nextId});await handleFeatureInteraction(next.i,settings);const nextView=next.calls.find(c=>c.method==='edit').payload;assert.equal(nextView.embeds.length,2);assert.notEqual(nextView.embeds[0].footer.text,view.embeds[0].footer.text);validateMessage(nextView);const stranger=fakeInteraction('',{}, {user:friend,isChatInputCommand:()=>false,isButton:()=>true,customId:nextId});await handleFeatureInteraction(stranger.i,settings);assert.ok(stranger.calls.at(-1).payload.embeds[0].description.includes('başka bir üyeye ait'));});
test('Talep edilen hatırlatıcı DM’i tek embed olarak gider; görev tamamlanır ve başka üyeye etiket bildirimi düşmez',async()=>{const settings=defaultCommunitySettings(),r=await addFeatureRecord(actor,'REMINDER','Kitapları getir',{}, {minutes:1},'reminder');await pg.query("UPDATE feature_records SET due_at=now()-interval '1 minute' WHERE id=$1",[r.id]);const fake=fakeInteraction('hatirlat'),client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await featureTick(client,settings);const sent:any[]=[];globalThis.fetch=async(input:any,init:any)=>{const url=String(input);if(url.endsWith('/members/'+actor.id))return Response.json({pending:false});if(url.endsWith('/users/@me/channels'))return Response.json({id:channel});if(url.endsWith('/messages')){sent.push(JSON.parse(init.body));return Response.json({id:messageId});}throw Error('Unexpected request');};await communityDeliveryTick();assert.equal(sent.length,1);assert.equal(sent[0].content,undefined);assert.equal(sent[0].embeds[0].title,'⏰ Hatırlatma zamanı');assert.equal(sent[0].embeds[0].description,'Kitapları getir');assert.deepEqual(sent[0].allowed_mentions,{parse:[],users:[]});assert.equal((await getFeatureRecord(r.id)).status,'DONE');await featureTick(client,settings);assert.equal((await pg.query("SELECT id FROM community_deliveries WHERE kind='REMINDER'")).rows.length,1);});

test('Rank sıralaması ilk 10 dışındaki üyeyi ve eşit XP durumunu doğru hesaplar',async()=>{
 for(let n=0;n<14;n++){const id=String(500000000000000000n+BigInt(n));await pg.query('INSERT INTO users(id,username) VALUES($1,$2)',[id,'Üye '+n]);await pg.query('INSERT INTO member_profiles(guild_id,user_id,xp) VALUES($1,$2,$3)',[config().guildId,id,1000-n*50]);}
 const last=await memberRank('500000000000000013');assert.equal(last.rank,14);assert.equal(last.rankedMembers,14);assert.equal((await memberRank(actor.id)).rank,null);
 await pg.query('UPDATE member_profiles SET xp=1000 WHERE user_id=$1',['500000000000000001']);assert.equal((await memberRank('500000000000000000')).rank,1);assert.equal((await memberRank('500000000000000001')).rank,2);
});
test('Eski üyeprofil komutu kapatma ayarı rank adına taşınır ve diğer tercihler korunur',()=>{const settings=communitySettingsSchema.parse({...defaultCommunitySettings(),features:{...defaultFeatureSettings(),disabledCommands:['uyeprofil','cuzdan'],xpPerMessage:15}});assert.deepEqual(settings.features.disabledCommands,['rank','cuzdan']);assert.equal(settings.features.xpPerMessage,15);});
test('Rank komutu fotoğraflı dosya izni yokken de public metin kartını gösterir',async()=>{const fake=fakeInteraction('rank',{}, {appPermissions:new PermissionsBitField(PermissionFlagsBits.EmbedLinks)});await handleFeatureInteraction(fake.i,defaultCommunitySettings());const view=fake.calls.at(-1).payload;assert.equal(view.files,undefined);assert.equal(fake.calls.find(c=>c.method==='defer').payload.flags,undefined);assert.match(view.embeds[0].fields.find((f:any)=>f.name==='🏆 Sunucu sırası').value,/Henüz/);});

test('Silinen eski kart yeniden gönderilmez ve worker aynı eksik mesajı tekrar sorgulamaz',async()=>{
 const record=await addFeatureRecord(actor,'EVENT','Eski kart',{reminders:[]},{minutes:60,channelId:channel},'old-card');await attachFeatureMessage(record.id,channel,messageId);await pg.query('UPDATE feature_records SET discord_updated_at=NULL WHERE id=$1',[record.id]);const fake=fakeInteraction('etkinlikler');let attempts=0;fake.ch.messages.fetch=async()=>{attempts++;throw {code:10008};};const client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await featureTick(client,defaultCommunitySettings());await featureTick(client,defaultCommunitySettings());assert.equal(attempts,1);assert.ok(!fake.calls.some(c=>c.method==='send'));assert.equal((await getFeatureRecord(record.id)).status,'OPEN');
});
test('Geçici mesaj izni hatası beş dakika bekler; izin düzeldikten sonra kart yenilenir',async()=>{
 const record=await addFeatureRecord(actor,'EVENT','Bekleyen kart',{reminders:[]},{minutes:60,channelId:channel},'pending-card');await attachFeatureMessage(record.id,channel,messageId);await pg.query('UPDATE feature_records SET discord_updated_at=NULL WHERE id=$1',[record.id]);const fake=fakeInteraction('etkinlikler'),realFetch=fake.ch.messages.fetch;let attempts=0;fake.ch.messages.fetch=async()=>{attempts++;throw {code:50013};};const client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await featureTick(client,defaultCommunitySettings());await featureTick(client,defaultCommunitySettings());assert.equal(attempts,1);fake.ch.messages.fetch=async()=>{attempts++;return realFetch();};const now=Date.now;Date.now=()=>now()+6*60000;try{await featureTick(client,defaultCommunitySettings());}finally{Date.now=now;}assert.equal(attempts,2);assert.ok(fake.calls.some(c=>c.method==='refresh'));
});

test('Seviye sınırı XP işlemiyle tek kayıt oluşturur; aynı kanalda fotoğraflı kart ve yalnız ilgili üyeye ping gider',async()=>{
 const settings=defaultCommunitySettings();await claimDaily(actor,settings.features,'seed');await pg.query('UPDATE member_profiles SET xp=95 WHERE user_id=$1',[actor.id]);
 assert.equal(await awardChatXP(actor,'Seviye atlayacak bir katkı',settings.features,channel),true);assert.equal(await awardChatXP(actor,'Bir sonraki katkı',settings.features,channel),false);
 const row=(await pg.query<any>('SELECT * FROM level_up_notifications')).rows[0];assert.equal(row.level,1);assert.equal(row.xp,105);assert.equal(row.channel_id,channel);
 const fake=fakeInteraction('rank');fake.i.guild.name='TurkishPix';fake.i.guild.members.fetch=async()=>({id:actor.id,user:{...actor,avatar:null,bot:false},displayName:'Topluluk Üyesi'});
 globalThis.fetch=async()=>new Response(null,{status:404});const client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await levelNotificationTick(client,settings);await levelNotificationTick(client,settings);
 const sent=fake.calls.filter(c=>c.method==='send');assert.equal(sent.length,1);assert.match(sent[0].payload.content,new RegExp('<@'+actor.id+'>'));assert.deepEqual(sent[0].payload.allowedMentions,{parse:[],users:[actor.id],repliedUser:false});assert.equal(sent[0].payload.embeds[0].image.url,'attachment://turkishpix-seviye.png');assert.deepEqual([...sent[0].payload.files[0].attachment.subarray(0,8)],[137,80,78,71,13,10,26,10]);assert.equal(sent[0].payload.enforceNonce,true);assert.equal((await pg.query<any>('SELECT status,message_id FROM level_up_notifications')).rows[0].status,'SENT');
 await pg.query("UPDATE member_profiles SET last_xp_at=now()-interval '2 minutes'");assert.equal(await awardChatXP(actor,'Seviye sonrasındaki başka katkı',settings.features,channel),true);assert.equal((await pg.query('SELECT id FROM level_up_notifications')).rows.length,1);
});
test('Seviye duyurusu kanal seçimini ve kapatma tercihini uygular; izin hatasında kuyruğu korur',async()=>{
 const settings=defaultCommunitySettings();settings.features.levelUpChannel='888888888888888887';await claimDaily(actor,settings.features,'seed');await pg.query('UPDATE member_profiles SET xp=95 WHERE user_id=$1',[actor.id]);await awardChatXP(actor,'Seçili kanala bir katkı',settings.features,channel);assert.equal((await pg.query<any>('SELECT channel_id FROM level_up_notifications')).rows[0].channel_id,settings.features.levelUpChannel);
 const fake=fakeInteraction('rank');fake.ch.id=settings.features.levelUpChannel;fake.i.guild.members.fetch=async()=>({id:actor.id,user:{...actor,bot:false}});fake.ch.permissionsFor=()=>new PermissionsBitField(0n);const client={guilds:{cache:new Collection([[config().guildId,fake.i.guild]])}};await levelNotificationTick(client,settings);assert.equal(fake.calls.filter(c=>c.method==='send').length,0);assert.equal((await pg.query<any>('SELECT status,attempts FROM level_up_notifications')).rows[0].status,'PENDING');
 settings.features.levelUpEnabled=false;await levelNotificationTick(client,settings);assert.equal((await pg.query<any>('SELECT status FROM level_up_notifications')).rows[0].status,'CANCELLED');await pg.query("UPDATE member_profiles SET xp=395,last_xp_at=now()-interval '2 minutes'");await awardChatXP(actor,'Duyuru kapalıyken sonraki seviye',settings.features,channel);assert.equal((await pg.query('SELECT id FROM level_up_notifications')).rows.length,1);
});
