import {test,before,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {config,setTestDatabase,configureTickets,ticketSettings,ticketOverwrites,ticketIsStaff,openTicket,closeTicket,materializeTicket,ticketTick,createGiveaway,publishGiveaway,manageGiveaway,participateFeature,finishGiveaway,getFeatureRecord,drawGiveawayWinners,addFeatureRecord,defaultCommunitySettings,effectiveChannelPermissions} from '../packages/core/src/index';
import {featureTick} from '../apps/bot/src/features';
import {commands} from '../packages/core/src/commands';
import {handleSupportInteraction} from '../apps/bot/src/support';
import {GET,POST} from '../apps/web/src/app/api/[...path]/route';
import {sha256,giveawayRequestId} from '../packages/core/src/index';
import {ticketTopics,ticketChannelName} from '../packages/core/src/ticket-policy';
process.env.DATABASE_URL='postgresql://test.invalid/test';process.env.APP_URL='https://turkishpix.example';process.env.DISCORD_GUILD_ID='888888888888888888';process.env.DISCORD_BOT_TOKEN='test-only-token';process.env.DEMO_MODE='false';process.env.AUDIT_HMAC_KEY='test-only-audit-key-0123456789012345678901';process.env.DISCORD_OWNER_IDS='111111111111111111';
const owner={id:'111111111111111111',username:'owner'},member={id:'222222222222222222',username:'member'},stranger={id:'333333333333333333',username:'stranger'},staffId='444444444444444444',botId='555555555555555555',roleId='666666666666666666',categoryId='777777777777777777',panelId='999999999999999999';
const initial={channelId:panelId,categoryId,staffRoleIds:[roleId]};let pg:PGlite,channels:any[],messages:Map<string,any[]>,calls:any[],sequence=0,failTicketMessage=false,pending=false,roleMentionable=true,botPermissions='8';const realFetch=globalThis.fetch;
before(async()=>{pg=new PGlite();setTestDatabase({query:async(sql,params=[])=>{const r=await pg.query(sql,params);return {rows:r.rows as any[],rowCount:r.affectedRows||0};}});for(const version of ['001_initial','003_discord_roles','004_server_setup','005_community','006_voice_presence','007_entertainment','008_chat_moderation','009_community_features','010_music_application_security','011_tickets_giveaways','012_community_expansion','013_level_notifications','014_arcade_currency'])await pg.exec(await readFile(new URL('../packages/core/sql/'+version+'.sql',import.meta.url),'utf8'));});
beforeEach(async()=>{await pg.exec('DELETE FROM feature_participants;DELETE FROM feature_records;DELETE FROM feature_receipts;DELETE FROM ticket_settings;DELETE FROM community_settings;DELETE FROM community_deliveries;DELETE FROM rate_limits;');channels=[{id:panelId,guild_id:config().guildId,type:0,name:'bilet-ac',permission_overwrites:[]},{id:categoryId,guild_id:config().guildId,type:4,name:'Destek biletleri',permission_overwrites:[]}];messages=new Map();calls=[];failTicketMessage=false;pending=false;roleMentionable=true;botPermissions='8';globalThis.fetch=async(input:any,init:any={})=>{const url=new URL(String(input)),path=url.pathname.replace('/api/v10',''),method=init.method||'GET',body=init.body?JSON.parse(init.body):undefined;calls.push({path,method,body});if(path==='/users/@me')return Response.json({id:botId});if(path.endsWith('/roles'))return Response.json([{id:config().guildId,name:'@everyone',permissions:'0',managed:false},{id:roleId,name:'Yetkililer',permissions:'0',managed:false,mentionable:roleMentionable},{id:botId,name:'Bot',permissions:botPermissions,managed:true}]);if(path.includes('/members/')){const id=path.split('/').at(-1);return Response.json({user:{id,bot:id===botId},roles:id===botId?[botId]:id===staffId?[roleId]:[],pending:pending&&id!==botId});}if(path===`/guilds/${config().guildId}/channels`){if(method==='GET')return Response.json(channels);const ch={...body,id:String(100000000000000000n+BigInt(++sequence)),guild_id:config().guildId};channels.push(ch);return Response.json(ch);}const m=/^\/channels\/(\d+)\/messages(?:\/(\d+))?$/.exec(path);if(m){const list=messages.get(m[1])||[];if(method==='GET')return Response.json(list);if(method==='PATCH'){const msg=list.find(mes=>mes.id===m[2]);if(!msg)return Response.json({}, {status:404});Object.assign(msg,body);return Response.json(msg);}if(failTicketMessage&&m[1]!==panelId){failTicketMessage=false;return Response.json({}, {status:503});}const msg={...body,id:String(200000000000000000n+BigInt(++sequence)),author:{id:botId}};list.unshift(msg);messages.set(m[1],list);return Response.json(msg);}const channel=/^\/channels\/(\d+)$/.exec(path);if(channel){const ch=channels.find(c=>c.id===channel[1]);if(method==='PATCH')Object.assign(ch,body);return Response.json(ch);}throw Error('Unexpected REST route '+path);};});
after(async()=>{globalThis.fetch=realFetch;await pg.close();});
test('Silinen eski panel başka kanaldaki yeni bilet kurulumunu engellemez',async()=>{
 await configureTickets(owner,initial);const nextId='999999999999999998';channels.push({...channels[0],id:nextId});messages.delete(panelId);await configureTickets(owner,{...initial,channelId:nextId});assert.equal((await ticketSettings()).panel_channel_id,nextId);assert.equal(messages.get(nextId)?.length,1);await ticketTick();assert.equal(messages.get(nextId)?.length,1);
});
test('Silinmiş bilet mesajı veya kanalı aynı bilet kaydıyla onarılır; kanal çoğalmaz',async()=>{
 await configureTickets(owner,initial);const ticket=await openTicket(member,'support','recover-deleted');messages.set(ticket.channel_id!,[]);await closeTicket(member,ticket.id,false,'close-after-message-deleted');let r=await getFeatureRecord(ticket.id);assert.equal(r.status,'CLOSED');assert.equal(r.channel_id,ticket.channel_id);assert.equal(messages.get(r.channel_id!)?.length,1);
 const second=await openTicket(stranger,'support','recover-channel');channels=channels.filter(c=>c.id!==second.channel_id);messages.delete(second.channel_id!);r=await materializeTicket(second.id);assert.notEqual(r.channel_id,second.channel_id);await materializeTicket(second.id);assert.equal(channels.filter(c=>c.topic==='turkishpix-ticket:'+second.id).length,1);assert.equal(messages.get(r.channel_id!)?.length,1);
});
test('404’lü eski bilet paneli her worker turunda tekrar istek göndermez',async()=>{
 await configureTickets(owner,initial);await pg.query('UPDATE ticket_settings SET panel_updated_at=NULL');const savedFetch=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>String(input).includes('/messages')?Response.json({code:10003},{status:404}):savedFetch(input,init);await ticketTick();const first=calls.length;await ticketTick();assert.equal(calls.length,first);assert.ok((await ticketSettings()).settings.enabled);
});
test('100 katılımcılı aktif çekiliş yeni worker ile aynı mesaj, süre ve katılımcılarla devam eder',async()=>{
 const r=await createGiveaway(owner,{title:'Aktif ödül',channelId:panelId,minutes:60,winnerCount:2,requestId:randomUUID()});for(let n=0;n<100;n++){const id=String(700000000000000000n+BigInt(n));await pg.query('INSERT INTO users(id,username) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,'Üye '+n]);await pg.query('INSERT INTO feature_participants(record_id,user_id) VALUES($1,$2)',[r.id,id]);}
 await pg.query('UPDATE feature_records SET updated_at=now(),discord_updated_at=NULL WHERE id=$1',[r.id]);const before=await getFeatureRecord(r.id),entries=(await pg.query<any>('SELECT user_id FROM feature_participants WHERE record_id=$1 ORDER BY user_id',[r.id])).rows;let edits=0;
 const guild={id:config().guildId,channels:{fetch:async()=>({messages:{fetch:async()=>({edit:async(view:any)=>{edits++;Object.assign(messages.get(panelId)![0],view);}})}})}};const freshClient=()=>({guilds:{cache:new Map([[config().guildId,guild]])}});
 await featureTick(freshClient(),defaultCommunitySettings(),false);await featureTick(freshClient(),defaultCommunitySettings(),false);const after=await getFeatureRecord(r.id);for(const field of ['id','status','channel_id','message_id','due_at','title'] as const)assert.deepEqual(after[field],before[field]);assert.equal(after.status,'OPEN');assert.equal(edits,1);assert.deepEqual((await pg.query('SELECT user_id FROM feature_participants WHERE record_id=$1 ORDER BY user_id',[r.id])).rows,entries);assert.equal(messages.get(panelId)?.length,1);
 const done=await finishGiveaway(owner,r.id,true,'end-after-restart'),again=await finishGiveaway(owner,r.id,true,'repeat-after-restart');assert.equal(done.payload.entries,100);assert.equal(new Set(done.payload.winners).size,2);assert.deepEqual(again.payload.winners,done.payload.winners);assert.equal((await pg.query('SELECT * FROM feature_participants WHERE record_id=$1',[r.id])).rows.length,100);
});
test('Silinmiş çekiliş mesajı yeniden oluşturulmaz; kayıt ve katılım kaybolmaz, sonuç bir kez seçilir',async()=>{
 const r=await createGiveaway(owner,{title:'Korunan kayıt',channelId:panelId,minutes:60,requestId:randomUUID()});await participateFeature(member,r.id,'preserved-entry');messages.delete(panelId);await publishGiveaway(r.id);const first=calls.length;await publishGiveaway(r.id);assert.equal(calls.length,first);const saved=await getFeatureRecord(r.id);assert.equal(saved.status,'OPEN');assert.equal(saved.message_id,r.message_id);assert.equal(saved.payload.discordMessageMissing,true);assert.equal((await pg.query('SELECT * FROM feature_participants WHERE record_id=$1',[r.id])).rows.length,1);await manageGiveaway(owner,r.id,'end',true,'end-missing');assert.equal((await getFeatureRecord(r.id)).payload.winner,member.id);assert.equal(messages.get(panelId),undefined);
});
test('Beş kategori düğmesi form açmadan konu-kullanıcı kanalını oluşturur; serbest konu kabul edilmez',async()=>{
 await configureTickets(owner,initial);const panel=messages.get(panelId)![0];
 for(const topic of ticketTopics){
  const responses:any[]=[];const i:any={id:'topic-'+topic.id,isChatInputCommand:()=>false,isButton:()=>true,isModalSubmit:()=>false,customId:'ticket:open:'+topic.id,user:member,channelId:panelId,message:panel,memberPermissions:{has:()=>false},showModal:async()=>{throw Error('Konu formu açılmamalı');},deferReply:async()=>{i.deferred=true;},editReply:async(v:any)=>responses.push(v)};
  assert.equal(await handleSupportInteraction(i,defaultCommunitySettings()),true);
  const r=(await pg.query<any>("SELECT * FROM feature_records WHERE payload->>'topicId'=$1",[topic.id])).rows[0];
  assert.ok(r,responses[0]?.embeds[0].description);assert.equal(r.title,topic.label);assert.equal(channels.find(c=>c.id===r.channel_id).name,topic.slug+'-member');assert.match(responses[0].embeds[0].description,/<#\d+>/);
 }
 await assert.rejects(openTicket(member,'Serbest konu yazısı','invalid'),/kategori/);assert.equal(channels.length,7);
 for(const command of commands.filter(c=>['destek','bilet'].includes(c.name))){const options=command.name==='bilet'?(command as any).options.find((s:any)=>s.name==='ac').options:(command as any).options;assert.equal(options.length,1);assert.equal(options[0].name,'tur');assert.deepEqual(options[0].choices,ticketTopics.map(t=>({name:t.label,value:t.id})));}
});
test('Kullanıcı adı Türkçe ve dekoratif yazıdan güvenli kanal adına çevrilir',()=>{
 assert.equal(ticketChannelName(ticketTopics[0],'Çağrı.İŞIK_42'),'odul-talebi-cagri-isik-42');
 assert.equal(ticketChannelName(ticketTopics[1],'𝙁𝙧𝙞𝙯𝙯 🤍'),'destek-frizz');
 assert.equal(ticketChannelName(ticketTopics[1],'🧡'),'destek-uye');
 assert.ok(ticketChannelName(ticketTopics[0],'a'.repeat(200)).length<=100);
});
test('Eski UUID adlı kanal ve tek düğmeli panel kendiliğinden yenilenir; ikinci tur yeniden yazmaz',async()=>{
 await configureTickets(owner,initial);const r=await openTicket(member,'support','legacy');const ch=channels.find(c=>c.id===r.channel_id);ch.name='bilet-'+r.id.slice(0,8);
 await pg.query("UPDATE feature_records SET title='Eski özel konu',payload=payload-'presentationVersion'-'topicId'-'requesterUsername' WHERE id=$1",[r.id]);
 await pg.query("UPDATE ticket_settings SET settings=settings-'panelVersion'");messages.get(panelId)![0].components=[];
 await ticketTick();assert.equal(ch.name,'destek-member');assert.equal(messages.get(panelId)![0].components[0].components.length,5);
 assert.equal((await getFeatureRecord(r.id)).payload.presentationVersion,2);assert.equal((await getFeatureRecord(r.id)).owner_id,member.id);
 const count=calls.filter(c=>c.method==='PATCH').length;await ticketTick();assert.equal(calls.filter(c=>c.method==='PATCH').length,count);assert.equal(channels.length,3);
});
test('Başka mesaja veya kanala taşınan kategori düğmesi bilet açamaz',async()=>{
 await configureTickets(owner,initial);const responses:any[]=[];const i:any={id:'foreign',isChatInputCommand:()=>false,isButton:()=>true,isModalSubmit:()=>false,customId:'ticket:open:reward',user:member,channelId:panelId,message:{id:'123456789012345678'},memberPermissions:{has:()=>false},deferReply:async()=>{i.deferred=true;},editReply:async(v:any)=>responses.push(v)};
 await handleSupportInteraction(i,defaultCommunitySettings());assert.match(responses[0].embeds[0].description,/etkin değil/);assert.equal(channels.length,2);
});
test('Kanal/kategori/rol kurulumu gerçek katılım düğmesini gönderir; ayar yenileme ikinci panel açmaz',async()=>{await configureTickets(owner,initial);const settings=await ticketSettings();assert.equal(settings?.panel_channel_id,panelId);assert.equal(messages.get(panelId)?.length,1);assert.deepEqual(messages.get(panelId)![0].components[0].components.map((b:any)=>b.custom_id),['reward','support','complaint','application','other'].map(id=>'ticket:open:'+id));await configureTickets(owner,{...initial,title:'Yardım merkezi'});assert.equal(messages.get(panelId)?.length,1);assert.ok(messages.get(panelId)![0].embeds[0].title.includes('Yardım merkezi'));await assert.rejects(configureTickets(stranger,initial),/owner/);});
test('Özel bilet kanalı yalnızca talep sahibi, seçilen yetkili ve bota izin verir; yalnızca seçilen rol etiketlenir',async()=>{await configureTickets(owner,initial);const r=await openTicket(member,'support','open');const ch=channels.find(c=>c.id===r.channel_id);assert.equal(ch.parent_id,categoryId);const writes=ticketOverwrites(config().guildId,botId,member.id,[roleId]);assert.deepEqual(ch.permission_overwrites,writes);assert.equal(BigInt(writes.find(o=>o.id===botId)!.allow)&268435456n,0n);assert.equal(effectiveChannelPermissions(1024n|2048n,[],stranger.id,ch,config().guildId)&1024n,0n);assert.ok(effectiveChannelPermissions(0n,[],member.id,ch,config().guildId)&1024n);assert.ok(effectiveChannelPermissions(0n,[roleId],staffId,ch,config().guildId)&1024n);const msg=messages.get(r.channel_id!)![0];assert.deepEqual(msg.allowed_mentions,{parse:[],roles:[roleId],users:[member.id]});assert.ok(msg.content.includes('<@&'+roleId+'>'));assert.equal((await openTicket(member,'support','open')).id,r.id);assert.equal(channels.filter(c=>c.topic?.startsWith('turkishpix-ticket')).length,1);assert.equal(messages.get(r.channel_id!)?.length,1);});
test('Discord gönderimi yarıda kesilse de kayıt korunur; yeniden deneme mevcut kanalı bulur',async()=>{await configureTickets(owner,initial);failTicketMessage=true;await assert.rejects(openTicket(member,'support','recover'),/503/);const row=(await pg.query<any>("SELECT * FROM feature_records WHERE kind='TICKET'")).rows[0];assert.equal(row.channel_id,null);await ticketTick();const fixed=await getFeatureRecord(row.id);assert.ok(fixed.channel_id);assert.ok(fixed.message_id);assert.equal(channels.filter(c=>c.topic?.startsWith('turkishpix-ticket')).length,1);await materializeTicket(row.id);assert.equal(messages.get(fixed.channel_id!)?.length,1);});
test('Başka üye bilet kapatamaz; yetkili kapatınca talep sahibinin yazması durur ve geçmiş görünür',async()=>{await configureTickets(owner,initial);const r=await openTicket(member,'support','close');await assert.rejects(closeTicket(stranger,r.id),/kapatamazsın/);assert.equal((await getFeatureRecord(r.id)).status,'OPEN');assert.equal(await ticketIsStaff(staffId,r),true);await closeTicket({id:staffId,username:'staff'},r.id,true);const ch=channels.find(c=>c.id===r.channel_id);const p=effectiveChannelPermissions(1024n|2048n|16384n,[],member.id,ch,config().guildId);assert.equal(p&2048n,0n);assert.ok(p&1024n);assert.equal(messages.get(r.channel_id!)![0].components.length,0);assert.equal((await getFeatureRecord(r.id)).status,'CLOSED');});
test('Yanlış kanal, kategori, everyone rolü, etiket ve eksik bot izinleri kurulumda reddedilir',async()=>{await assert.rejects(configureTickets(owner,{...initial,categoryId:panelId}),/kategori/);await assert.rejects(configureTickets(owner,{...initial,staffRoleIds:[config().guildId]}),/rolü/);botPermissions=String(16n|268435456n|1024n|2048n|16384n|65536n);roleMentionable=false;await assert.rejects(configureTickets(owner,initial),/etiketlenebilir/);roleMentionable=true;botPermissions='1024';await assert.rejects(configureTickets(owner,initial),/izin/);});
test('Kapalı bilet sistemi ve sunucu doğrulaması tamamlanmamış üyeler kanal açamaz',async()=>{await configureTickets(owner,{...initial,enabled:false});await assert.rejects(openTicket(member,'support','disabled'),/kapalı/);await configureTickets(owner,initial);pending=true;await assert.rejects(openTicket(member,'support','pending'),/üyelik/);assert.equal(channels.length,2);});
test('Çekiliş seçilen kanalda başlar; tekrar teslim ikinci mesaj/kayıt oluşturmaz',async()=>{const input={title:'Kitap',channelId:panelId,minutes:5,winnerCount:3,requestId:randomUUID()};const r=await createGiveaway(owner,input);assert.equal(r.payload.winnerCount,3);assert.equal(messages.get(panelId)![0].components[0].components[0].custom_id,'feature:'+r.id+':join');assert.equal((await createGiveaway(owner,input)).id,r.id);assert.equal(messages.get(panelId)?.length,1);});
test('Çoklu kazanan benzersizdir; katılım bir kere sayılır ve sonuçlandırma tekrar kazanan seçmez',async()=>{const r=await createGiveaway(owner,{title:'Kitap',channelId:panelId,minutes:5,winnerCount:10,requestId:randomUUID()});await participateFeature(member,r.id,'join');await participateFeature(member,r.id,'join-again');await participateFeature(stranger,r.id,'join');await assert.rejects(manageGiveaway(stranger,r.id,'end',false,'deny'),/yetkili/);const done=await manageGiveaway(owner,r.id,'end',true,'end');assert.equal(done.payload.entries,2);assert.equal(done.payload.winners.length,2);assert.equal(new Set(done.payload.winners).size,2);assert.deepEqual((await finishGiveaway(owner,r.id,true,'end-again')).payload.winners,done.payload.winners);await assert.rejects(participateFeature(member,r.id,'late'),/açık değil/);assert.equal(messages.get(panelId)![0].components.length,0);});
test('Yeniden seçim önceki kazananı dışlar, aynı işlem iki kez çekilmez ve başka kayıt iptal edilemez',async()=>{const r=await createGiveaway(owner,{title:'Kitap',channelId:panelId,minutes:5,winnerCount:1,requestId:randomUUID()});await participateFeature(member,r.id,'join');await participateFeature(stranger,r.id,'join');const first=await manageGiveaway(owner,r.id,'end',true,'end'),next=await manageGiveaway(owner,r.id,'reroll',true,'reroll');assert.notEqual(next.payload.winner,first.payload.winner);assert.equal(next.payload.drawNumber,2);assert.deepEqual((await manageGiveaway(owner,r.id,'reroll',true,'reroll')).payload,next.payload);const note=await addFeatureRecord(owner,'NOTE','Özel not',{}, {},'note');await assert.rejects(manageGiveaway(owner,note.id,'cancel',true,'bad'),/çekiliş/);assert.equal((await getFeatureRecord(note.id)).status,'OPEN');});
test('Çekiliş iptali katılımı durdurur; başka sunucu/kategori hedefleri reddedilir',async()=>{await assert.rejects(createGiveaway(owner,{title:'Kitap',channelId:categoryId,minutes:5,winnerCount:1,requestId:randomUUID()}),/metin kanalı/);const r=await createGiveaway(owner,{title:'Kitap',channelId:panelId,minutes:5,winnerCount:1,requestId:randomUUID()});await manageGiveaway(owner,r.id,'cancel',true,'cancel');await assert.rejects(participateFeature(member,r.id,'join'),/açık değil/);assert.equal((await getFeatureRecord(r.id)).status,'CANCELLED');});
test('Kazanan örneklemesi sınırları, tekrar eden üyeler ve boş havuz için güvenlidir',()=>{assert.deepEqual(drawGiveawayWinners([],10),[]);assert.deepEqual(drawGiveawayWinners([member.id,member.id],10),[member.id]);for(let n=0;n<20;n++){const selected=drawGiveawayWinners([member.id,stranger.id,staffId],2);assert.equal(selected.length,2);assert.equal(new Set(selected).size,2);}assert.throws(()=>drawGiveawayWinners([member.id],11));});
test('Bilet kur komutu yetkiyi çalışma anında kontrol eder; toplam kök komut Discord sınırında kalır',async()=>{const responses:any[]=[];const i:any={isChatInputCommand:()=>true,isButton:()=>false,isModalSubmit:()=>false,commandName:'bilet',user:member,channelId:panelId,id:'command',memberPermissions:{has:()=>false},options:{getSubcommand:()=> 'kur'},deferReply:async()=>{i.deferred=true;},editReply:async(v:any)=>responses.push(v)};await handleSupportInteraction(i,defaultCommunitySettings());assert.match(responses[0].embeds[0].description,/Sunucuyu Yönet/);assert.equal((await ticketSettings()),null);assert.equal(commands.length,100);assert.ok(commands.length<=100);for(const c of commands)for(const sub of (c as any).options||[]){let optional=false;for(const option of sub.options||[]){if(option.required)assert.equal(optional,false);else optional=true;}}});
test('Slash çekilişi yeniden teslim edilince aynı kaydı döndürür; katılım ve sonuç düğmeleri çalışır',async()=>{const views:any[]=[];const i:any={id:'123456789012345678',isChatInputCommand:()=>true,isButton:()=>false,isModalSubmit:()=>false,commandName:'cekilis',user:owner,channelId:panelId,memberPermissions:{has:()=>true},options:{getString:()=> 'Kitap',getInteger:(key:string)=>key==='dakika'?5:2,getChannel:()=>null},deferReply:async()=>{i.deferred=true;},editReply:async(v:any)=>views.push(v)};await handleSupportInteraction(i,defaultCommunitySettings());await handleSupportInteraction(i,defaultCommunitySettings());assert.equal(messages.get(panelId)?.length,1);assert.equal((await pg.query("SELECT id FROM feature_records WHERE kind='GIVEAWAY'")).rows.length,1);assert.match(giveawayRequestId(i.id),/^[0-9a-f-]{36}$/);assert.ok(views.every(v=>v.embeds[0].title.includes('TurkishPix')));});
test('Web kurulum ve çekiliş yazmaları owner ve CSRF ister; adlarla kanal/rol seçimi API’den yüklenir',async()=>{const ownerToken='ab'.repeat(32),memberToken='cd'.repeat(32);for(const actor of [owner,member])await pg.query('INSERT INTO users(id,username) VALUES($1,$2) ON CONFLICT DO NOTHING',[actor.id,actor.username]);for(const [token,id] of [[ownerToken,owner.id],[memberToken,member.id]])await pg.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,$3,now()+interval '1 hour') ON CONFLICT DO NOTHING",[sha256(token),id,'csrf']);const headers={cookie:'tp_session='+ownerToken,origin:'https://turkishpix.example','x-csrf-token':'csrf','content-type':'application/json'};for(const endpoint of ['tickets','giveaway','support-action']){const request=new Request('https://turkishpix.example/api/community/'+endpoint,{method:'POST',headers:{...headers,cookie:'tp_session='+memberToken},body:'{}'});assert.equal((await POST(request)).status,403);}const csrf=await POST(new Request('https://turkishpix.example/api/community/tickets',{method:'POST',headers:{...headers,'x-csrf-token':'wrong'},body:JSON.stringify(initial)}));assert.equal(csrf.status,403);const saved=await POST(new Request('https://turkishpix.example/api/community/tickets',{method:'POST',headers,body:JSON.stringify(initial)}));assert.equal(saved.status,200);const state=await GET(new Request('https://turkishpix.example/api/support',{headers}));const body=await state.json();assert.equal(state.status,200);assert.ok(body.channels.some((c:any)=>c.type===4&&c.name==='Destek biletleri'));assert.equal(body.roles[0].name,'Yetkililer');const raffle=await POST(new Request('https://turkishpix.example/api/community/giveaway',{method:'POST',headers,body:JSON.stringify({title:'Kitap',channelId:panelId,minutes:5,winnerCount:2,requestId:randomUUID()})}));assert.equal(raffle.status,200);const id=(await raffle.json()).id;await participateFeature(member,id,'member-join');const end=await POST(new Request('https://turkishpix.example/api/community/support-action',{method:'POST',headers,body:JSON.stringify({id,action:'end',requestId:randomUUID()})}));assert.equal(end.status,200);assert.equal((await getFeatureRecord(id)).payload.winner,member.id);});
