'use client';
export default function ApplicationProtectionPanel({value,setValue,live}:{value:any;setValue:(v:any)=>void;live:any}){
 const edit=(key:string,v:any)=>setValue({...value,[key]:v});
 const toggle=(key:string,label:string,help:string)=><div className="setting-row"><div><strong>{label}</strong><span>{help}</span></div><button type="button" role="switch" aria-label={label} aria-checked={value[key]} className={'toggle '+(value[key]?'on':'')} onClick={()=>edit(key,!value[key])}><span/></button></div>;
 return <section className="surface community-card"><span className="eyebrow">DIŞ UYGULAMA & YÖNLENDİRME KORUMASI</span><h2>Hesaba kurulan botlar da denetlenir.</h2><p className="role-help">Sunucuya eklenmemiş uygulamaların /spam gibi komutlarla gönderdiği yanıtlar yakalanır. Logda uygulamanın adı ve mesajı tetikleyen gerçek üye görünür. Uygulamayı kuran kişiyle mesajı tetikleyen kişi karıştırılmaz.</p>
 {toggle('enabled','Uygulama korumasını aç','Ana güvenlik sistemi açıkken çalışır.')}{toggle('blockUserInstalled','Hesaba kurulan uygulama mesajlarını sil','Sunucuya kurulmuş botların normal yanıtları korunur; TurkishPix kendi mesajlarını silmez.')}{toggle('nativeBlock','Discord’da herkese açık dış uygulama yanıtını kapat','Metin ve forum kanallarında Dış Uygulamaları Kullan izni kapatılır. Yöneticiler Discord izinlerini aşabilir; silme koruması onları da denetler. Kapattığında önceki izinler geri yüklenir.')}{toggle('blockForwards','Yönlendirilmiş mesajları engelle','Mesaj yönlendirmesiyle koruma aşılmasın; normal cevaplar etkilenmez.')}
 <div className="form-grid">{[['timeoutAfter','Susturma öncesi ihlal sayısı',2,30],['windowSeconds','İhlal aralığı (saniye)',5,300],['timeoutMinutes','Susturma süresi (dakika)',0,60]].map(([key,label,min,max])=><label className="form-field" key={key}>{label}<input type="number" min={Number(min)} max={Number(max)} value={value[key]} onChange={e=>edit(String(key),Number(e.target.value))}/></label>)}</div><small>0 dakika: mesaj silinir, susturma uygulanmaz. Aynı mesajın tekrar gelen olayı ikinci ihlal sayılmaz.</small>
 <label className="form-field">İzinli uygulama ID’leri<input defaultValue={value.allowedApplicationIds.join(', ')} onBlur={e=>edit('allowedApplicationIds',e.target.value.split(/[,\s]+/).filter(Boolean))}/><small>Virgülle ayır. Belirli uygulamalara izin vermek için Discord izin kilidini kapat; mesaj filtresi bu listeyi kullanır.</small></label>
 <p className="role-help">Discord izin koruması: {({ACTIVE:'Etkin',APPLYING:'Kanallara uygulanıyor',PARTIAL:'Bazı kanallarda izin eksik',PERMISSION_MISSING:'Kanalları Yönet izni gerekli',RESTORING:'Önceki izinler geri yükleniyor',OFF:'Kapalı'} as any)[live?.state]||'Botun uygulaması bekleniyor'} · {live?.protected||0} kanal korunuyor.</p>
 </section>;
}
