'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {arcadeGames,isArcadeBoard,type ArcadeGame} from '../../../../packages/core/src/arcade-policy';
import {FlyingRound,MemoryRound,type GameResult} from './ArcadeGames';
import {BoardRound} from './ArcadeBoards';
import {ActionRound} from './ArcadeAction';
import {roomGuideSteps} from '../../../../packages/core/src/room-guide';
type Round={id:string;game:ArcadeGame;cost:number;seed:number;expires_at:string;practice?:boolean};
const money=(coins:number)=>new Intl.NumberFormat('tr-TR').format(coins)+' Bot TL';
function GameArt({game}:{game:ArcadeGame}){
 if(game==='memory')return <div className="memory-preview">{['✦','☾','❖','✦','◇','☾'].map((icon,i)=><span key={i}>{icon}</span>)}</div>;
 if(game==='orbit')return <><i className="orbit-ring"/><i className="orbit-ring second"/><i className="orbit-cube one"/><i className="orbit-cube two"/><i className="orbit-star">✦</i></>;
 if(game==='neon')return <><i className="neon-grid"/><i className="neon-ship">▲</i><i className="neon-obstacle one"/><i className="neon-obstacle two"/><i className="neon-star">✦</i></>;
 return <svg className="arcade-preview-svg" viewBox="0 0 360 220" aria-hidden="true">
  {game==='snake'?<><path d="M74 155 H146 V95 H225 V137 H272" fill="none" stroke="#48a489" strokeWidth="27" strokeLinecap="round" strokeLinejoin="round"/><rect x="255" y="121" width="33" height="33" rx="10" fill="#bbffd0"/><circle cx="279" cy="130" r="3" fill="#133b35"/><circle cx="279" cy="144" r="3" fill="#133b35"/><circle cx="108" cy="79" r="11" fill="#ffd074"/><circle cx="108" cy="79" r="23" fill="#ffd07415"/></>:game==='breaker'?<>{Array.from({length:24},(_,i)=><rect key={i} x={42+(i%8)*35} y={56+Math.floor(i/8)*24} width="30" height="17" rx="4" fill={['#ff89b6','#ffcd70','#89cfee'][Math.floor(i/8)]} opacity={i===10||i===13?.2:.9}/>)}<rect x="137" y="183" width="88" height="9" rx="4" fill="#9adfff"/><circle cx="211" cy="142" r="8" fill="#fff2bd"/><path d="M183 174 L208 149" stroke="#fff2bd45" strokeWidth="3"/></>:game==='space'?<><path d="M180 133 L205 182 L180 171 L155 182Z" fill="#b2f2ff"/><path d="M173 181 L180 201 L187 181" fill="#ffa66b"/>{[110,180,250].map((x,i)=><g key={x}><path d={'M'+x+' '+(68+i%2*20)+' l18 -12 l-18 -13 l-18 13Z'} fill="#b593ee"/><rect x={x-2} y={108+i%2*13} width="4" height="16" rx="2" fill="#86e8ff"/></g>)}<circle cx="62" cy="127" r="13" fill="none" stroke="#7fe1aa"/><text x="62" y="132" textAnchor="middle" fill="#7fe1aa" fontSize="18">◇</text></>:game==='2048'?<>{[2,4,8,16,32,64,128,256,2048].map((v,i)=><g key={v}><rect x={96+i%3*58} y={31+Math.floor(i/3)*58} width="50" height="50" rx="10" fill={i===8?'#ffd074':i>4?'#bd855a':'#39344d'}/><text x={121+i%3*58} y={64+Math.floor(i/3)*58} textAnchor="middle" fill={i===8?'#39241d':'#f6e8c6'} fontSize={v===2048?16:22} fontWeight="700">{v}</text></g>)}</>:game==='mines'?<>{Array.from({length:16},(_,i)=><g key={i}><rect x={95+i%4*43} y={36+Math.floor(i/4)*43} width="36" height="36" rx="7" fill={i===5||i===6||i===9?'#312b53':'#555070'}/><text x={113+i%4*43} y={61+Math.floor(i/4)*43} textAnchor="middle" fill={i===10?'#ffd074':'#c5b5fc'} fontSize="22">{i===10?'⚑':i===5?'1':i===6?'2':i===9?'1':'◇'}</text></g>)}</>:<>{Array.from({length:28},(_,i)=><circle key={i} cx={64+i%7*39} cy={49+Math.floor(i/7)*40} r="15" fill={i>20&&i<25?'#ffd074':i===14||i===15||i===19||i===25?'#aa87e7':'#27324f'}/>)}</>}
 </svg>;
}
export default function ArcadePanel(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[choice,setChoice]=useState<ArcadeGame|null>(null),[round,setRound]=useState<Round|null>(null),[result,setResult]=useState<GameResult|null>(null),[webGL,setWebGL]=useState(true),[saving,setSaving]=useState(false),[filter,setFilter]=useState('all');
 const requestId=useRef<string|null>(null),finishing=useRef(false);
 async function refresh(){try{const response=await fetch('/api/arcade',{cache:'no-store'}),body=await response.json();if(!response.ok)throw Error(body.error||'Oyun salonu yüklenemedi.');setData(body);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı.');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const selected=new URLSearchParams(window.location.search).get('oyun');if(arcadeGames.some(g=>g.id===selected))setChoice(selected as ArcadeGame);try{const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl');setWebGL(!!gl);gl?.getExtension('WEBGL_lose_context')?.loseContext();}catch{setWebGL(false);}},[]);
 useEffect(()=>{if(!choice)return;const previous=document.activeElement as HTMLElement|null,dialog=document.querySelector<HTMLElement>('.arcade-start-modal');const elements=()=>dialog?Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')):[];elements()[0]?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy){event.preventDefault();setChoice(null);}if(event.key==='Tab'){const list=elements(),first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);previous?.focus();};},[choice,busy]);
 const end=useCallback(async(outcome:GameResult)=>{
  if(!round||finishing.current)return;finishing.current=true;setResult(outcome);setError('');
  if(round.practice){finishing.current=false;return;}setSaving(true);
  try{const response=await fetch('/api/arcade/finish',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':data?.csrf||''},body:JSON.stringify({id:round.id,...outcome})}),body=await response.json();if(!response.ok)throw Error(body.error||'Tur kaydedilemedi.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Tur kaydedilemedi. Yeniden dene.');}finally{setSaving(false);finishing.current=false;}
 },[round,data?.csrf]);
 function practice(game:ArcadeGame){setChoice(null);setRound({id:crypto.randomUUID(),game,cost:0,seed:crypto.getRandomValues(new Uint32Array(1))[0],expires_at:'',practice:true});setResult(null);setError('');}
 async function start(game:ArcadeGame){
  if(busy)return;setBusy(true);setError('');requestId.current||=crypto.randomUUID();
  try{const response=await fetch('/api/arcade/start',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':data?.csrf||''},body:JSON.stringify({game,requestId:requestId.current})}),body=await response.json();if(!response.ok)throw Error(body.error||'Tur başlatılamadı.');requestId.current=null;setData((old:any)=>({...old,me:{...old.me,coins:body.coins},active:body}));setChoice(null);setRound(body);setResult(null);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı.');}finally{setBusy(false);}
 }
 const chosen=arcadeGames.find(g=>g.id===choice),activeGame=arcadeGames.find(g=>g.id===round?.game),games=arcadeGames.filter(g=>filter==='all'||filter==='3d'&&g.dimension==='3D'||filter==='logic'&&(isArcadeBoard(g.id)||g.id==='memory')||filter==='action'&&!isArcadeBoard(g.id)&&g.id!=='memory');
 return <main className="bot-main arcade-main"><div className="arcade-heading"><div><span className="eyebrow">TURKISHPiX / ARCADE · 9 OYUN</span><h1>Bir tur daha.</h1><p>Refleks, strateji ve uzay macerası. Telefonda, bilgisayarda, Discord’da. Favorini bul; ilk turu ücretsiz dene.</p></div><div className="arcade-wallet"><span>SANAL BOT BAKİYESİ</span><strong>{data?.me?money(data.me.coins):'Discord ile giriş yap'}</strong><small>{data?.me?'@'+data.me.username+' · /cuzdan ile aynı bakiye':'Ücretsiz denemek için giriş gerekmez.'}</small></div></div>
 {error&&<div className="notice danger" role="alert">{error}</div>}
 {round?<section className="surface arcade-player"><div className="section-top"><div><span className="eyebrow">{activeGame?.dimension} · {round.practice?'ÜCRETSİZ DENEME':money(round.cost)+' / TUR'}</span><h2>{activeGame?.name}</h2></div>{!result&&<button className="button ghost small" onClick={()=>void end({outcome:'QUIT',score:0})}>Turu bitir</button>}</div>{result?<div className="arcade-result"><span>{result.outcome==='WIN'?'✦':'◇'}</span><h2>{result.outcome==='WIN'?'Güzel tur!':result.outcome==='LOSE'?'Bir kez daha?':'Tur tamamlandı.'}</h2><strong>{result.score.toLocaleString('tr-TR')} skor</strong><p>{round.practice?'Deneme turu ücretsizdir; skor geçmişe kaydedilmez.':saving?'Turun kaydediliyor…':'Bu tur cüzdanından '+money(round.cost)+' harcadı.'}</p>{error&&<button className="button ghost" disabled={saving} onClick={()=>void end(result)}>Kaydı yeniden dene</button>}{round.practice&&<button className="button primary" onClick={()=>practice(round.game)}>Yeniden ücretsiz dene</button>}<button className="button ghost" disabled={saving||!!error} onClick={()=>{setRound(null);setResult(null);}}>Oyun salonuna dön</button></div>:round.game==='memory'?<MemoryRound key={round.id} seed={round.seed} onEnd={end}/>:isArcadeBoard(round.game)?<BoardRound key={round.id} game={round.game} seed={round.seed} onEnd={end}/>:round.game==='neon'||round.game==='orbit'?<FlyingRound key={round.id} game={round.game} seed={round.seed} onEnd={end}/>:<ActionRound key={round.id} game={round.game} seed={round.seed} onEnd={end}/>}</section>:<>
 {data?.active&&<div className="arcade-resume"><div><strong>Ödenmiş bir turun var.</strong><span>{arcadeGames.find(g=>g.id===data.active.game)?.name} · devam etmek yeniden ücret almaz.</span></div><button className="button ghost" onClick={()=>{setRound(data.active);setResult(null);}}>Tura devam et</button></div>}
 <div className="arcade-filters" aria-label="Oyun türleri">{[['all','Tüm oyunlar · 9'],['action','Refleks & aksiyon'],['logic','Zekâ & strateji'],['3d','3D deneyim']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 <div className="arcade-catalog">{games.map(game=><article className={'arcade-game-card arcade-'+game.id} key={game.id} style={{'--arcade-color':game.color} as React.CSSProperties}><div className="arcade-game-art" aria-hidden="true"><GameArt game={game.id}/><span className="arcade-dimension">{game.dimension}</span>{isArcadeBoard(game.id)&&<span className="arcade-discord-chip">DISCORD’DA DA OYNA</span>}</div><div className="arcade-game-info"><div className="section-top"><h2>{game.name}</h2><span className="arcade-price">{money(game.cost)}</span></div><p>{game.description}</p><small>{game.controls}</small><button className="button primary full" disabled={busy||game.id==='orbit'&&!webGL} onClick={()=>practice(game.id)}>{game.id==='orbit'&&!webGL?'Bu cihazda WebGL yok':'Ücretsiz dene →'}</button><button className="button ghost full" disabled={loading||busy||game.id==='orbit'&&!webGL} onClick={()=>{if(data?.active){setRound(data.active);setResult(null);return;}requestId.current=null;setChoice(game.id);}}>{data?.active?'Ödenmiş tura devam':money(game.cost)+' ile oyna'}</button></div></article>)}</div>
 <section className="surface arcade-discord-guide"><span className="eyebrow">OYUNU SOHBETE TAŞI</span><h2>Discord’da da bir tur.</h2><p>2048, Mayın Tarlası ve Dörtlü Bağla’yı mesajdaki düğmelerle oyna. Ücreti “Başlat” düğmesinde onayla; aynı cüzdan kullanılır.</p><div className="arcade-command-list"><code>/topluluk oyun 2048</code><code>/topluluk oyun mayin</code><code>/topluluk oyun dortlu</code></div><p className="role-help"><code>/topluluk oyun salon oyun: Neon Yılan</code> bütün 2D / 3D oyunları tarayıcıda açar. Gerçek zamanlı oyunlar tarayıcıda; üç strateji oyunu Discord’da da oynanır.</p></section>
 <section className="surface arcade-room-guide"><span className="eyebrow">ÖZEL SES ODALARI</span><h2>Arkadaşlarını kendi odanda topla.</h2><p>Kanala basılı tutmana gerek yok. <strong>➕・Oda Oluştur</strong> ses kanalına katıl; bot kendi odanı açıp seni taşır.</p><div>{roomGuideSteps.map((step,i)=><article key={step.command}><span>{String(i+1).padStart(2,'0')}</span><h3>{step.title}</h3><p>{step.description}</p><code>{step.command}</code></article>)}</div><p className="role-help">Oda boş kalınca ayarlanan sürede silinir; varsayılan 120 saniye. <code>/topluluk oda yardim</code> tüm kontrolleri gösterir.</p></section>
 <section className="arcade-gift"><span>✦</span><div><strong>Topluluk hediyesi · 50.000 Bot TL</strong><p>9 Ekim kampanyasındaki üyelere bağlantı sağlandığında tek seferlik cüzdan hediyesi. /cuzdan ile ödeme durumunu görebilirsin.</p></div><a href="https://discord.gg/turkishpix" target="_blank" rel="noreferrer">Topluluğa katıl ↗</a></section>
 {data?.history?.length>0&&<section className="surface community-card"><span className="eyebrow">SON WEB TURLARIN</span><h2>Her turun bir hikâyesi.</h2><div className="arcade-history">{data.history.map((item:any,i:number)=><div key={i}><strong>{arcadeGames.find(g=>g.id===item.game)?.name}</strong><span>{item.score||0} skor</span><span>−{money(item.cost)}</span></div>)}</div><p className="role-help">Skorlar kişisel oyun kayıtlarıdır. Oyun salonu tur ücreti alır; skor bot bakiyesi kazandırmaz.</p></section>}
 </>}
 {chosen&&<div className="arcade-modal-backdrop" onClick={()=>!busy&&setChoice(null)}><section className="arcade-start-modal surface" role="dialog" aria-modal="true" aria-labelledby="arcade-start-title" onClick={e=>e.stopPropagation()}><button className="arcade-modal-close" aria-label="Kapat" disabled={busy} onClick={()=>setChoice(null)}>×</button><span className="eyebrow">{chosen.dimension} / YENİ TUR</span><h2 id="arcade-start-title">{chosen.name}</h2><p>{chosen.description}</p><button className="button ghost full" disabled={busy||chosen.id==='orbit'&&!webGL} onClick={()=>practice(chosen.id)}>Önce ücretsiz dene</button><div className="arcade-cost-row"><span>Kayıtlı tur ücreti</span><strong>{money(chosen.cost)}</strong></div><p className="role-help">Başlatınca ücret cüzdanından bir kez düşer. Turu bitirmen veya sayfayı kapatman ücreti geri vermez.</p>{data?.me?<><div className="arcade-cost-row"><span>Cüzdanın</span><strong>{money(data.me.coins)}</strong></div><button className="button primary full" disabled={busy||loading||data.me.coins<chosen.cost||chosen.id==='orbit'&&!webGL} onClick={()=>void start(chosen.id)}>{busy?'Tur hazırlanıyor…':data?.active?'Ödenmiş tura devam et':money(chosen.cost)+' ile başlat'}</button></>:<a className="button primary full" href={'/api/auth/login?return='+encodeURIComponent('/oyunlar?oyun='+chosen.id)}>Discord ile giriş yap →</a>}{error&&<p className="negative" role="alert">{error}</p>}</section></div>}
 </main>;
}
