'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {arcadeGames,type ArcadeGame} from '../../../../packages/core/src/arcade-policy';
import {FlyingRound,MemoryRound,type GameResult} from './ArcadeGames';
type Round={id:string;game:ArcadeGame;cost:number;seed:number;expires_at:string};
const money=(coins:number)=>new Intl.NumberFormat('tr-TR').format(coins)+' Bot TL';
export default function ArcadePanel(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[choice,setChoice]=useState<ArcadeGame|null>(null),[round,setRound]=useState<Round|null>(null),[result,setResult]=useState<GameResult|null>(null),[webGL,setWebGL]=useState(true),[saving,setSaving]=useState(false);
 const requestId=useRef<string|null>(null),finishing=useRef(false);
 async function refresh(){try{const response=await fetch('/api/arcade',{cache:'no-store'}),body=await response.json();if(!response.ok)throw Error(body.error||'Oyun salonu yüklenemedi.');setData(body);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı.');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();try{const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl');setWebGL(!!gl);gl?.getExtension('WEBGL_lose_context')?.loseContext();}catch{setWebGL(false);}},[]);
 useEffect(()=>{if(!choice)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.arcade-start-modal');const elements=()=>dialog?Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')):[];elements()[0]?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy){event.preventDefault();setChoice(null);}if(event.key==='Tab'){const list=elements();const first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',keyboard);return ()=>{document.removeEventListener('keydown',keyboard);previous?.focus();};},[choice,busy]);
 const end=useCallback(async(outcome:GameResult)=>{
  if(!round||finishing.current)return;finishing.current=true;setResult(outcome);setSaving(true);setError('');
  try{const response=await fetch('/api/arcade/finish',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':data?.csrf||''},body:JSON.stringify({id:round.id,...outcome})}),body=await response.json();if(!response.ok)throw Error(body.error||'Tur kaydedilemedi.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Tur kaydedilemedi. Yeniden dene.');}finally{setSaving(false);finishing.current=false;}
 },[round,data?.csrf]);
 async function start(game:ArcadeGame){
  if(busy)return;setBusy(true);setError('');requestId.current||=crypto.randomUUID();
  try{const response=await fetch('/api/arcade/start',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':data?.csrf||''},body:JSON.stringify({game,requestId:requestId.current})}),body=await response.json();if(!response.ok)throw Error(body.error||'Tur başlatılamadı.');requestId.current=null;setData((old:any)=>({...old,me:{...old.me,coins:body.coins},active:body}));setChoice(null);setRound(body);setResult(null);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı.');}finally{setBusy(false);}
 }
 const chosen=arcadeGames.find(game=>game.id===choice),activeGame=arcadeGames.find(game=>game.id===round?.game);
 return <main className="bot-main arcade-main"><div className="arcade-heading"><div><span className="eyebrow">TURKISHPiX / ARCADE</span><h1>Bir tur daha.</h1><p>İki boyutta refleks, üç boyutta yolculuk. Cüzdanın hazırsa oyun başlasın.</p></div><div className="arcade-wallet"><span>SANAL BOT BAKİYESİ</span><strong>{data?.me?money(data.me.coins):'Discord ile giriş yap'}</strong>{data?.me&&<small>@{data.me.username} · /cuzdan ile aynı bakiye</small>}</div></div>
 {error&&<div className="notice danger" role="alert">{error}</div>}
 {round?<section className="surface arcade-player"><div className="section-top"><div><span className="eyebrow">{activeGame?.dimension} · {money(round.cost)} / TUR</span><h2>{activeGame?.name}</h2></div>{!result&&<button className="button ghost small" onClick={()=>void end({outcome:'QUIT',score:0})}>Turu bitir</button>}</div>{result?<div className="arcade-result"><span>{result.outcome==='WIN'?'✦':'◇'}</span><h2>{result.outcome==='WIN'?'Güzel tur!':result.outcome==='LOSE'?'Yeni bir rota dene.':'Tur tamamlandı.'}</h2><strong>{result.score.toLocaleString('tr-TR')} skor</strong><p>{saving?'Turun kaydediliyor…':'Bu tur cüzdanından '+money(round.cost)+' harcadı.'}</p>{error&&<button className="button ghost" disabled={saving} onClick={()=>void end(result)}>Kaydı yeniden dene</button>}<button className="button primary" disabled={saving||!!error} onClick={()=>{setRound(null);setResult(null);}}>Oyun salonuna dön</button></div>:round.game==='memory'?<MemoryRound seed={round.seed} onEnd={end}/>:<FlyingRound game={round.game} seed={round.seed} onEnd={end}/>}</section>:<>
 {data?.active&&<div className="arcade-resume"><div><strong>Ödenmiş bir turun var.</strong><span>{arcadeGames.find(game=>game.id===data.active.game)?.name} · devam etmek yeniden ücret almaz.</span></div><button className="button ghost" onClick={()=>{setRound(data.active);setResult(null);}}>Tura devam et</button></div>}
 <div className="arcade-catalog">{arcadeGames.map(game=><article className={'arcade-game-card arcade-'+game.id} key={game.id} style={{'--arcade-color':game.color} as React.CSSProperties}><div className="arcade-game-art" aria-hidden="true">{game.id==='memory'?<div className="memory-preview">{['✦','☾','❖','✦','◇','☾'].map((icon,i)=><span key={i}>{icon}</span>)}</div>:game.id==='orbit'?<><i className="orbit-ring"/><i className="orbit-ring second"/><i className="orbit-cube one"/><i className="orbit-cube two"/><i className="orbit-star">✦</i></>:<><i className="neon-grid"/><i className="neon-ship">▲</i><i className="neon-obstacle one"/><i className="neon-obstacle two"/><i className="neon-star">✦</i></>}<span className="arcade-dimension">{game.dimension}</span></div><div className="arcade-game-info"><div className="section-top"><h2>{game.name}</h2><span className="arcade-price">{money(game.cost)}</span></div><p>{game.description}</p><small>{game.controls}</small><button className="button primary full" disabled={loading||busy||game.id==='orbit'&&!webGL} onClick={()=>{if(data?.active){setRound(data.active);setResult(null);return;}requestId.current=null;setChoice(game.id);}}>{game.id==='orbit'&&!webGL?'Bu cihazda WebGL yok':data?.active?'Ödenmiş tura devam':'Turu seç →'}</button></div></article>)}</div>
 <section className="arcade-gift"><span>✦</span><div><strong>Topluluk hediyesi · 50.000 Bot TL</strong><p>9 Ekim dağıtımındaki mevcut üyelere tek seferlik cüzdan hediyesi. Tur ücretleri bu bakiyeden düşer.</p></div><a href="https://discord.gg/turkishpix" target="_blank" rel="noreferrer">Topluluğa katıl ↗</a></section>
 {data?.history?.length>0&&<section className="surface community-card"><span className="eyebrow">SON TURLARIN</span><h2>Her turun bir hikâyesi.</h2><div className="arcade-history">{data.history.map((item:any,i:number)=><div key={i}><strong>{arcadeGames.find(game=>game.id===item.game)?.name}</strong><span>{item.score||0} skor</span><span>−{money(item.cost)}</span></div>)}</div><p className="role-help">Skorlar kişisel oyun kayıtlarıdır. Oyun salonu tur ücreti alır; skor bot bakiyesi kazandırmaz.</p></section>}
 </>}
 {chosen&&<div className="arcade-modal-backdrop" onClick={()=>!busy&&setChoice(null)}><section className="arcade-start-modal surface" role="dialog" aria-modal="true" aria-labelledby="arcade-start-title" onClick={e=>e.stopPropagation()}><button className="arcade-modal-close" aria-label="Kapat" disabled={busy} onClick={()=>setChoice(null)}>×</button><span className="eyebrow">{chosen.dimension} / YENİ TUR</span><h2 id="arcade-start-title">{chosen.name}</h2><p>{chosen.description}</p><div className="arcade-cost-row"><span>Tur ücreti</span><strong>{money(chosen.cost)}</strong></div><p className="role-help">Başlatınca ücret cüzdanından bir kez düşer. Turu bitirmen veya sayfayı kapatman ücreti geri vermez.</p>{data?.me?<><div className="arcade-cost-row"><span>Cüzdanın</span><strong>{money(data.me.coins)}</strong></div><button className="button primary full" disabled={busy||data.me.coins<chosen.cost} onClick={()=>void start(chosen.id)}>{busy?'Tur hazırlanıyor…':data?.active?'Ödenmiş tura devam et':money(chosen.cost)+' ile başlat'}</button></>:<a className="button primary full" href="/api/auth/login?return=%2Foyunlar">Discord ile giriş yap →</a>}{error&&<p className="negative" role="alert">{error}</p>}</section></div>}
 </main>;
}
