'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {advanceArcadeBoard,createArcadeBoard,mineCount,type ArcadeBoard} from '../../../../packages/core/src/arcade-boards';
import type {ArcadeBoardGame} from '../../../../packages/core/src/arcade-policy';
import type {GameResult} from './ArcadeGames';
const arrows:Record<string,string>={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'};
export function BoardRound({game,seed,onEnd}:{game:ArcadeBoardGame;seed:number;onEnd:(result:GameResult)=>void}){
 const random=useRef(seed),rng=useCallback((max:number)=>{random.current=(random.current*1664525+1013904223)>>>0;return Math.floor(random.current/4294967296*max);},[]);
 const [board,setBoard]=useState<ArcadeBoard>(()=>createArcadeBoard(game,rng)),state=useRef(board),[note,setNote]=useState(''),surface=useRef<HTMLDivElement>(null),touch=useRef({x:0,y:0});
 const act=useCallback((action:string)=>{try{const next=advanceArcadeBoard(state.current,action,rng);state.current=next;setBoard(next);setNote('');if(next.done)onEnd({outcome:next.result==='LOSE'?'LOSE':'WIN',score:Math.min(100000,next.score)});}catch(e){setNote(e instanceof Error?e.message:'Başka bir hamle dene.');}},[rng,onEnd]);
 useEffect(()=>{surface.current?.focus();},[]);
 return <div className="board-round" ref={surface} tabIndex={0} aria-label={game==='2048'?'2048 oyun alanı':game==='mines'?'Mayın tarlası oyun alanı':'Dörtlü Bağla oyun alanı'} onKeyDown={e=>{if(game==='2048'&&arrows[e.key]){e.preventDefault();act(arrows[e.key]);}}}>
  <div className="arcade-hud"><span><b>{board.score}</b> skor</span><span><b>{board.moves}</b> hamle</span><span>{game==='2048'?'Hedef 2048':game==='mines'?'4 mayın':'Sen altın · bot mor'}</span></div>
  {board.kind==='2048'?<><div className="tile-board" onPointerDown={e=>{touch.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const dx=e.clientX-touch.current.x,dy=e.clientY-touch.current.y;if(Math.max(Math.abs(dx),Math.abs(dy))>25)act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');}}>{board.board.map((v,i)=><div className={'tile-cell tile-'+v} key={i} aria-label={'Kare '+(i+1)+': '+(v||'boş')}>{v||''}</div>)}</div><div className="arcade-pad">{[['left','←'],['up','↑'],['down','↓'],['right','→']].map(([action,label])=><button key={action} onClick={()=>act(action)} aria-label={{left:'Sola',up:'Yukarı',down:'Aşağı',right:'Sağa'}[action]}>{label}</button>)}</div><p className="arcade-control-note">Ok tuşları, yön düğmeleri veya taşların üzerinde kaydır. Aynı taşlar tek hamlede bir kez birleşir.</p></>:board.kind==='mines'?<><div className="mine-board">{Array.from({length:16},(_,i)=>{const open=board.opened.includes(i),flag=board.flags.includes(i),n=mineCount(board,i);return <button key={i} className={'mine-cell '+(open?'open mine-'+n:flag?'flagged':'')} disabled={open} aria-label={'Kare '+(i+1)+(open?', '+n+' komşu mayın':flag?', bayraklı':', kapalı')} onClick={()=>act(String(i))} onContextMenu={e=>{e.preventDefault();if(open)return;const mode=state.current.kind==='mines'&&state.current.flagMode;if(!mode)act('flag');act(String(i));if(!mode)act('flag');}}>{open?n||'✧':flag?'⚑':'◇'}</button>;})}</div><button className={'button '+(board.flagMode?'primary':'ghost')} onClick={()=>act('flag')} aria-pressed={board.flagMode}>{board.flagMode?'⚑ Bayrak modu · Kare açmaya geç':'◇ Kare açma modu · Bayrak koy'}</button><p className="arcade-control-note">Sayılar komşu mayınları gösterir. İlk kare ve çevresi güvenlidir. Bayrak: {board.flags.length} / 4 · Açık: {board.opened.length} / 12</p></>:<><div className="connect-controls">{Array.from({length:7},(_,i)=><button key={i} disabled={!!board.board[i]} onClick={()=>act(String(i))} aria-label={(i+1)+'. sütuna taş bırak'}>{i+1}<span>↓</span></button>)}</div><div className="connect-board">{board.board.map((v,i)=><span className={'connect-cell player-'+v} key={i} aria-label={v===1?'Senin taşın':v===2?'Botun taşı':'Boş'}/>)}</div><p className="arcade-control-note">Dört taşı yatay, dikey veya çapraz birleştir. Bot kendi hamlesini otomatik yapar.</p></>}
  <p className="arcade-control-note" role="status" aria-live="polite">{note||'Bir sonraki hamle senin.'}</p>
 </div>;
}
