'use client';
import {useState} from 'react';
export type PanelChannel={id:string;name:string;type:number;category?:string;checks:{view:boolean;send:boolean;embed?:boolean};usable?:boolean};
export default function ChannelPicker({label,channels,value,onChange,multiple=false,voice=false,category=false,requireSend=false,requireEmbed=false,emptyLabel='Kanal seçilmedi',help}:{label:string;channels:PanelChannel[];value:string|string[];onChange:(value:any)=>void;multiple?:boolean;voice?:boolean;category?:boolean;requireSend?:boolean;requireEmbed?:boolean;emptyLabel?:string;help?:string}){
 const [query,setQuery]=useState('');
 const options=channels.filter(ch=>ch.checks.view&&(category?[4]:voice?[2,13]:[0,5]).includes(ch.type));
 const filtered=options.filter(ch=>(ch.name+' '+(ch.category||'')).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
 const selected=Array.isArray(value)?value:[],missing=selected.filter(id=>!options.some(ch=>ch.id===id));
 const disabled=(ch:PanelChannel)=>(requireSend&&!ch.checks.send)||(requireEmbed&&!ch.checks.embed);
 const name=(ch:PanelChannel)=>(ch.category?ch.category+' / ':'')+(category?'📁 ':voice?'🔊 ':'#')+ch.name+(disabled(ch)?' · izin eksik':'');
 return <div className="form-field channel-picker"><span>{label}</span>{multiple?<details><summary>{selected.length?selected.length+' kanal seçildi':emptyLabel}</summary><input type="search" placeholder="Kanal ara…" aria-label={label+' ara'} value={query} onChange={e=>setQuery(e.target.value)}/><div className="channel-options">{filtered.map(ch=><label key={ch.id}><input type="checkbox" disabled={disabled(ch)} checked={selected.includes(ch.id)} onChange={e=>onChange(e.target.checked?[...selected,ch.id]:selected.filter(id=>id!==ch.id))}/><span>{name(ch)}</span></label>)}{missing.map(id=><label key={id}><input type="checkbox" checked onChange={()=>onChange(selected.filter(item=>item!==id))}/><span>Kayıtlı kanal · artık erişilemiyor</span></label>)}</div>{!filtered.length&&<small>Bu aramayla görünen kanal bulunamadı.</small>}<button type="button" className="text-link" onClick={()=>onChange([])}>Seçimi temizle</button></details>:<select aria-label={label} value={String(value)} onChange={e=>onChange(e.target.value)}><option value="">{emptyLabel}</option>{value&&!options.some(ch=>ch.id===value)&&<option value={String(value)}>Kayıtlı kanal · artık erişilemiyor</option>}{options.map(ch=><option key={ch.id} value={ch.id} disabled={disabled(ch)}>{name(ch)}</option>)}</select>}{help&&<small>{help}</small>}{!options.length&&<small>Botun gördüğü {voice?'ses':'metin'} kanalları listelenecek. Listeyi yenilemek için Yenile’ye bas.</small>}</div>;
}
