'use client';
import {useEffect,useState} from 'react';
import {radioStations} from '../../../../packages/core/src/music-policy';
import ChannelPicker from './ChannelPicker';
import DiscordIdentity from './DiscordIdentity';
export default function MusicPanel({value,setValue,data,channels,busy,request}:{value:any;setValue:(v:any)=>void;data:any;channels:any[];busy:boolean;request:(path:string,body:any)=>Promise<any>}){
 const [music,setMusic]=useState(data),[channelId,setChannelId]=useState(''),[url,setUrl]=useState(''),[title,setTitle]=useState(''),[station,setStation]=useState('chill'),[pollError,setPollError]=useState(''),[volume,setVolume]=useState(data?.live?.status?.volume??value.defaultVolume);
 useEffect(()=>{let active=true;async function poll(){try{const r=await fetch('/api/music',{cache:'no-store'});if(!r.ok)throw Error('Müzik durumu alınamadı.');const body=await r.json();if(active){setMusic(body);setPollError('');}}catch(e){if(active)setPollError((e as Error).message);}}void poll();const timer=setInterval(()=>void poll(),4000);return()=>{active=false;clearInterval(timer);};},[]);
 const live=music?.live?.status,stale=!music?.live||Date.now()-new Date(music.live.updated_at).getTime()>30000,effectiveChannel=channelId||live?.channelId||'';
 useEffect(()=>{if(live?.volume)setVolume(live.volume);},[live?.volume]);
 const edit=(key:string,v:any)=>setValue({...value,[key]:v});
 async function action(action:string,payload:any={}){const result=await request('/api/community/music',{channelId:effectiveChannel,action,...payload});if(result){const r=await fetch('/api/music',{cache:'no-store'});if(r.ok)setMusic(await r.json());}}
 const toggle=<div className="setting-row"><div><strong>Müzik ve ses bağlantısını aç</strong><span>Bot dosya, doğrudan ses akışı ve radyo oynatsın.</span></div><button type="button" role="switch" aria-label="Müzik modülünü aç" aria-checked={value.enabled} className={'toggle '+(value.enabled?'on':'')} onClick={()=>edit('enabled',!value.enabled)}><span/></button></div>;
 return <><div className="community-grid"><section className="surface community-card"><span className="eyebrow">CANLI DİNLEME</span><h2>🎧 Müzik odası</h2><div className="music-now"><strong>{live?.current?.title||'İlk parçayı seç.'}</strong><p>{stale?'Bot durumu bekleniyor':live?.connected?(live.state==='paused'?'⏸️ Duraklatıldı':'🔊 Ses kanalına bağlı'):'Ses kanalına bağlı değil'}{live?.current&&' · '+live.seconds+' sn'}</p>{live?.current&&<DiscordIdentity id={live.current.requesterId}/>}</div>
 <ChannelPicker label="Ses kanalı" channels={channels.filter(c=>c.type===2)} voice value={effectiveChannel} onChange={setChannelId} help="Botu bağlayacağın veya kontrol edeceğin ses kanalını seç."/>
 <div className="music-controls">{[['katil','🔊 Katıl'],['ayril','👋 Ayrıl'],['duraklat','⏸ Duraklat'],['devam','▶ Devam'],['atla','⏭ Atla'],['durdur','⏹ Durdur'],['karistir','🔀 Karıştır'],['temizle','🧹 Kuyruğu temizle']].map(([key,label])=><button key={key} className="button ghost small" disabled={busy||!effectiveChannel||!value.enabled||stale} onClick={()=>void action(key)}>{label}</button>)}</div>
 <label className="form-field">Ses düzeyi · %{live?.volume??value.defaultVolume}<input type="range" aria-label="Canlı ses düzeyi" min={1} max={100} value={volume} onChange={e=>setVolume(Number(e.target.value))} disabled={busy||!live?.connected||stale} onPointerUp={e=>void action('ses',{volume:Number(e.currentTarget.value)})} onKeyUp={e=>void action('ses',{volume:Number(e.currentTarget.value)})}/></label>
 <label className="form-field">Tekrar modu<select value={live?.repeat||'OFF'} disabled={busy||!live?.connected||stale} onChange={e=>void action('tekrar',{mode:e.target.value})}><option value="OFF">Kapalı</option><option value="TRACK">Parçayı tekrarla</option><option value="QUEUE">Kuyruğu tekrarla</option></select></label>
 {live?.lastError&&<p className="error-banner" role="alert">{live.lastError}</p>}{pollError&&<p role="alert">{pollError}</p>}
 </section><section className="surface community-card"><span className="eyebrow">KAYNAK SEÇ</span><h2>Bir parça veya radyo aç.</h2><label className="form-field">HTTPS ses bağlantısı<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/parca.mp3"/></label><label className="form-field">Başlık<input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="İsteğe bağlı"/></label><button className="button primary" disabled={busy||!effectiveChannel||!url||!value.enabled||stale} onClick={()=>void action('oynat',{url,title})}>🎵 Kuyruğa ekle</button><label className="form-field music-radio">Radyo istasyonu<select value={station} onChange={e=>setStation(e.target.value)}>{radioStations.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button className="button ghost" disabled={busy||!effectiveChannel||!value.enabled||stale} onClick={()=>void action('radyo',{station})}>📻 Radyoyu aç</button><p className="role-help">Discord’da <code>/muzik oynat dosya:</code> ile MP3, OGG, WAV veya M4A yükleyebilirsin. YouTube ve Spotify sayfa bağlantıları ses kaynağı olarak desteklenmez. Radyo için anahtar gerekmez.</p><a href="https://somafm.com/" target="_blank" rel="noreferrer" className="text-link">Radyo: SomaFM ↗</a></section></div>
 <section className="surface community-card"><div className="section-top"><h2>🎶 Ortak kuyruk</h2><span>{live?.queue?.length||0} parça</span></div>{live?.queue?.length?<div className="table-scroll"><table><thead><tr><th>Sıra</th><th>Parça</th><th>Ekleyen</th><th>İşlem</th></tr></thead><tbody>{live.queue.map((t:any,n:number)=><tr key={t.id}><td>{n+1}</td><td>{t.title}</td><td><DiscordIdentity id={t.requesterId}/></td><td><div className="music-controls"><button className="button ghost small" disabled={busy||stale||n===0} onClick={()=>void action('tasi',{index:n+1,target:n})}>↑</button><button className="button ghost small" disabled={busy||stale||n===live.queue.length-1} onClick={()=>void action('tasi',{index:n+1,target:n+2})}>↓</button><button className="button ghost small" disabled={busy||stale} onClick={()=>void action('cikar',{index:n+1})}>Çıkar</button></div></td></tr>)}</tbody></table></div>:<p className="muted">Sırada parça yok. Dosya ekle veya radyo seç.</p>}</section>
 <section className="surface community-card"><span className="eyebrow">DİNLEME AYARLARI</span><h2>Kuyruk, DJ ve otomatik ayrılma.</h2>{toggle}<ChannelPicker label="Müzik için açık ses kanalları" channels={channels.filter(c=>c.type===2)} voice multiple value={value.channelIds} onChange={v=>edit('channelIds',v)} emptyLabel="Tüm ses kanalları"/><label className="form-field">DJ rol ID’leri<input defaultValue={value.djRoleIds.join(', ')} onBlur={e=>edit('djRoleIds',e.target.value.split(/[,\s]+/).filter(Boolean))}/><small>Owner ve Sunucuyu Yönet yetkilileri de DJ kontrollerini kullanabilir. Tek başına dinleyen üye kendi oturumunu yönetir.</small></label><div className="form-grid">{[['defaultVolume','Başlangıç ses düzeyi',1,100],['maxQueue','Kuyruk kapasitesi',5,100],['perUserLimit','Üye başına parça',1,20],['idleSeconds','Kuyruk boşsa ayrıl (sn)',30,1800],['emptySeconds','Kanal boşsa ayrıl (sn)',15,600],['maxTrackMinutes','Parça süre sınırı (dk)',5,240]].map(([key,label,min,max])=><label className="form-field" key={key}>{label}<input type="number" min={Number(min)} max={Number(max)} value={value[key]} onChange={e=>edit(String(key),Number(e.target.value))}/></label>)}</div><label className="form-field">Oylamayla atlama oranı<select value={value.voteSkipRatio} onChange={e=>edit('voteSkipRatio',Number(e.target.value))}>{[0.3,0.5,0.75,1].map(v=><option key={v} value={v}>%{v*100} dinleyici</option>)}</select></label><p className="role-help">Bot yeniden başlarsa ses oturumu ve oynatma kuyruğu kapanır. Son işlem sonuçları korunur. <code>/muzik yardim</code> tüm kontrolleri gösterir.</p></section>
 {!!music?.jobs?.length&&<section className="surface community-card"><h2>Son müzik işlemleri</h2><ul className="music-job-list">{music.jobs.map((j:any)=><li key={j.id}><strong>{({QUEUED:'Sırada',RUNNING:'Uygulanıyor',DONE:'Tamamlandı',FAILED:'Başarısız'} as any)[j.status]}</strong><span>{j.result||'Botun yanıtı bekleniyor.'}</span><small>{new Date(j.created_at).toLocaleTimeString('tr-TR')}</small></li>)}</ul></section>}</>;
}
