'use client';
import {useEffect,useState} from 'react';
import {Check,CheckCircle2,AlertCircle,RefreshCw,ExternalLink,Copy,Hash,ShieldCheck,Users,ArrowRight} from 'lucide-react';
import PortalGuide from './PortalGuide';
import ChannelPicker from './ChannelPicker';
const labels={guildId:'Discord sunucu ID’si',voteChannel:'Halk oylaması kanalı',logChannel:'Owner log kanalı'};
export default function SetupPanel({me,isDemo,busy,onAction,notify,login,onRoles}:{me:any;isDemo:boolean;busy:boolean;onAction:(a:string,d:any)=>Promise<boolean>;notify:(s:string)=>void;login:React.ReactNode;onRoles:()=>void}){
 const [connection,setConnection]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState({guildId:'1497372055530639504',voteChannel:'',logChannel:''});
 async function refresh(){setLoading(true);setError('');try{if(isDemo){setConnection({settings,bot:{authenticated:true,installed:false,name:'TurkishPix Parti Sistemi'},channels:[],installUrl:'https://discord.com/oauth2/authorize?client_id=1557484052133707896&scope=bot%20applications.commands&permissions=268520448&guild_id=1497372055530639504',redirectUri:window.location.origin+'/api/auth/callback'});return;}const res=await fetch('/api/setup',{cache:'no-store'}),data=await res.json();if(!res.ok)throw new Error(data.error);setConnection(data);setSettings(data.settings);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(me?.isOwner||isDemo)void refresh();},[me?.id,isDemo]);
 if(!me?.isOwner&&!isDemo)return <div className="access-panel"><ShieldCheck size={32}/><h2>Sunucu kurulumu</h2><p>Tanımlı dört owner hesabından biriyle Discord’a giriş yapın. Kanal ve rol ID’leri bu hesaplardan yönetilir.</p>{!me&&login}</div>;
 const steps=[{label:'Bot kimliği',ok:connection?.bot?.authenticated,detail:connection?.bot?.name||'Bağlantı kontrolü gerekli'},{label:'Sunucu erişimi',ok:connection?.bot?.installed,detail:connection?.guild?.name||'Botu sunucuya ekleyin'},{label:'Kanallar',ok:connection?.ready,detail:'Oylama ve log kanalı izinleri'},{label:'Rol yetkisi',ok:connection?.bot?.canManage,detail:'Rolleri Yönet ve rol sırası'}];
 return <div className="setup-page">
  <section className="setup-intro"><div><span className="eyebrow">OWNER KURULUM ALANI</span><h2>Discord’u meclise bağlayın.</h2><p>Sunucuyu belirleyin, kanalları ve rolleri listeden seçin. Bot erişimi ve izinleri kontrol etsin.</p></div><button className="button ghost" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={17} className={loading?'spin':''}/>Bağlantıyı kontrol et</button></section>
  {error&&<div className="error-banner"><AlertCircle size={17}/>{error}</div>}
  <div className="setup-steps">{steps.map((step,i)=><div key={step.label} className={step.ok?'done':''}><span>{step.ok?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><div><strong>{step.label}</strong><small>{step.detail}</small></div></div>)}</div>
  {connection&&!connection.bot?.installed&&<div className="install-card"><Users size={30}/><div><h3>Bot henüz bu sunucuda değil.</h3><p>Sunucuyu yönetme yetkisi olan bir hesapla botu ekleyin. Slash komutları otomatik kaydedilir.</p>{connection.bot?.error&&<p>{connection.bot.error}</p>}</div><a className="button primary" href={connection.installUrl} target="_blank" rel="noreferrer">Botu ekle<ExternalLink size={16}/></a></div>}
  <div className="setup-grid"><section className="surface setup-form"><div className="surface-heading"><div><span className="eyebrow">01 · KANALLAR</span><h2>Sunucu ve kanal seçimi</h2></div><Hash size={23}/></div><form onSubmit={async e=>{e.preventDefault();if(await onAction('serverSettings',settings))await refresh();}}>
   <label className="form-field">{labels.guildId}<input required pattern="[0-9]{17,20}" inputMode="numeric" value={settings.guildId} onChange={e=>setSettings(s=>({...s,guildId:e.target.value}))}/></label>
   {(['voteChannel','logChannel'] as const).map(key=><ChannelPicker key={key} label={labels[key]} channels={connection?.channels||[]} value={settings[key]} requireSend requireEmbed onChange={value=>setSettings(s=>({...s,[key]:value}))}/>)}
   <p className="role-help">Oylama kanalı halka açık, log kanalı owner’lara özel olmalı. Botun gördüğü metin kanallarını yukarıdaki listelerden seçebilirsiniz.</p><div className="form-footer"><span className="muted">Değişiklikler denetim kaydına işlenir.</span><button className="button primary" disabled={busy||isDemo}><Check size={17}/>Ayarları kaydet</button></div>
  </form></section><div className="setup-side"><section className="surface setup-card"><span className="eyebrow">02 · ROLLER</span><h2>Görevleri eşleştirin</h2><p>TBMM başkanı, parti başkanı, milletvekili ve parti üyesi için sunucudaki rolleri seçin veya ID’lerini yazın.</p><button className="button ghost full" onClick={onRoles}>Rol yönetimini aç<ArrowRight size={17}/></button><small>Botun rolünü bu rollerin üstüne taşıyın. “Rolleri Yönet” yetkisini açın.</small></section><section className="surface setup-card"><span className="eyebrow">03 · DISCORD GİRİŞİ</span><h2>Developer Portal ayarları</h2><PortalGuide redirectUri={connection?.redirectUri} application={connection?.application} notify={notify}/></section></div></div>
  {connection?.channels?.length>0&&<details className="surface connection-details"><summary>Tespit edilen kanallar ve bot izinleri <span>{connection.channels.length} kanal</span></summary><div className="table-scroll"><table><thead><tr><th>Kanal</th><th>ID</th><th>Görünürlük</th><th>Mesaj</th><th>Embed</th><th>Geçmiş</th></tr></thead><tbody>{connection.channels.map((ch:any)=><tr key={ch.id}><td>#{ch.name}</td><td>{ch.id}</td>{['view','send','embed','history'].map(k=><td key={k}>{ch.checks[k]?<CheckCircle2 size={17} className="positive"/>:<AlertCircle size={17} className="negative"/>}</td>)}</tr>)}</tbody></table></div></details>}
 </div>;
}
