'use client';
import {useEffect,useState} from 'react';
import {Check,CheckCircle2,AlertCircle,RefreshCw,ExternalLink,Copy,Hash,ShieldCheck,Users,ArrowRight} from 'lucide-react';
const labels={guildId:'Discord sunucu ID’si',voteChannel:'Halk oylaması kanal ID’si',logChannel:'Owner log kanal ID’si'};
export default function SetupPanel({me,isDemo,busy,onAction,notify,login,onRoles}:{me:any;isDemo:boolean;busy:boolean;onAction:(a:string,d:any)=>Promise<boolean>;notify:(s:string)=>void;login:React.ReactNode;onRoles:()=>void}){
 const [connection,setConnection]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState({guildId:'1497372055530639504',voteChannel:'',logChannel:''});
 async function refresh(){setLoading(true);setError('');try{if(isDemo){setConnection({settings,bot:{authenticated:true,installed:false,name:'TurkishPix Parti Sistemi'},channels:[],installUrl:'https://discord.com/oauth2/authorize?client_id=1557484052133707896&scope=bot%20applications.commands&permissions=268520448&guild_id=1497372055530639504',redirectUri:window.location.origin+'/api/auth/callback'});return;}const res=await fetch('/api/setup',{cache:'no-store'}),data=await res.json();if(!res.ok)throw new Error(data.error);setConnection(data);setSettings(data.settings);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(me?.isOwner||isDemo)void refresh();},[me?.id,isDemo]);
 if(!me?.isOwner&&!isDemo)return <div className="access-panel"><ShieldCheck size={32}/><h2>Sunucu kurulumu</h2><p>Tanımlı dört owner hesabından biriyle Discord’a giriş yapın. Kanal ve rol ID’leri bu hesaplardan yönetilir.</p>{!me&&login}</div>;
 const steps=[{label:'Bot kimliği',ok:connection?.bot?.authenticated,detail:connection?.bot?.name||'Bağlantı kontrolü gerekli'},{label:'Sunucu erişimi',ok:connection?.bot?.installed,detail:connection?.guild?.name||'Botu sunucuya ekleyin'},{label:'Kanallar',ok:connection?.ready,detail:'Oylama ve log kanalı izinleri'},{label:'Rol yetkisi',ok:connection?.bot?.canManage,detail:'Rolleri Yönet ve rol sırası'}];
 return <div className="setup-page">
  <section className="setup-intro"><div><span className="eyebrow">OWNER KURULUM ALANI</span><h2>Discord’u meclise bağlayın.</h2><p>Sunucu, kanal ve rol ID’lerini siz belirleyin. Bot erişimi ve izinleri kontrol etsin.</p></div><button className="button ghost" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={17} className={loading?'spin':''}/>Bağlantıyı kontrol et</button></section>
  {error&&<div className="error-banner"><AlertCircle size={17}/>{error}</div>}
  <div className="setup-steps">{steps.map((step,i)=><div key={step.label} className={step.ok?'done':''}><span>{step.ok?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><div><strong>{step.label}</strong><small>{step.detail}</small></div></div>)}</div>
  {connection&&!connection.bot?.installed&&<div className="install-card"><Users size={30}/><div><h3>Bot henüz bu sunucuda değil.</h3><p>Sunucuyu yönetme yetkisi olan bir hesapla botu ekleyin. Slash komutları otomatik kaydedilir.</p>{connection.bot?.error&&<p>{connection.bot.error}</p>}</div><a className="button primary" href={connection.installUrl} target="_blank" rel="noreferrer">Botu ekle<ExternalLink size={16}/></a></div>}
  <div className="setup-grid"><section className="surface setup-form"><div className="surface-heading"><div><span className="eyebrow">01 · KANALLAR</span><h2>Sunucu ve kanal ID’leri</h2></div><Hash size={23}/></div><form onSubmit={async e=>{e.preventDefault();if(await onAction('serverSettings',settings))await refresh();}}>
   {(Object.entries(labels) as [keyof typeof settings,string][]).map(([key,label])=><label className="form-field" key={key}>{label}<input required={key==='guildId'} pattern="[0-9]{17,20}" inputMode="numeric" placeholder="Discord’da ID’yi Kopyala" value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))}/>{key!=='guildId'&&connection?.channels?.length>0&&<select aria-label={label+' seçimi'} value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))}><option value="">Sunucudan kanal seçin</option>{connection.channels.map((ch:any)=><option key={ch.id} value={ch.id}>#{ch.name}{ch.usable?'':' · izin eksik'}</option>)}</select>}{key!=='guildId'&&connection?.selected?.[key]?.configured&&<small className={connection.selected[key].ready?'positive':'negative'}>{connection.selected[key].ready?'Kanal bulundu; mesaj ve embed izinleri uygun.':'Kanal bulunamadı veya botun izinleri yetersiz.'}</small>}</label>)}
   <p className="role-help">Oylama kanalı halka açık, log kanalı owner’lara özel olmalı. Discord → Ayarlar → Gelişmiş → Geliştirici Modu’nu açarak ID’leri kopyalayabilirsiniz.</p><div className="form-footer"><span className="muted">Değişiklikler denetim kaydına işlenir.</span><button className="button primary" disabled={busy||isDemo}><Check size={17}/>ID’leri kaydet</button></div>
  </form></section><div className="setup-side"><section className="surface setup-card"><span className="eyebrow">02 · ROLLER</span><h2>Görevleri eşleştirin</h2><p>TBMM başkanı, parti başkanı, milletvekili ve parti üyesi için sunucudaki rolleri seçin veya ID’lerini yazın.</p><button className="button ghost full" onClick={onRoles}>Rol yönetimini aç<ArrowRight size={17}/></button><small>Botun rolünü bu rollerin üstüne taşıyın. “Rolleri Yönet” yetkisini açın.</small></section><section className="surface setup-card"><span className="eyebrow">03 · DISCORD GİRİŞİ</span><h2>OAuth yönlendirmesi</h2><p>Discord Developer Portal → OAuth2 → Redirects alanına bu adresi ekleyin.</p><div className="copy-value"><code>{connection?.redirectUri||'Bağlantı kontrolünden sonra gösterilir'}</code><button className="icon-button" aria-label="OAuth adresini kopyala" onClick={async()=>{if(connection?.redirectUri){await navigator.clipboard.writeText(connection.redirectUri);notify('OAuth yönlendirme adresi kopyalandı.');}}}><Copy size={16}/></button></div><a className="text-link" href="https://discord.com/developers/applications/1557484052133707896/oauth2" target="_blank" rel="noreferrer">Developer Portal<ExternalLink size={14}/></a></section></div></div>
  {connection?.channels?.length>0&&<details className="surface connection-details"><summary>Tespit edilen kanallar ve bot izinleri <span>{connection.channels.length} kanal</span></summary><div className="table-scroll"><table><thead><tr><th>Kanal</th><th>ID</th><th>Görünürlük</th><th>Mesaj</th><th>Embed</th><th>Geçmiş</th></tr></thead><tbody>{connection.channels.map((ch:any)=><tr key={ch.id}><td>#{ch.name}</td><td>{ch.id}</td>{['view','send','embed','history'].map(k=><td key={k}>{ch.checks[k]?<CheckCircle2 size={17} className="positive"/>:<AlertCircle size={17} className="negative"/>}</td>)}</tr>)}</tbody></table></div></details>}
 </div>;
}
