'use client';
import {useState,useEffect} from 'react';
import YouTubePlayer from './YouTubePlayer';
export default function YouTubePanel({status,channelId,busy,request}:{status:any;channelId:string;busy:boolean;request:(path:string,body:any)=>Promise<any>}){
 const [apiKey,setApiKey]=useState(''),[configured,setConfigured]=useState(!!status?.configured),[query,setQuery]=useState(''),[url,setUrl]=useState(''),[videos,setVideos]=useState<any[]>([]),[current,setCurrent]=useState<any>(null),[invite,setInvite]=useState('');
 useEffect(()=>{setConfigured(!!status?.configured);},[status?.configured]);
 useEffect(()=>{setInvite('');},[channelId,current?.id]);
 async function search(){const result=await request('/api/community/youtube',{action:'search',query});if(result)setVideos(result.videos);}
 async function open(input:string){const r=await request('/api/community/youtube',{action:'video',url:input});if(r)setCurrent(r.video);}
 return <><section className="surface community-card"><span className="eyebrow">YOUTUBE · BİRLİKTE DİNLE</span><h2>Şarkını ara, kapaktan seç.</h2><p>Panelde YouTube oynatıcısını kullan veya Discord ses kanalında Watch Together oturumu başlat.</p><div className="form-grid"><label className="form-field">YouTube araması<input maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Şarkı veya video adı" onKeyDown={e=>{if(e.key==='Enter'&&!busy&&configured&&query.trim().length>=2){e.preventDefault();void search();}}}/><button className="button primary" disabled={busy||query.trim().length<2||!configured} onClick={()=>void search()}>YouTube’da ara</button></label><label className="form-field">Video bağlantısı<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=…"/><button className="button ghost" disabled={busy||!url} onClick={()=>void open(url)}>Videoyu aç</button></label></div>{!configured&&<p className="role-help">Video bağlantısı ve Watch Together hazır. Adla arama için aşağıdan YouTube API bağlantısını kur.</p>}<button className="button discord" disabled={busy||!channelId} onClick={async()=>{const r=await request('/api/community/youtube',{action:'together',channelId});if(r)setInvite(r.url);}}>▶ Ses kanalında Watch Together aç</button>{invite&&<div className="youtube-session-note"><a className="button primary" href={invite} target="_blank" rel="noreferrer">Ortak oturuma katıl ↗</a><p>Oturumdaki arama kutusuna {current?'aşağıdaki seçili video bağlantısını yapıştır':'şarkı adını yaz veya bir video bağlantısı yapıştır'}. Katılımcılar aynı oynatma listesini izler ve dinler.</p>{current&&<input aria-label="Ortak oturuma yapıştırılacak video bağlantısı" readOnly value={current.url} onClick={e=>e.currentTarget.select()}/>}</div>}
 {!!videos.length&&<div className="youtube-results">{videos.map(v=><article key={v.id} className={current?.id===v.id?'selected':''}><img src={v.thumbnail} alt=""/><div><strong>{v.title}</strong><span>{v.channel}</span></div><button className="button ghost small" disabled={busy} onClick={()=>void open(v.url)}>{current?.id===v.id?'✓ Seçildi':'▶ Seç ve izle'}</button><button className="button ghost small" disabled={busy} onClick={()=>void request('/api/community/youtube',{action:'favourite',url:v.url})}>♡ Favori</button></article>)}</div>}
 {current&&<div className="youtube-current"><span className="eyebrow">SEÇİLEN VİDEO</span><h3>{current.title}</h3><p className="muted">{current.channel}</p><YouTubePlayer videoId={current.id}/><a className="text-link" target="_blank" rel="noreferrer" href={current.url}>YouTube’da aç ↗</a></div>}</section>
 <section className="surface community-card"><span className="eyebrow">ARAMA BAĞLANTISI</span><h2>YouTube Data API v3</h2><p>{configured?'Bağlantı hazır. Anahtarını değiştirmek için yenisini gir.':'Google Cloud’da YouTube Data API v3’ü etkinleştirip bir API anahtarı oluştur.'} Anahtar yalnızca sunucuda kullanılır.</p><label className="form-field">API anahtarı<input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Google API anahtarı"/></label><button className="button primary" disabled={busy||apiKey.trim().length<20} onClick={async()=>{const r=await request('/api/community/youtube-key',{apiKey});if(r){setApiKey('');setConfigured(true);}}}>Bağlantıyı doğrula ve kaydet</button><a className="text-link" href="https://console.cloud.google.com/apis/library/youtube.googleapis.com" target="_blank" rel="noreferrer">Google Cloud · YouTube API ↗</a><p className="role-help">Anahtarı YouTube Data API v3 ile sınırla. Arama kota kullanır. Data API ses akışı sağlamaz; YouTube videoları görünür oynatıcı ve Watch Together üzerinden açılır.</p></section></>;
}
