import {randomInt,createHash} from 'node:crypto';
import {DomainError} from './config';
import {isArcadeBoard} from './arcade-policy';
import {createArcadeBoard,advanceArcadeBoard} from './arcade-boards';
export const rand=(max:number)=>randomInt(max);
export function shuffle<T>(items:T[],rng=rand){const a=[...items];for(let i=a.length-1;i>0;i--){const j=rng(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
export function dailyValue(key:string,date=new Date()){const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(date);return createHash('sha256').update(key+':'+day).digest().readUInt32BE(0);}
export function listItems(input:string,min:number,max:number){const items=input.split('|').map(x=>x.trim()).filter(Boolean);if(items.length<min||items.length>max||items.some(x=>x.length>80)||new Set(items.map(x=>x.toLocaleLowerCase('tr-TR'))).size!==items.length)throw new DomainError('INVALID_LIST',`${min}–${max} farklı maddeyi | ile ayırın. Her madde en fazla 80 karakter olabilir.`);return items;}
export const safeText=(text:string)=>text.replace(/@/g,'＠').replace(/[\\*_~`|<>\[\]]/g,'\\$&');
export type GameState={kind:string;phase:string;revision:number;message:string;result?:'WIN'|'LOSE'|'DRAW';[key:string]:any};
const riddles=[
 ['Dört ayağı var, yürüyemez. Nedir?','Masa','Kedi','At','Köpek'],['Ne kadar alırsan o kadar büyür. Nedir?','Çukur','Çanta','Kitap','Bardak'],['Ben giderim, o gider; üstümde gölge eder. Nedir?','Şemsiye','Ayakkabı','Saat','Kalem'],['Gece görünür, gündüz saklanır. Nedir?','Yıldız','Bulut','Ağaç','Göl']
];
const knowledge=[
 ['Suyun kimyasal formülü hangisidir?','H₂O','CO₂','O₂','NaCl'],['Güneş Sistemi’nin en büyük gezegeni hangisidir?','Jüpiter','Dünya','Mars','Venüs'],['Bir üçgenin iç açıları toplamı kaç derecedir?','180','90','270','360'],['Satranç tahtasında kaç kare vardır?','64','32','48','81'],['Fotosentez sırasında bitkilerin havaya verdiği gaz hangisidir?','Oksijen','Hidrojen','Azot','Helyum'],['Türkiye’nin başkenti neresidir?','Ankara','İstanbul','İzmir','Bursa']
];
const history=[
 ['Türkiye Cumhuriyeti hangi tarihte ilan edildi?','29 Ekim 1923','23 Nisan 1920','19 Mayıs 1919','30 Ağustos 1922'],['TBMM hangi tarihte açıldı?','23 Nisan 1920','29 Ekim 1923','19 Mayıs 1919','10 Kasım 1938'],['Mustafa Kemal Atatürk Samsun’a ne zaman çıktı?','19 Mayıs 1919','23 Nisan 1920','29 Ekim 1923','30 Ağustos 1922'],['İstanbul’un fethi hangi yılda gerçekleşti?','1453','1071','1299','1517'],['Malazgirt Savaşı hangi yılda gerçekleşti?','1071','1453','1517','1922'],['Lozan Barış Antlaşması hangi yılda imzalandı?','1923','1919','1920','1922']
];
const words=[['CUMHURİYET','Bir yönetim biçimi'],['KÜTÜPHANE','Kitapların evi'],['ARKADAŞ','Sohbetini sevdiğin kişi'],['DAYANIŞMA','Birbirine destek olmak'],['BİLGİSAYAR','Dijital çalışma aracı'],['GÖKKUŞAĞI','Yağmurdan sonra renkler'],['ASTRONOT','Uzay yolcusu'],['DEMOKRASİ','Halkın yönetime katılması'],['MATEMATİK','Sayılar ve işlemler'],['İSTANBUL','İki kıtadaki şehir']];
function quiz(kind:string,question:string,answer:string,wrong:string[],rng:(n:number)=>number):GameState{const choices=shuffle([answer,...wrong],rng);return {kind,phase:'PLAY',revision:0,message:'Bir seçenek seç.',question,choices,answer:choices.indexOf(answer)};}
export function createGame(kind:string,difficulty='normal',rng=rand,now=Date.now()):GameState{
 const base={kind,phase:'PLAY',revision:0,message:'Oyun başladı.'};
 if(isArcadeBoard(kind))return {...base,puzzle:createArcadeBoard(kind,rng)};
 if(kind==='tas-kagit-makas')return {...base,bot:rng(3)};
 if(kind==='sayi-tahmin'){const max=difficulty==='kolay'?20:difficulty==='zor'?500:100;return {...base,max,answer:rng(max)+1,attempts:0,guesses:[],message:`1–${max} arasında bir sayı tuttum. 6 deneme hakkın var.`};}
 if(kind==='kelime-tahmin'){const [answer,hint]=words[rng(words.length)];return {...base,answer,hint,letters:[],errors:0};}
 if(['bilmece','bilgi','tarih-sorusu'].includes(kind)){const set=kind==='bilmece'?riddles:kind==='bilgi'?knowledge:history;const [q,a,...wrong]=set[rng(set.length)];return quiz(kind,q,a,wrong,rng);}
 if(kind==='matematik'){const bound=difficulty==='kolay'?10:difficulty==='zor'?100:30,a=rng(bound)+1,b=rng(bound)+1,op=rng(3),answer=op===0?a+b:op===1?a-b:a*b;const wrong=new Set<number>();while(wrong.size<3){const offset=wrong.size+1;wrong.add(answer+(rng(2)?1:-1)*offset);}return quiz(kind,`${a} ${['+','−','×'][op]} ${b} = ?`,String(answer),[...wrong].map(String),rng);}
 if(kind==='hafiza'){const sequence=shuffle(['🍎','🌙','⭐','🎈','🎲','🧩','🌻','🚀'],rng).slice(0,5);const choices=[sequence.join(' ')];for(let i=1;i<=3;i++){const other=[...sequence];[other[0],other[i]]=[other[i],other[0]];choices.push(other.join(' '));}const mixed=shuffle(choices,rng);return {...base,phase:'MEMORIZE',sequence:sequence.join(' '),choices:mixed,answer:mixed.indexOf(sequence.join(' '))};}
 if(kind==='refleks')return {...base,phase:'READY',createdAt:now};
 if(kind==='xox')return {...base,board:Array(9).fill(''),difficulty};
 throw new DomainError('UNKNOWN_GAME','Bu oyun bulunamadı.');
}
export function boardWinner(b:string[]){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'DRAW':null;}
function minimax(b:string[],bot:boolean):number{const winner=boardWinner(b);if(winner)return winner==='O'?1:winner==='X'?-1:0;const scores=b.flatMap((v,i)=>{if(v)return [];b[i]=bot?'O':'X';const s=minimax(b,!bot);b[i]='';return [s];});return bot?Math.max(...scores):Math.min(...scores);}
export function botMove(b:string[],difficulty:string,rng=rand){const empty=b.flatMap((v,i)=>v?[]:[i]);if(difficulty==='kolay')return empty[rng(empty.length)];if(difficulty==='normal'){for(const p of ['O','X'])for(const i of empty){b[i]=p;const win=boardWinner(b);b[i]='';if(win===p)return i;}return empty.includes(4)?4:empty[rng(empty.length)];}let best=-2,moves:number[]=[];for(const i of empty){b[i]='O';const score=minimax(b,false);b[i]='';if(score>best){best=score;moves=[i];}else if(score===best)moves.push(i);}return moves[rng(moves.length)];}
const finish=(s:GameState,result:GameState['result'],message:string)=>Object.assign(s,{phase:'DONE',result,message});
export function advanceGame(previous:GameState,action:string,value='',now=Date.now(),rng=rand):GameState{
 const s=structuredClone(previous);if(s.phase==='DONE')throw new DomainError('GAME_CLOSED','Bu oyun tamamlandı. Yeni bir oyun başlatabilirsin.');
 s.revision++;if(action==='cancel')return finish(s,'LOSE','Turu bitirdin. İstediğinde yeni bir oyun başlatabilirsin.');const index=Number(action);
 if(isArcadeBoard(s.kind)){try{s.puzzle=advanceArcadeBoard(s.puzzle,action,rng);}catch(e){throw new DomainError('INVALID_MOVE',e instanceof Error?e.message:'Geçersiz hamle.');}s.message=s.puzzle.done?(s.puzzle.result==='WIN'?'Kazandın!':s.puzzle.result==='DRAW'?'Berabere!':'Bu tur sona erdi.'):'Sıra sende.';return s.puzzle.done?finish(s,s.puzzle.result,s.message):s;}
 if(s.kind==='tas-kagit-makas'){if(!['0','1','2'].includes(action))throw new DomainError('INVALID_MOVE','Geçersiz seçim.');const result=(index-s.bot+3)%3;return finish(s,result===0?'DRAW':result===1?'WIN':'LOSE',`Sen: ${['🪨 Taş','📄 Kâğıt','✂️ Makas'][index]} · Bot: ${['🪨 Taş','📄 Kâğıt','✂️ Makas'][s.bot]}`);}
 if(s.kind==='sayi-tahmin'){if(action!=='guess'||!/^\d{1,3}$/.test(value)||Number(value)<1||Number(value)>s.max)throw new DomainError('INVALID_GUESS',`1–${s.max} arasında tam sayı gir.`);const guess=Number(value);if(s.guesses.includes(guess))throw new DomainError('REPEAT_GUESS','Bu sayıyı zaten denedin.');s.attempts++;s.guesses.push(guess);if(guess===s.answer)return finish(s,'WIN',`${s.attempts}. denemede ${s.answer} sayısını buldun!`);if(s.attempts===6)return finish(s,'LOSE',`Hakların bitti. Gizli sayı: ${s.answer}.`);s.message=`${guess}: daha ${guess<s.answer?'büyük':'küçük'} bir sayı dene. Kalan hak: ${6-s.attempts}.`;return s;}
 if(s.kind==='kelime-tahmin'){const guess=value.trim().toLocaleUpperCase('tr-TR');if(action!=='guess'||!/^[A-ZÇĞİÖŞÜ]{1,20}$/.test(guess))throw new DomainError('INVALID_GUESS','Tek bir Türkçe harf veya kelime gir.');if(s.letters.includes(guess))throw new DomainError('REPEAT_GUESS','Bu harfi zaten denedin.');if(guess===s.answer)return finish(s,'WIN',`Kelimeyi buldun: ${s.answer}!`);s.letters.push(guess);if(guess.length>1||!s.answer.includes(guess))s.errors++;if([...s.answer].every(x=>s.letters.includes(x)))return finish(s,'WIN',`Kelimeyi buldun: ${s.answer}!`);if(s.errors>=6)return finish(s,'LOSE',`Hakların bitti. Kelime: ${s.answer}.`);s.message=`Kalan hata hakkı: ${6-s.errors}.`;return s;}
 if(s.kind==='hafiza'&&s.phase==='MEMORIZE'){if(action!=='ready')throw new DomainError('INVALID_MOVE','Önce hazır olduğunda düğmeye bas.');s.phase='PLAY';s.message='Doğru emoji sırasını seç.';return s;}
 if(['bilmece','bilgi','tarih-sorusu','matematik','hafiza'].includes(s.kind)){if(!['0','1','2','3'].includes(action))throw new DomainError('INVALID_MOVE','Geçersiz seçenek.');return finish(s,index===s.answer?'WIN':'LOSE',`${index===s.answer?'Doğru cevap!':'Bu kez olmadı.'} Cevap: ${s.choices[s.answer]}`);}
 if(s.kind==='refleks'){if(s.phase==='READY'&&action==='start'){s.phase='WAIT';s.targetAt=now+3000+rng(4001);s.message='Yeşil düğmeyi bekle. Erken basarsan oyun biter.';return s;}if(s.phase==='WAIT'&&action==='hit'){if(now<s.targetAt)return finish(s,'LOSE','Erken bastın! Yeşil düğmeyi beklemeliydin.');s.elapsed=now-s.targetAt;return finish(s,s.elapsed<=2000?'WIN':'LOSE',`Tepki süren: ${s.elapsed} ms. Discord ve ağ gecikmesi bu ölçüme dahildir.`);}throw new DomainError('INVALID_MOVE','Önce oyunu başlat.');}
 if(s.kind==='xox'){if(!/^[0-8]$/.test(action)||s.board[index])throw new DomainError('INVALID_MOVE','Boş bir kare seç.');s.board[index]='X';let winner=boardWinner(s.board);if(!winner){s.board[botMove(s.board,s.difficulty,rng)]='O';winner=boardWinner(s.board);}if(winner)return finish(s,winner==='X'?'WIN':winner==='O'?'LOSE':'DRAW',winner==='DRAW'?'Berabere!':winner==='X'?'Kazandın!':'Bot kazandı. Yeni bir tur deneyebilirsin.');s.message='Sıra sende. Sen ❌, bot ⭕.';return s;}
 throw new DomainError('INVALID_MOVE','Geçersiz oyun işlemi.');
}
