import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {config,DomainError} from './config';
import {database,transaction} from './db';
import {syncUser,discordRequest} from './discord';
import {audit} from './audit';
import {recordDiscordAudit} from './discord-audit';
import {featureMutation,getFeatureRecord,type FeatureActor,levelInfo,queueLevelUp} from './features';
import {communitySettings,saveCommunitySettings,type CommunitySettings} from './community';
import {expansionSettingsSchema,eventOptionsSchema,validBirthday,AUTOMATIC_ROLE_DANGER_MASK,type ExpansionSettings} from './expansion-policy';
import {brightEmbed,displayText,userTag,theme} from './presentation';
import {discordRoleCatalog,roleMappings} from './roles';
import {ownerOnly} from './service';
import {addFeatureRecord,listFeatureRecords} from './features';
import {inspectContent} from './moderation-engine';
const snowflake=z.string().regex(/^\d{17,20}$/);
const dangerousPermissions=AUTOMATIC_ROLE_DANGER_MASK;
export async function expansionRoleDirectory(){const c=await discordRoleCatalog(),protectedIds=Object.values(await roleMappings()).filter(Boolean);const channels=await discordRequest('/guilds/'+config().guildId+'/channels');return {...c,roles:c.roles.map(r=>{
 const blockedReason=r.id===config().guildId?'@everyone tüm üyelerde zaten bulunur. Ayrı bir Üye rolü seç.':r.managed?'Bu rol Discord veya bağlı uygulaması tarafından yönetiliyor.':protectedIds.includes(r.id)?'Bu siyasi görev rolü kendi görev sisteminden verilir.':BigInt(r.permissions)&dangerousPermissions?'Bu rol yönetim veya moderasyon yetkisi taşıyor.':channels.some((ch:any)=>(ch.permission_overwrites||[]).some((o:any)=>o.id===r.id&&(BigInt(o.allow)&dangerousPermissions)))?'Bu role kanal içinde yönetim veya moderasyon yetkisi verilmiş.':r.blockedReason;
 return {...r,manageable:!blockedReason,blockedReason};
 })};}
export async function validateExpansionSettings(input:ExpansionSettings){
 const s=expansionSettingsSchema.parse(input);const roleIds=[...s.autoRoleIds,...s.levelRoles.map(r=>r.roleId),s.registration.memberRoleId,s.registration.unregisteredRoleId].filter(Boolean);
 if(roleIds.length){const catalog=await expansionRoleDirectory();for(const id of roleIds){const role=catalog.roles.find(r=>r.id===id);if(!role?.manageable)throw new DomainError('UNSAFE_AUTOMATIC_ROLE',role?'@'+role.name+': '+role.blockedReason:'Seçilen rol artık sunucuda yok.',403);}}
 if(s.registration.memberRoleId&&s.registration.memberRoleId===s.registration.unregisteredRoleId)throw new DomainError('REGISTRATION_ROLES','Kayıtlı ve kayıtsız rolleri farklı olmalı.');
 if(s.rooms.createChannelId){const channel=await discordRequest('/channels/'+s.rooms.createChannelId);if(channel.guild_id!==config().guildId||channel.type!==2)throw new DomainError('ROOM_LOBBY','Bu sunucudan bir oda oluşturma ses kanalı seç.');}
 if(s.rooms.categoryId){const channel=await discordRequest('/channels/'+s.rooms.categoryId);if(channel.guild_id!==config().guildId||channel.type!==4)throw new DomainError('ROOM_CATEGORY','Bu sunucudan bir kanal kategorisi seç.');}
}
export async function setAFK(actor:FeatureActor,reason:string|null,key:string){if(reason!==null)reason=z.string().trim().min(1).max(150).parse(reason);return featureMutation(actor,key,async tx=>{await tx.query('INSERT INTO member_utilities(guild_id,user_id,afk_reason,afk_at) VALUES($1,$2,$3,CASE WHEN $3::text IS NULL THEN NULL ELSE now() END) ON CONFLICT(guild_id,user_id) DO UPDATE SET afk_reason=EXCLUDED.afk_reason,afk_at=EXCLUDED.afk_at',[config().guildId,actor.id,reason]);return {reason};});}
export async function clearAFK(userId:string){return (await database().query('UPDATE member_utilities SET afk_reason=NULL,afk_at=NULL WHERE guild_id=$1 AND user_id=$2 AND afk_reason IS NOT NULL RETURNING user_id',[config().guildId,userId])).rows.length>0;}
export async function mentionedAFK(ids:string[]){return ids.length?(await database().query('SELECT user_id,afk_reason,afk_at FROM member_utilities WHERE guild_id=$1 AND user_id=ANY($2::text[]) AND afk_reason IS NOT NULL LIMIT 5',[config().guildId,ids.slice(0,20)])).rows:[];}
export async function setBirthday(actor:FeatureActor,day:number|null,month:number|null,key:string){if(day!==null&&(!month||!validBirthday(day,month)))throw new DomainError('BIRTHDAY_DATE','Geçerli bir gün ve ay seç.');return featureMutation(actor,key,async tx=>{await tx.query('INSERT INTO member_utilities(guild_id,user_id,birthday_day,birthday_month) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,user_id) DO UPDATE SET birthday_day=EXCLUDED.birthday_day,birthday_month=EXCLUDED.birthday_month',[config().guildId,actor.id,day,month]);return {day,month};});}
export async function birthdayCalendar(){return (await database().query('SELECT m.user_id,u.username,m.birthday_day,m.birthday_month FROM member_utilities m JOIN users u ON u.id=m.user_id WHERE m.guild_id=$1 AND m.birthday_day IS NOT NULL ORDER BY birthday_month,birthday_day LIMIT 100',[config().guildId])).rows;}
export function customResponse(template:string,actor:FeatureActor,server:string){return template.replace(/\{(user|username|server)\}/g,(_,name)=>name==='user'?userTag(actor.id):displayText(name==='username'?actor.username:server,200));}
export async function changeCustomCommand(actor:FeatureActor,input:{name:string;response?:string;channelId?:string}){
 // Called after Discord ManageGuild authorization; the same owner-only settings validation is used for panel writes.
 const name=z.string().regex(/^[a-z0-9-]{1,32}$/).parse(input.name),settings=await communitySettings();let commands=settings.expansion.customCommands.filter(c=>c.name!==name);
 if(input.response)commands.push({name,response:z.string().trim().min(1).max(1500).parse(input.response),channelId:input.channelId||''});settings.expansion.customCommands=commands;expansionSettingsSchema.parse(settings.expansion);
 if(input.channelId){const ch=await discordRequest('/channels/'+input.channelId);if(ch.guild_id!==config().guildId||![0,5].includes(ch.type))throw new DomainError('INVALID_CHANNEL','Bu sunucudan bir metin kanalı seç.');}
 await transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['custom-commands:'+config().guildId]);await syncUser(tx,actor);const row=(await tx.query('SELECT settings FROM community_settings WHERE guild_id=$1 FOR UPDATE',[config().guildId])).rows[0];const current=row?row.settings:settings;const expanded=expansionSettingsSchema.parse(current.expansion||settings.expansion);expanded.customCommands=expanded.customCommands.filter(c=>c.name!==name);if(input.response)expanded.customCommands.push({name,response:input.response.trim(),channelId:input.channelId||''});expansionSettingsSchema.parse(expanded);current.expansion=expanded;await tx.query('INSERT INTO community_settings(guild_id,settings,updated_by) VALUES($1,$2,$3) ON CONFLICT(guild_id) DO UPDATE SET settings=EXCLUDED.settings,updated_by=EXCLUDED.updated_by,updated_at=now()',[config().guildId,current,actor.id]);await audit(tx,actor.id,input.response?'CUSTOM_COMMAND_SAVED':'CUSTOM_COMMAND_REMOVED',name);});return {name};
}
export async function awardVoiceXP(actor:FeatureActor,settings:CommunitySettings){
 const f=settings.features,e=settings.expansion;if(!e.enabled||!e.voiceXP.enabled||!f.enabled||!f.economy||!f.xpEnabled)return false;
 return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['profile:'+config().guildId+':'+actor.id]);await syncUser(tx,actor);await tx.query('INSERT INTO member_profiles(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[config().guildId,actor.id]);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());const result=await tx.query(`UPDATE member_profiles SET xp=xp+$3,voice_minutes=voice_minutes+1,last_voice_xp_at=now(),xp_day=$4,xp_today=CASE WHEN xp_day=$4 THEN xp_today+$3 ELSE $3 END WHERE guild_id=$1 AND user_id=$2 AND (last_voice_xp_at IS NULL OR last_voice_xp_at<=now()-interval '60 seconds') AND (xp_day IS DISTINCT FROM $4::date OR xp_today+$3<=$5) RETURNING xp,last_chat_channel_id`,[config().guildId,actor.id,e.voiceXP.perMinute,today,f.xpDailyCap]);if(result.rows.length)await queueLevelUp(tx,actor.id,result.rows[0].xp,e.voiceXP.perMinute,f,f.levelUpChannel||result.rows[0].last_chat_channel_id);return !!result.rows.length;});
}
export async function eventRSVP(actor:FeatureActor,id:string,choice:'GOING'|'MAYBE'|'DECLINED'|'LEAVE'|'TOGGLE',roleIds:string[],key:string){
 return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(r.kind!=='EVENT'||r.status!=='OPEN'||!r.due_at||new Date(r.due_at).getTime()<=Date.now())throw new DomainError('EVENT_CLOSED','Etkinlik artık katılıma açık değil.');const options=eventOptionsSchema.parse(r.payload);
  const old=(await tx.query('SELECT choice FROM feature_participants WHERE record_id=$1 AND user_id=$2',[id,actor.id])).rows[0]?.choice;
  let selected:'GOING'|'MAYBE'|'DECLINED'|'LEAVE'|'WAITLIST'=choice==='TOGGLE'?(old==='GOING'||old==='WAITLIST'?'LEAVE':'GOING'):choice;
  if(selected!=='LEAVE'&&options.requiredRoleId&&!roleIds.includes(options.requiredRoleId))throw new DomainError('EVENT_ROLE','Bu etkinliğe katılmak için kartta belirtilen rol gerekli.',403);
  if(selected==='GOING'&&old!=='GOING'&&options.capacity){const count=(await tx.query("SELECT count(*)::int AS n FROM feature_participants WHERE record_id=$1 AND choice='GOING'",[id])).rows[0].n;if(count>=options.capacity)selected='WAITLIST' as any;}
  if(selected==='LEAVE')await tx.query('DELETE FROM feature_participants WHERE record_id=$1 AND user_id=$2',[id,actor.id]);else await tx.query('INSERT INTO feature_participants(record_id,user_id,choice) VALUES($1,$2,$3) ON CONFLICT(record_id,user_id) DO UPDATE SET choice=EXCLUDED.choice,created_at=CASE WHEN feature_participants.choice=EXCLUDED.choice THEN feature_participants.created_at ELSE now() END',[id,actor.id,selected]);
  if(old==='GOING'&&selected!=='GOING'){await tx.query("UPDATE feature_participants SET choice='GOING' WHERE record_id=$1 AND user_id=(SELECT user_id FROM feature_participants WHERE record_id=$1 AND choice='WAITLIST' ORDER BY created_at,user_id LIMIT 1)",[id]);}
  await tx.query('UPDATE feature_records SET updated_at=now() WHERE id=$1',[id]);const count=(await tx.query("SELECT count(*)::int AS n FROM feature_participants WHERE record_id=$1 AND choice='GOING'",[id])).rows[0].n;return {choice:selected,count,joined:selected==='GOING'||selected==='WAITLIST',record:r};
 });
}
export async function eventAttendees(id:string){const r=await getFeatureRecord(id);if(r.kind!=='EVENT')throw new DomainError('EVENT_KIND','Bir etkinlik kodu seç.');return (await database().query('SELECT user_id,choice FROM feature_participants WHERE record_id=$1 ORDER BY choice,created_at LIMIT 100',[id])).rows;}
export async function editEvent(actor:FeatureActor,id:string,minutes:number,title:string|undefined,staff:boolean,key:string){z.number().int().min(5).max(43200).parse(minutes);if(title)z.string().trim().min(1).max(100).parse(title);return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(r.kind!=='EVENT'||r.status!=='OPEN')throw new DomainError('EVENT_CLOSED','Açık bir etkinlik seç.');if(r.owner_id!==actor.id&&!staff)throw new DomainError('FORBIDDEN','Bu etkinliğin organizatörü değilsin.',403);const next=(await tx.query('UPDATE feature_records SET due_at=now()+$2*interval \'1 minute\',title=COALESCE($3,title),updated_at=now() WHERE id=$1 RETURNING *',[id,minutes,title?.trim()||null])).rows[0];await tx.query("UPDATE community_deliveries SET status='CANCELLED',last_error='CANCELLED' WHERE guild_id=$1 AND kind='SOCIAL' AND payload->>'recordId'=$2 AND status='QUEUED'",[config().guildId,id]);await tx.query("UPDATE feature_records SET payload=payload-'remindersSent' WHERE id=$1",[id]);await audit(tx,actor.id,'EVENT_EDITED',id,{minutes});return next;});}
export async function eventMaintenance(settings:CommunitySettings){
 if(!settings.features.enabled||!settings.features.community)return;
 await transaction(async tx=>{const records=(await tx.query("SELECT r.*,u.username FROM feature_records r JOIN users u ON u.id=r.owner_id WHERE r.guild_id=$1 AND r.kind='EVENT' AND r.status='OPEN' ORDER BY due_at LIMIT 100 FOR UPDATE OF r SKIP LOCKED",[config().guildId])).rows;
  for(const r of records){const options=eventOptionsSchema.parse(r.payload),due=new Date(r.due_at).getTime(),now=Date.now();const sent=r.payload.remindersSent||[];
   for(const minutes of options.reminders){if(!r.message_id||sent.includes(minutes)||now<due-minutes*60000||now>=due)continue;
    const users=(await tx.query("SELECT user_id FROM feature_participants WHERE record_id=$1 AND choice='GOING' ORDER BY user_id",[r.id])).rows;
    for(let n=0;n<users.length;n+=20){const mentions=users.slice(n,n+20).map(u=>u.user_id);await tx.query("INSERT INTO community_deliveries(id,guild_id,kind,payload,dedupe_key) VALUES(gen_random_uuid(),$1,'SOCIAL',$2,$3) ON CONFLICT(dedupe_key) DO NOTHING",[config().guildId,{source:'EVENT',recordId:r.id,channelId:r.channel_id,mentionUsers:mentions,content:mentions.map((id:string)=>userTag(id)).join(' ')+'\n**'+displayText(r.title)+'** <t:'+Math.floor(due/1000)+':R> başlıyor.\nhttps://discord.com/channels/'+config().guildId+'/'+r.channel_id+'/'+r.message_id},'event-reminder:'+r.id+':'+due+':'+minutes+':'+n]);}sent.push(minutes);
   }
   const payload={...r.payload,remindersSent:sent};if(now>=due){await tx.query("UPDATE feature_records SET status='DONE',payload=$2,updated_at=now() WHERE id=$1",[r.id,payload]);if(options.repeat!=='OFF'){const interval=(options.repeat==='DAILY'?1:7)*86400000,nextDue=due+(Math.floor((now-due)/interval)+1)*interval,nextId=randomUUID();await tx.query("INSERT INTO feature_records(id,guild_id,owner_id,kind,title,payload,channel_id,due_at) VALUES($1,$2,$3,'EVENT',$4,$5,$6,$7)",[nextId,config().guildId,r.owner_id,r.title,{...options,seriesId:r.payload.seriesId||r.id,previousId:r.id},r.channel_id,new Date(nextDue).toISOString()]);}}else if(JSON.stringify(payload)!==JSON.stringify(r.payload))await tx.query('UPDATE feature_records SET payload=$2 WHERE id=$1',[r.id,payload]);
  }
 });
}
export async function scheduledAnnouncement(actor:FeatureActor,channelId:string,content:string,minutes:number,key:string){snowflake.parse(channelId);z.string().trim().min(1).max(1500).parse(content);z.number().int().min(1).max(43200).parse(minutes);const result=await featureMutation(actor,key,async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['scheduled:'+config().guildId+':'+actor.id]);if((await tx.query("SELECT count(*)::int AS n FROM community_deliveries WHERE guild_id=$1 AND kind='ANNOUNCEMENT' AND payload->>'scheduledBy'=$2 AND status='QUEUED'",[config().guildId,actor.id])).rows[0].n>=20)throw new DomainError('SCHEDULE_LIMIT','En fazla 20 bekleyen duyuru planlayabilirsin.');const id=randomUUID();await tx.query("INSERT INTO community_deliveries(id,guild_id,kind,payload,available_at) VALUES($1,$2,'ANNOUNCEMENT',$3,now()+$4*interval '1 minute')",[id,config().guildId,{channelId,content,scheduledBy:actor.id},minutes]);await audit(tx,actor.id,'ANNOUNCEMENT_SCHEDULED',id,{channelId,minutes});return {id};});await recordDiscordAudit({key:'scheduled-planned:'+result.id,kind:'ANNOUNCEMENT_PLANNED',actorId:actor.id,actorName:actor.username,channelId,after:content,metadata:{details:minutes+' dakika sonra gönderilecek.'}});return result;}
export async function cancelScheduled(actor:FeatureActor,id:string,key:string){z.uuid().parse(id);return featureMutation(actor,key,async tx=>{const r=await tx.query("UPDATE community_deliveries SET status='CANCELLED',last_error='CANCELLED' WHERE id=$1 AND guild_id=$2 AND payload->>'scheduledBy'=$3 AND status='QUEUED' RETURNING id",[id,config().guildId,actor.id]);if(!r.rows.length)throw new DomainError('SCHEDULE_CLOSED','Bu duyuru sana ait değil veya gönderim başlamış.');return {id};});}
export async function scheduledList(userId:string){return (await database().query("SELECT id,payload,available_at FROM community_deliveries WHERE guild_id=$1 AND kind='ANNOUNCEMENT' AND payload->>'scheduledBy'=$2 AND status='QUEUED' ORDER BY available_at LIMIT 20",[config().guildId,userId])).rows;}
export async function birthdayMaintenance(settings:CommunitySettings){const s=settings.expansion;if(!s.enabled||!s.birthdays.enabled||!s.birthdays.channelId)return;const now=new Date(Date.now()+10800000),day=now.getUTCDate(),month=now.getUTCMonth()+1,year=now.getUTCFullYear();if(now.getUTCHours()<9)return;const people=(await database().query('SELECT m.user_id,u.username FROM member_utilities m JOIN users u ON u.id=m.user_id WHERE m.guild_id=$1 AND m.birthday_day=$2 AND m.birthday_month=$3',[config().guildId,day,month])).rows;for(const p of people)await database().query("INSERT INTO community_deliveries(id,guild_id,kind,payload,dedupe_key) VALUES(gen_random_uuid(),$1,'SOCIAL',$2,$3) ON CONFLICT(dedupe_key) DO NOTHING",[config().guildId,{source:'BIRTHDAY',userId:p.user_id,channelId:s.birthdays.channelId,mentionUser:p.user_id,content:'İyi ki doğdun '+userTag(p.user_id)+'! 🎂 Yeni yaşında güzel günler dileriz.'},'birthday:'+config().guildId+':'+p.user_id+':'+year]);}
export async function expansionOverview(){const [rooms,registrations,scheduled]=await Promise.all([database().query('SELECT r.*,u.username FROM community_voice_rooms r JOIN users u ON u.id=r.owner_id WHERE r.guild_id=$1 ORDER BY created_at DESC LIMIT 50',[config().guildId]),database().query("SELECT staff_id,count(*)::int AS n FROM community_registrations WHERE guild_id=$1 AND status='DONE' GROUP BY staff_id ORDER BY n DESC LIMIT 20",[config().guildId]),database().query("SELECT id,payload,available_at,status FROM community_deliveries WHERE guild_id=$1 AND kind='ANNOUNCEMENT' AND payload ? 'scheduledBy' ORDER BY created_at DESC LIMIT 20",[config().guildId])]);return {rooms:rooms.rows,registrations:registrations.rows,scheduled:scheduled.rows};}
export async function createAdvancedEvent(actor:FeatureActor,input:unknown){ownerOnly(actor);const data=z.object({title:z.string().trim().min(1).max(100),channelId:snowflake,minutes:z.number().int().min(5).max(43200),requestId:z.uuid(),options:eventOptionsSchema}).parse(input),settings=await communitySettings();if(!settings.features.enabled||!settings.features.community)throw new DomainError('EVENT_DISABLED','Etkinlik modülü kapalı.');if(settings.features.channelIds.length&&!settings.features.channelIds.includes(data.channelId))throw new DomainError('FEATURE_CHANNEL','Bu kanalda topluluk araçları açık değil.');if(inspectContent(data.title+' '+data.options.description,settings.security.content))throw new DomainError('CONTENT_RULE','Metin sohbet korumasına takıldı.');const ch=await discordRequest('/channels/'+data.channelId);if(ch.guild_id!==config().guildId||![0,5].includes(ch.type))throw new DomainError('INVALID_CHANNEL','Bu sunucudan bir metin kanalı seç.');const r=await addFeatureRecord(actor,'EVENT',data.title,{...data.options,publishPending:true},{minutes:data.minutes,channelId:data.channelId},'event-panel:'+data.requestId);return {id:r.id,message:'Etkinlik kaydedildi. Katılım kartı seçilen kanala gönderilecek.'};}
export async function communityCalendar(){const rows=(await listFeatureRecords('EVENT',config().owners[0]||'',true,{limit:100})).filter(r=>r.status==='OPEN'&&r.due_at);const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const stamp=(d:string|Date)=>new Date(d).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//TurkishPix//Community Events//TR','CALSCALE:GREGORIAN',...rows.flatMap(r=>['BEGIN:VEVENT','UID:'+r.id+'@turkishpix','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(r.due_at!), 'SUMMARY:'+escape(r.title),'DESCRIPTION:'+escape(r.payload.description||''),'URL:https://discord.com/channels/'+r.guild_id+'/'+r.channel_id+'/'+r.message_id,'END:VEVENT']),'END:VCALENDAR',''].join('\r\n');}
