import {randomUUID,randomInt,createHash} from 'node:crypto';
import {z} from 'zod';
import {config,DomainError} from './config';
import {database,transaction,type DB} from './db';
import {syncUser} from './discord';
import {audit} from './audit';
import {rateLimit} from './auth';
import {brightEmbed,userTag,theme} from './presentation';
import {featureCommands,shopItems} from './features-catalog';
import type {FeatureSettings} from './features-policy';
export type FeatureActor={id:string;username:string;avatar?:string|null};
export type FeatureKind='REMINDER'|'NOTE'|'TASK'|'GIVEAWAY'|'EVENT'|'SUGGESTION'|'TICKET'|'WARNING'|'ROLE_MENU'|'FAQ';
export type FeatureRecord={id:string;guild_id:string;owner_id:string;kind:FeatureKind;title:string;payload:any;channel_id:string|null;message_id:string|null;due_at:string|null;status:string;created_at:string;participants?:number;message_revision?:string};
const uuid=z.uuid(),snowflake=z.string().regex(/^\d{17,20}$/);
const categories:Record<string,keyof FeatureSettings>={ekonomi:'economy',planlama:'planner',topluluk:'community',yonetim:'moderation',rehber:'resources'};
export function checkFeature(settings:FeatureSettings,name:string,channelId:string){const command=featureCommands.find(c=>c.name===name);if(!command||!settings.enabled||settings.disabledCommands.includes(name)||!settings[categories[command.category]])throw new DomainError('FEATURE_DISABLED','Bu özellik owner ayarlarından kapatılmış.',403);if(settings.channelIds.length&&!settings.channelIds.includes(channelId))throw new DomainError('FEATURE_CHANNEL','Bu kanalda yeni topluluk araçları açık değil.',403);}
export async function featureRate(actor:FeatureActor){await rateLimit('features:'+config().guildId+':'+actor.id,15,60);}
export async function featureMutation<T>(actor:FeatureActor,key:string,work:(tx:DB)=>Promise<T>,lockUsers:string[]=[]):Promise<T>{
 if(config().demo)throw new DomainError('DEMO_READONLY','Önizlemede kayıt değiştirilemez.',403);
 if(!key||key.length>180)throw new DomainError('FEATURE_KEY','İşlem kodu geçersiz.');snowflake.parse(actor.id);
 const receiptKey=actor.id+':'+key;return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['feature-receipt:'+config().guildId+':'+receiptKey]);for(const id of [...new Set(lockUsers)].sort())await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['profile:'+config().guildId+':'+id]);const old=(await tx.query('SELECT result FROM feature_receipts WHERE guild_id=$1 AND interaction_id=$2',[config().guildId,receiptKey])).rows[0];if(old)return (old.result?.__recordId?await getFeatureRecord(old.result.__recordId,tx):old.result) as T;await syncUser(tx,actor);const result=await work(tx);await tx.query('INSERT INTO feature_receipts(guild_id,interaction_id,result) VALUES($1,$2,$3)',[config().guildId,receiptKey,JSON.stringify((result as any)?.guild_id==config().guildId&&(result as any)?.kind?{__recordId:(result as any).id}:result??null)]);return result;});
}
async function ensureProfile(tx:DB,actor:FeatureActor){await syncUser(tx,actor);await tx.query('INSERT INTO member_profiles(guild_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[config().guildId,actor.id]);}
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function levelInfo(xp:number){const level=Math.floor(Math.sqrt(Math.max(0,xp)/100)),start=level*level*100,end=(level+1)*(level+1)*100;return {level,start,end,remaining:end-xp,percent:Math.floor((xp-start)/(end-start)*100)};}
export async function memberProfile(userId:string){snowflake.parse(userId);const row=(await database().query('SELECT p.*,u.username FROM member_profiles p JOIN users u ON u.id=p.user_id WHERE p.guild_id=$1 AND p.user_id=$2',[config().guildId,userId])).rows[0]||{user_id:userId,xp:0,coins:0,messages:0,reputation:0,streak:0,inventory:[]};return {...row,...levelInfo(row.xp)};}
export async function xpLeaderboard(){return (await database().query('SELECT p.user_id,p.xp,u.username FROM member_profiles p JOIN users u ON u.id=p.user_id WHERE p.guild_id=$1 ORDER BY p.xp DESC,p.user_id LIMIT 10',[config().guildId])).rows;}
export async function memberRank(userId:string){
 const p=await memberProfile(userId);
 const result=(await database().query('WITH ranked AS (SELECT user_id,row_number() OVER (ORDER BY xp DESC,user_id) AS place FROM member_profiles WHERE guild_id=$1 AND xp>0) SELECT (SELECT place FROM ranked WHERE user_id=$2)::int AS rank,(SELECT count(*) FROM ranked)::int AS ranked_members',[config().guildId,userId])).rows[0];
 return {...p,rank:result.rank??null,rankedMembers:result.ranked_members,voice_minutes:p.voice_minutes||0};
}
export function memberBadges(profile:any){return [...(profile.level>=10?['🏛️ Sohbet ustası']:profile.level>=5?['✨ Aktif üye']:[]),...(profile.messages>=100?['💬 100 sohbet katkısı']:[]),...(profile.reputation>=10?['🤝 Yardımsever']:[]),...(profile.streak>=7?['🔥 7 günlük seri']:[]),...shopItems.filter(x=>(profile.inventory||[]).includes(x.id)).map(x=>x.name)];}
export async function awardChatXP(actor:FeatureActor,text:string,settings:FeatureSettings,channelId:string){
 if(!settings.enabled||!settings.economy||!settings.xpEnabled||(settings.channelIds.length&&!settings.channelIds.includes(channelId))||text.replace(/\s/g,'').length<8)return false;
 const hash=createHash('sha256').update(text.normalize('NFKC').trim().toLocaleLowerCase('tr-TR')).digest('hex'),today=day();
 return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['profile:'+config().guildId+':'+actor.id]);await ensureProfile(tx,actor);const result=await tx.query(`UPDATE member_profiles SET xp=xp+$3,messages=messages+1,last_chat_channel_id=$8,last_xp_at=now(),last_content_hash=$4,xp_day=$5,xp_today=CASE WHEN xp_day=$5 THEN xp_today+$3 ELSE $3 END WHERE guild_id=$1 AND user_id=$2 AND (last_xp_at IS NULL OR last_xp_at<=now()-$6*interval '1 second') AND (last_content_hash IS NULL OR last_content_hash<>$4) AND (xp_day IS DISTINCT FROM $5::date OR xp_today+$3<=$7) RETURNING xp`,[config().guildId,actor.id,settings.xpPerMessage,hash,today,settings.xpCooldownSeconds,settings.xpDailyCap,channelId]);if(result.rows.length)await queueLevelUp(tx,actor.id,result.rows[0].xp,settings.xpPerMessage,settings,settings.levelUpChannel||channelId);return !!result.rows.length;});
}
export async function queueLevelUp(tx:DB,userId:string,xp:number,gain:number,settings:FeatureSettings,channelId?:string|null){
 const level=levelInfo(xp).level;if(!settings.levelUpEnabled||!channelId||level<=levelInfo(xp-gain).level)return;
 await tx.query("INSERT INTO level_up_notifications(guild_id,user_id,channel_id,level,xp) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guild_id,user_id,level) DO NOTHING",[config().guildId,userId,channelId,level,xp]);
}
export async function claimDaily(actor:FeatureActor,settings:FeatureSettings,key:string){return featureMutation(actor,key,async tx=>{await ensureProfile(tx,actor);const p=(await tx.query('SELECT * FROM member_profiles WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[config().guildId,actor.id])).rows[0];const today=day(),old=p.daily_date?new Date(p.daily_date).toISOString().slice(0,10):null;if(old===today)throw new DomainError('DAILY_CLAIMED','Bugünkü ödülünü aldın. Türkiye saatiyle gece yarısı yenilenir.',429);const yesterday=new Date(today+'T00:00:00Z');yesterday.setUTCDate(yesterday.getUTCDate()-1);const streak=old===yesterday.toISOString().slice(0,10)?p.streak+1:1,reward=settings.dailyReward+Math.min(streak-1,6)*10,credited=Math.min(reward,1000000-p.coins);await tx.query('UPDATE member_profiles SET coins=coins+$3,daily_date=$4,streak=$5 WHERE guild_id=$1 AND user_id=$2',[config().guildId,actor.id,credited,today,streak]);await audit(tx,actor.id,'FEATURE_DAILY',actor.id,{reward:credited,streak});return {reward:credited,streak,coins:p.coins+credited};},[actor.id]);}
export async function transferCoins(actor:FeatureActor,target:FeatureActor,amount:number,key:string){snowflake.parse(target.id);z.number().int().min(1).max(10000).parse(amount);if(actor.id===target.id)throw new DomainError('SELF_TRANSFER','Başka bir sunucu üyesi seç.');return featureMutation(actor,key,async tx=>{for(const id of [actor.id,target.id].sort())await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['profile:'+config().guildId+':'+id]);await ensureProfile(tx,actor);await ensureProfile(tx,target);const a=(await tx.query('SELECT coins FROM member_profiles WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[config().guildId,actor.id])).rows[0],b=(await tx.query('SELECT coins FROM member_profiles WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[config().guildId,target.id])).rows[0];if(a.coins<amount)throw new DomainError('NO_COINS','Sanal bakiyen yetersiz. /gunluk ile ödül alabilirsin.');if(b.coins+amount>1000000)throw new DomainError('WALLET_FULL','Alıcının sanal cüzdanı dolu.');await tx.query('UPDATE member_profiles SET coins=coins-$3 WHERE guild_id=$1 AND user_id=$2',[config().guildId,actor.id,amount]);await tx.query('UPDATE member_profiles SET coins=coins+$3 WHERE guild_id=$1 AND user_id=$2',[config().guildId,target.id,amount]);await audit(tx,actor.id,'FEATURE_TRANSFER',target.id,{amount});return {amount,coins:a.coins-amount};},[actor.id,target.id]);}
export async function purchaseBadge(actor:FeatureActor,itemId:string,key:string){const item=shopItems.find(x=>x.id===itemId);if(!item)throw new DomainError('ITEM_UNKNOWN','Ürün kodunu /magaza listesinden seç.');return featureMutation(actor,key,async tx=>{await ensureProfile(tx,actor);const p=(await tx.query('SELECT * FROM member_profiles WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[config().guildId,actor.id])).rows[0];if(p.inventory.includes(item.id))throw new DomainError('ALREADY_OWNED','Bu rozet zaten envanterinde.');if(p.coins<item.price)throw new DomainError('NO_COINS','Bu rozet için sanal bakiyen yetersiz.');await tx.query('UPDATE member_profiles SET coins=coins-$3,inventory=$4 WHERE guild_id=$1 AND user_id=$2',[config().guildId,actor.id,item.price,[...p.inventory,item.id]]);await audit(tx,actor.id,'FEATURE_PURCHASE',actor.id,{item:item.id,price:item.price});return {item,coins:p.coins-item.price};},[actor.id]);}
export async function giveReputation(actor:FeatureActor,target:FeatureActor,key:string){if(actor.id===target.id)throw new DomainError('SELF_REPUTATION','Teşekkür için başka bir üyeyi seç.');return featureMutation(actor,key,async tx=>{await ensureProfile(tx,target);const result=await tx.query('INSERT INTO member_reputation(guild_id,giver_id,receiver_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING receiver_id',[config().guildId,actor.id,target.id]);if(!result.rows.length)throw new DomainError('REPUTATION_COOLDOWN','Günde bir üyeye teşekkür puanı verebilirsin.',429);await tx.query('UPDATE member_profiles SET reputation=reputation+1 WHERE guild_id=$1 AND user_id=$2',[config().guildId,target.id]);await audit(tx,actor.id,'FEATURE_REPUTATION',target.id);return {userId:target.id};},[actor.id,target.id]);}
export async function addFeatureRecord(actor:FeatureActor,kind:FeatureKind,title:string,payload:any,options:{minutes?:number;channelId?:string},key:string){
 z.enum(['REMINDER','NOTE','TASK','GIVEAWAY','EVENT','SUGGESTION','TICKET','WARNING','ROLE_MENU','FAQ']).parse(kind);title=z.string().trim().min(1).max(kind==='NOTE'?1000:kind==='TASK'?500:kind==='REMINDER'?500:kind==='SUGGESTION'?600:200).parse(title);if(options.minutes!==undefined)z.number().int().min(1).max(43200).parse(options.minutes);if(options.channelId)snowflake.parse(options.channelId);if(JSON.stringify(payload).length>3000)throw new DomainError('FEATURE_PAYLOAD','Kayıt boyutu çok büyük.');
 return featureMutation(actor,key,async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['feature-create:'+config().guildId+':'+kind+':'+actor.id]);const cap={NOTE:50,TASK:50,REMINDER:25,TICKET:5,GIVEAWAY:10,EVENT:10,ROLE_MENU:30,FAQ:100,SUGGESTION:10,WARNING:500}[kind];if((await tx.query("SELECT count(*)::int AS n FROM feature_records WHERE guild_id=$1 AND owner_id=$2 AND kind=$3 AND status='OPEN'",[config().guildId,actor.id,kind])).rows[0].n>=cap)throw new DomainError('FEATURE_CAP','Bu türde açık kayıt sınırına ulaştın. Eski kayıtlarını kapat.');const id=randomUUID(),record=(await tx.query('INSERT INTO feature_records(id,guild_id,owner_id,kind,title,payload,channel_id,due_at) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $8::int IS NULL THEN NULL ELSE now()+$8*interval \'1 minute\' END) RETURNING *',[id,config().guildId,actor.id,kind,title,payload,options.channelId||null,options.minutes||null])).rows[0];await audit(tx,actor.id,'FEATURE_CREATED',id,{kind});if(['WARNING','TICKET'].includes(kind)&&config().logChannel)await tx.query("INSERT INTO community_deliveries(id,guild_id,kind,payload,dedupe_key) VALUES(gen_random_uuid(),$1,'SECURITY_LOG',$2,$3) ON CONFLICT(dedupe_key) DO NOTHING",[config().guildId,{channelId:config().logChannel,embeds:[brightEmbed(kind==='WARNING'?'🛡️ Yetkili uyarısı':'🎫 Yeni destek talebi',kind==='WARNING'?userTag(payload.userId)+' için uyarı kaydedildi.':'**Özel bir destek talebi açıldı.**',[{name:'👤 İşlemi yapan',value:userTag(actor.id)},{name:'🔗 Ayrıntılar',value:'[Yetkili panelini aç]('+config().appUrl+'/topluluk)'}],theme.gold)]},'feature-log:'+id]);return record as FeatureRecord;});
}
export async function getFeatureRecord(id:string,tx:DB=database(),lock=false):Promise<FeatureRecord>{uuid.parse(id);const row=(await tx.query('SELECT *,updated_at::text AS message_revision FROM feature_records WHERE id=$1 AND guild_id=$2'+(lock?' FOR UPDATE':''),[id,config().guildId])).rows[0];if(!row)throw new DomainError('FEATURE_NOT_FOUND','Bu kayıt bulunamadı.');return row as FeatureRecord;}
export async function acknowledgeFeatureMessage(r:FeatureRecord,missing=false,tx:DB=database()){
 // Keep PostgreSQL's microseconds intact; JS Date rounding would leave every card dirty.
 await tx.query("UPDATE feature_records SET discord_updated_at=$2::timestamptz,payload=CASE WHEN $5 THEN payload||'{\"discordMessageMissing\":true}'::jsonb ELSE payload END WHERE id=$1 AND guild_id=$6 AND channel_id=$3 AND message_id=$4",[r.id,r.message_revision,r.channel_id,r.message_id,missing,config().guildId]);
}
export async function listFeatureRecords(kind:FeatureKind,userId:string,staff=false,options:{limit?:number;offset?:number}={}):Promise<FeatureRecord[]>{const privateKind=['NOTE','TASK','REMINDER'].includes(kind),filter=kind==='WARNING'?' AND payload->>\'userId\'=$3':privateKind||kind==='TICKET'&&!staff?' AND owner_id=$3':'';const params:any[]=filter?[config().guildId,kind,userId]:[config().guildId,kind];const limit=Math.max(1,Math.min(100,options.limit||25)),offset=Math.max(0,Math.min(10000,options.offset||0));params.push(limit,offset);return (await database().query(`SELECT r.*,(SELECT count(*)::int FROM feature_participants p WHERE p.record_id=r.id AND p.choice='GOING') AS participants FROM feature_records r WHERE guild_id=$1 AND kind=$2 ${filter} AND status<>'CANCELLED' ORDER BY created_at DESC,id LIMIT $${params.length-1} OFFSET $${params.length}`,params)).rows as FeatureRecord[];}

export async function updateFeatureRecord(actor:FeatureActor,id:string,status:string,staff:boolean,key:string){z.enum(['DONE','CLOSED','CANCELLED','APPROVED','REJECTED']).parse(status);return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);const personal=['NOTE','TASK','REMINDER'].includes(r.kind),staffOnly=['SUGGESTION','WARNING','ROLE_MENU','FAQ'].includes(r.kind);if(personal?r.owner_id!==actor.id:staffOnly?!staff:!staff&&r.owner_id!==actor.id)throw new DomainError('FORBIDDEN','Bu kaydı değiştirme yetkin yok.',403);if(r.status!=='OPEN')throw new DomainError('FEATURE_CLOSED','Kayıt zaten tamamlanmış veya kapatılmış.');const updated=(await tx.query('UPDATE feature_records SET status=$3,updated_at=now() WHERE id=$1 AND guild_id=$2 RETURNING *',[id,config().guildId,status])).rows[0];await audit(tx,actor.id,'FEATURE_STATUS',id,{kind:r.kind,status});return updated as FeatureRecord;});}
export async function attachFeatureMessage(id:string,channelId:string,messageId:string){uuid.parse(id);snowflake.parse(channelId);snowflake.parse(messageId);await database().query("UPDATE feature_records SET channel_id=$2,message_id=$3,updated_at=now(),discord_updated_at=now(),payload=payload-'discordMessageMissing' WHERE id=$1 AND guild_id=$4",[id,channelId,messageId,config().guildId]);}
export async function participateFeature(actor:FeatureActor,id:string,key:string){const record=await getFeatureRecord(id);if(record.kind==='EVENT')return (await import('./expansion')).eventRSVP(actor,id,'TOGGLE',[],key);return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(!['GIVEAWAY','EVENT','SUGGESTION'].includes(r.kind)||r.status!=='OPEN'||r.due_at&&new Date(r.due_at).getTime()<=Date.now())throw new DomainError('FEATURE_CLOSED','Bu kayıt artık katılıma açık değil.');const joined=!!(await tx.query('SELECT user_id FROM feature_participants WHERE record_id=$1 AND user_id=$2',[id,actor.id])).rows.length;if(joined&&r.kind==='EVENT')await tx.query('DELETE FROM feature_participants WHERE record_id=$1 AND user_id=$2',[id,actor.id]);else if(!joined)await tx.query('INSERT INTO feature_participants(record_id,user_id) VALUES($1,$2)',[id,actor.id]);await tx.query('UPDATE feature_records SET updated_at=now() WHERE id=$1',[id]);const count=(await tx.query('SELECT count(*)::int AS n FROM feature_participants WHERE record_id=$1',[id])).rows[0].n;return {joined:r.kind==='EVENT'?!joined:true,count,record:r};});}
export function drawGiveawayWinners(pool:string[],count:number){const remaining=[...new Set(pool)],winners:string[]=[];const wanted=z.number().int().min(1).max(10).parse(count);while(winners.length<wanted&&remaining.length)winners.push(remaining.splice(randomInt(remaining.length),1)[0]);return winners;}
export async function finishGiveaway(actor:FeatureActor,id:string,staff:boolean,key:string){return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(r.kind!=='GIVEAWAY')throw new DomainError('FEATURE_KIND','Bu kod bir çekilişe ait değil.');if(!staff&&r.owner_id!==actor.id)throw new DomainError('FORBIDDEN','Çekilişi yalnızca organizatör veya yetkili sonuçlandırabilir.',403);if(r.status==='DONE')return r;if(r.status!=='OPEN')throw new DomainError('FEATURE_CLOSED','Çekiliş iptal edilmiş.');const users=(await tx.query('SELECT user_id FROM feature_participants WHERE record_id=$1 ORDER BY user_id',[id])).rows;const winners=drawGiveawayWinners(users.map(x=>x.user_id),r.payload.winnerCount||1);const payload={...r.payload,winners,winner:winners[0]||null,entries:users.length,drawNumber:1};const row=(await tx.query("UPDATE feature_records SET status='DONE',payload=$2,updated_at=now() WHERE id=$1 RETURNING *",[id,payload])).rows[0];await audit(tx,actor.id,'GIVEAWAY_FINISHED',id,{entries:users.length,winner:payload.winner});return row as FeatureRecord;});}
export async function featureOverview(){const g=config().guildId;const [counts,records,profiles]=await Promise.all([database().query("SELECT kind,status,count(*)::int AS n FROM feature_records WHERE guild_id=$1 AND kind NOT IN ('NOTE','TASK','REMINDER') GROUP BY kind,status",[g]),database().query("SELECT r.*,u.username,(SELECT count(*)::int FROM feature_participants p WHERE p.record_id=r.id AND p.choice='GOING') AS participants FROM feature_records r JOIN users u ON u.id=r.owner_id WHERE guild_id=$1 AND kind IN ('TICKET','SUGGESTION','EVENT','GIVEAWAY','FAQ','ROLE_MENU','WARNING') ORDER BY r.created_at DESC LIMIT 60",[g]),xpLeaderboard()]);return {counts:counts.rows,records:records.rows,leaderboard:profiles};}
export async function cleanupFeatures(){await database().query("DELETE FROM feature_receipts WHERE created_at<now()-interval '90 days'");await database().query("DELETE FROM feature_records WHERE guild_id=$1 AND kind IN ('REMINDER','TICKET','NOTE','TASK') AND status IN ('DONE','CLOSED','CANCELLED') AND (kind<>'TICKET' OR payload->>'privateChannel' IS DISTINCT FROM 'true') AND updated_at<now()-interval '30 days'",[config().guildId]);}
