import {z} from 'zod';
import {createHash} from 'node:crypto';
import {config,DomainError} from './config';
import {database,transaction} from './db';
import {discordRequest} from './discord';
import {listBotChannels} from './setup';
import {inspectContent} from './moderation-engine';
import {communitySettings} from './community';
import {addFeatureRecord,checkFeature,featureMutation,finishGiveaway,getFeatureRecord,updateFeatureRecord,type FeatureActor,type FeatureRecord} from './features';
import {audit} from './audit';
import {brightEmbed,displayText,userTag,theme} from './presentation';
export function giveawayRequestId(key:string){const h=createHash('sha256').update(config().guildId+':giveaway:'+key).digest('hex');return h.slice(0,8)+'-'+h.slice(8,12)+'-4'+h.slice(13,16)+'-a'+h.slice(17,20)+'-'+h.slice(20,32);}
export const giveawayCreateSchema=z.object({title:z.string().trim().min(1).max(200),channelId:z.string().regex(/^\d{17,20}$/),minutes:z.number().int().min(5).max(10080),winnerCount:z.number().int().min(1).max(10).default(1),requestId:z.uuid()});
export function giveawayMessage(r:FeatureRecord,count=0){const winners=r.payload.winners||(r.payload.winner?[r.payload.winner]:[]),description=displayText(r.title,900)+(r.status==='DONE'?`\n\n🏆 Kazananlar: ${winners.length?winners.map(userTag).join(', '):'Katılımcı yok'}\n${r.payload.entries||0} katılım. ${r.payload.drawNumber>1?'Yeniden seçim #'+r.payload.drawNumber:''}`:r.status!=='OPEN'?'\n\n🚫 Çekiliş iptal edildi.':`\n\n🎁 ${r.payload.winnerCount||1} kazanan · ${count} katılım\nBitiş: <t:${Math.floor(new Date(r.due_at!).getTime()/1000)}:R>\nÜcretsiz katılmak için düğmeye bas.`)+'\nÖdül teslimi organizatöre aittir.';return {embeds:[brightEmbed('🎁 TurkishPix · Çekiliş',description,[{name:'Organizatör',value:userTag(r.owner_id)}],theme.gold)],components:r.status==='OPEN'?[{type:1,components:[{type:2,style:1,custom_id:`feature:${r.id}:join`,label:'Çekilişe katıl',emoji:{name:'🎁'}}]}]:[],allowed_mentions:{parse:[]}};}
export async function publishGiveaway(id:string){return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['giveaway-message:'+id]);const r=await getFeatureRecord(id,tx,true);if(r.kind!=='GIVEAWAY'||!r.channel_id)throw new DomainError('GIVEAWAY_CHANNEL','Çekiliş kanalı bulunamadı.');const count=(await tx.query('SELECT count(*)::int AS n FROM feature_participants WHERE record_id=$1',[id])).rows[0].n,view=giveawayMessage(r,count);let messageId=r.message_id;if(messageId)await discordRequest(`/channels/${r.channel_id}/messages/${messageId}`,{method:'PATCH',body:JSON.stringify(view)});else {const nonce=r.id.replaceAll('-','').slice(0,24),self=await discordRequest('/users/@me'),messages=await discordRequest(`/channels/${r.channel_id}/messages?limit=50`);messageId=messages.find((m:any)=>m.author?.id===self.id&&m.nonce===nonce)?.id;if(!messageId)messageId=(await discordRequest(`/channels/${r.channel_id}/messages`,{method:'POST',body:JSON.stringify({...view,nonce,enforce_nonce:true})})).id;}await tx.query('UPDATE feature_records SET message_id=$2,discord_updated_at=updated_at WHERE id=$1',[id,messageId]);return {...r,message_id:messageId} as FeatureRecord;});}
export async function createGiveaway(actor:FeatureActor,input:unknown){const data=giveawayCreateSchema.parse(input),settings=await communitySettings();checkFeature(settings.features,'cekilis',data.channelId);if(inspectContent(data.title,settings.security.content))throw new DomainError('CONTENT_RULE','Ödül açıklaması sohbet korumasına takıldı.');const directory=await listBotChannels(),channel=directory.channels.find(c=>c.id===data.channelId&&[0,5].includes(c.type));if(!channel?.checks.view||!channel.checks.send||!channel.checks.embed||!channel.checks.history)throw new DomainError('GIVEAWAY_PERMISSION','Botun okuyabildiği ve mesaj/embed gönderebildiği bir metin kanalı seçin.');const record=await addFeatureRecord(actor,'GIVEAWAY',data.title,{winnerCount:data.winnerCount},{channelId:data.channelId,minutes:data.minutes},'giveaway:'+data.requestId);return publishGiveaway(record.id);}
export async function rerollGiveaway(actor:FeatureActor,id:string,staff:boolean,key:string){return featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(r.kind!=='GIVEAWAY'||r.status!=='DONE')throw new DomainError('GIVEAWAY_NOT_DONE','Yalnızca tamamlanmış çekilişte yeniden seçim yapılabilir.');if(!staff&&r.owner_id!==actor.id)throw new DomainError('FORBIDDEN','Bu çekilişi yönetemezsin.',403);const old=r.payload.winners||(r.payload.winner?[r.payload.winner]:[]),rows=(await tx.query('SELECT user_id FROM feature_participants WHERE record_id=$1 ORDER BY user_id',[id])).rows;const {drawGiveawayWinners}=await import('./features');const winners=drawGiveawayWinners(rows.map(x=>x.user_id).filter(id=>!old.includes(id)),r.payload.winnerCount||1);if(!winners.length)throw new DomainError('GIVEAWAY_NO_ALTERNATIVE','Önceki kazananlar dışında katılımcı yok.');const payload={...r.payload,winners,winner:winners[0],previousWinners:old,drawNumber:(r.payload.drawNumber||1)+1};const updated=(await tx.query('UPDATE feature_records SET payload=$2,updated_at=now() WHERE id=$1 RETURNING *',[id,payload])).rows[0];await audit(tx,actor.id,'GIVEAWAY_REROLLED',id,{winners,drawNumber:payload.drawNumber});return updated as FeatureRecord;});}
export async function manageGiveaway(actor:FeatureActor,id:string,action:'end'|'cancel'|'reroll',staff:boolean,key:string){const before=await getFeatureRecord(id);if(before.kind!=='GIVEAWAY')throw new DomainError('GIVEAWAY_KIND','Bir çekiliş seçin.');const r=action==='end'?await finishGiveaway(actor,id,staff,key):action==='reroll'?await rerollGiveaway(actor,id,staff,key):await updateFeatureRecord(actor,id,'CANCELLED',staff,key);if(r.kind!=='GIVEAWAY')throw new DomainError('GIVEAWAY_KIND','Bir çekiliş seçin.');return publishGiveaway(r.id);}
export async function giveawayTick(){const rows=(await database().query("SELECT id FROM feature_records WHERE guild_id=$1 AND kind='GIVEAWAY' AND message_id IS NULL AND channel_id IS NOT NULL ORDER BY created_at LIMIT 5",[config().guildId])).rows;for(const r of rows)try{await publishGiveaway(r.id);}catch{console.error('GIVEAWAY_PUBLISH_PENDING');}}
