import {z} from 'zod';
export const musicSettingsSchema=z.object({enabled:z.boolean().default(true),channelIds:z.array(z.string().regex(/^\d{17,20}$/)).max(50).default([]),djRoleIds:z.array(z.string().regex(/^\d{17,20}$/)).max(20).default([]),defaultVolume:z.number().int().min(1).max(100).default(35),maxQueue:z.number().int().min(5).max(100).default(50),perUserLimit:z.number().int().min(1).max(20).default(5),idleSeconds:z.number().int().min(30).max(1800).default(120),emptySeconds:z.number().int().min(15).max(600).default(30),maxTrackMinutes:z.number().int().min(5).max(240).default(60),voteSkipRatio:z.number().min(0.3).max(1).default(0.5)});
export const defaultMusicSettings=()=>musicSettingsSchema.parse({});
export const radioStations=[{id:'chill',name:'Groove Salad · Chill',url:'https://ice2.somafm.com/groovesalad-128-mp3'},{id:'lofi',name:'DEF CON · Elektronik',url:'https://ice2.somafm.com/defcon-128-mp3'},{id:'ambient',name:'Drone Zone · Ambient',url:'https://ice2.somafm.com/dronezone-128-mp3'},{id:'jazz',name:'Sonic Universe · Caz',url:'https://ice2.somafm.com/sonicuniverse-128-mp3'},{id:'pop',name:'PopTron · Pop',url:'https://ice2.somafm.com/poptron-128-mp3'},{id:'rock',name:'Indie Pop Rocks · Indie',url:'https://ice2.somafm.com/indiepop-128-mp3'}];
const string=(name:string,description:string,extra:any={})=>({name,description,type:3,...extra});
const number=(name:string,description:string,min:number,max:number)=>({name,description,type:4,required:true,min_value:min,max_value:max});
const sub=(name:string,description:string,options:any[]=[])=>({name,description,type:1,...(options.length?{options}:{})});
export const musicCommands=[{name:'ses',description:'Botu ses kanalına bağla, ayır veya bağlantıyı kontrol et.',options:[sub('katil','Bulunduğun ses kanalına katıl.'),sub('ayril','Müziği durdur ve kanaldan ayrıl.'),sub('durum','Ses bağlantısını ve izinlerini göster.')]},
 {name:'muzik',description:'Müzik, radyo ve ortak dinleme kuyruğunu yönet.',options:[
 sub('oynat','HTTPS ses bağlantısını veya yüklediğin ses dosyasını oynat.',[string('baglanti','Doğrudan MP3, OGG, WAV veya radyo bağlantısı',{max_length:1500}),{name:'dosya',description:'Ses dosyası yükle',type:11},string('baslik','Parça başlığı',{max_length:120})]),
 sub('radyo','Hazır radyo istasyonunu dinle.',[string('istasyon','İstasyon seç',{required:true,choices:radioStations.map(r=>({name:r.name,value:r.id}))})]),
 sub('duraklat','Çalan parçayı duraklat.'),sub('devam','Duraklatılan müziği sürdür.'),sub('atla','DJ veya parçayı ekleyen üye sıradakine geçer.'),sub('oyla','Dinleyiciler parçayı atlamak için oy verir.'),sub('durdur','Müziği durdur ve kuyruğu boşalt.'),sub('kuyruk','Sıradaki parçaları göster.'),sub('simdi','Çalan parçayı ve süreyi göster.'),
 sub('ses','Ses düzeyini ayarla.',[number('yuzde','1–100 arası ses düzeyi',1,100)]),sub('tekrar','Tek parçayı veya bütün kuyruğu tekrarla.',[string('mod','Tekrar modu',{required:true,choices:[{name:'Kapalı',value:'OFF'},{name:'Parça',value:'TRACK'},{name:'Kuyruk',value:'QUEUE'}]})]),sub('karistir','Bekleyen parçaları karıştır.'),sub('temizle','Bekleyen parçaları temizle.'),sub('cikar','Kuyruktan bir parça çıkar.',[number('sira','Kuyruktaki sıra',1,100)]),sub('tasi','Bekleyen parçanın sırasını değiştir.',[number('sira','Taşınacak sıra',1,100),number('hedef','Yeni sıra',1,100)]),sub('ileri','Çalan dosyada belirli saniyeye git.',[number('saniye','Başlangıçtan itibaren saniye',0,14400)]),sub('yardim','Müzik komutları ve desteklenen kaynakları göster.')]}];
export type MusicTrack={id:string;url:string;title:string;requesterId:string;radio:boolean};
export class MusicQueue{
 tracks:MusicTrack[]=[];current:MusicTrack|null=null;repeat:'OFF'|'TRACK'|'QUEUE'='OFF';volume:number;votes=new Set<string>();
 constructor(public policy:z.infer<typeof musicSettingsSchema>){this.volume=policy.defaultVolume;}
 add(track:MusicTrack){if(this.tracks.length+(this.current?1:0)>=this.policy.maxQueue)throw Error('Kuyruk dolu.');if([...this.tracks,...(this.current?[this.current]:[])].filter(t=>t.requesterId===track.requesterId).length>=this.policy.perUserLimit)throw Error('Kendi parça sınırına ulaştın.');this.tracks.push(track);}
 advance(skipped=false){if(this.current&&!skipped){if(this.repeat==='TRACK'){this.votes.clear();return this.current;}if(this.repeat==='QUEUE')this.tracks.push(this.current);}this.current=this.tracks.shift()||null;this.votes.clear();return this.current;}
 stop(){this.current=null;this.tracks=[];this.votes.clear();}
 remove(index:number){if(index<1||index>this.tracks.length)throw Error('Bu sırada parça yok.');return this.tracks.splice(index-1,1)[0];}
 move(from:number,to:number){if(to<1||to>this.tracks.length)throw Error('Hedef sıra geçersiz.');const track=this.remove(from);this.tracks.splice(to-1,0,track);}
 shuffle(random=Math.random){for(let i=this.tracks.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[this.tracks[i],this.tracks[j]]=[this.tracks[j],this.tracks[i]];}}
 vote(userId:string,listeners:string[]){this.votes=new Set([...this.votes].filter(id=>listeners.includes(id)));if(!listeners.includes(userId))throw Error('Oylamak için aynı ses kanalına katıl.');this.votes.add(userId);const required=Math.max(1,Math.ceil(listeners.length*this.policy.voteSkipRatio));return {votes:this.votes.size,required,skip:this.votes.size>=required};}
}
