import {config} from './config';
import {categoryForTitle,type CardCategory} from './visuals';
/** Shared Discord presentation. Mentions render as links; callers disable notifications. */
export const categoryBannerURL=(category:CardCategory)=>config().appUrl+'/api/cards/banner/'+category+'?v=2.11.0';
export const theme={cyan:0x35e2ff,gold:0xffca55,green:0x38e8a5,red:0xff557a,purple:0xbd80ff};
export function displayText(value:string,max=1000){return value.replace(/@/g,'＠').replace(/[\\*_~`|<>]/g,'\\$&').slice(0,max);}
const snowflake=(id:string)=>/^\d{17,20}$/.test(id);
export const userTag=(id:string,name='Üye')=>snowflake(id)?`<@${id}>`:displayText(name,80);
export const channelTag=(id:string)=>snowflake(id)?`<#${id}>`:'Kanal bilgisi yok';
export const roleTag=(id:string)=>snowflake(id)?`<@&${id}>`:'Rol bilgisi yok';
export function brightEmbed(title:string,description='',fields:any[]=[],color=theme.cyan){return {author:{name:'𝙏𝙪𝙧𝙠𝙞𝙨𝙝𝙋𝙞𝙭  ◆  TOPLULUK'},title:title.slice(0,256),description:description.slice(0,4000)||undefined,color,image:{url:categoryBannerURL(categoryForTitle(title))},fields:fields.slice(0,25).map(f=>({...f,name:f.name.slice(0,256),value:String(f.value||'—').slice(0,1024)})),footer:{text:'✦ TurkishPix  ·  /yardim ile keşfet'},timestamp:new Date().toISOString()};}
export function actionLabel(action:string){const map:Record<string,string>={MESSAGE_DELETED:'🗑️ Mesaj silindi',NATIVE_BLOCKED:'⛔ Gönderim engellendi',REVIEW_ONLY:'🔎 İncelemeye alındı',DELETE_PERMISSION_MISSING:'⚠️ Silme izni eksik',PERMISSION_MISSING:'⚠️ Bot izni eksik',DELETE_FAILED:'⚠️ Mesaj silinemedi',ALERT_ONLY:'📣 Yetkililere bildirildi',TIMEOUT:'🔇 Süreli susturma uygulandı',ALREADY_TIMED_OUT:'🔇 Mevcut susturma korundu',TIMEOUT_PERMISSION_MISSING:'⚠️ Susturma izni / rol sırası yetersiz',TIMEOUT_FAILED:'⚠️ Susturma uygulanamadı'};return action.split(' + ').map(x=>map[x]||displayText(x,100)).join('\n');}
export function securityEmbed(input:{userId:string;username:string;channelId?:string|null;rule:string;action:string;source?:string;hits?:number;caseId?:string;roleIds?:string[];avatarUrl?:string;appName?:string},panelUrl:string){const review=input.action==='REVIEW_ONLY',embed:any=brightEmbed(review?'🔎 Sohbet incelemesi':'🛡️ Sohbet koruması',review?'**Bir yetkilinin değerlendirmesi bekleniyor.**':'**Sunucu kuralı uygulandı.**',[{name:input.appName?'👤 Tetikleyen üye':'👤 Üye',value:userTag(input.userId,input.username),inline:true},{name:'💬 Kanal',value:channelTag(input.channelId||''),inline:true},{name:'🛡️ Kural',value:displayText(input.rule),inline:true},{name:'⚡ İşlem',value:actionLabel(input.action)},{name:'📡 Kaynak',value:input.source||'TurkishPix koruması',inline:true},...(input.hits===undefined?[]:[{name:'📊 Son ihlaller',value:`**${input.hits}** kayıt`,inline:true}]),...(input.roleIds?.length?[{name:'🎭 Üyenin rolleri',value:input.roleIds.slice(0,6).map(roleTag).join(' ')}]:[]),...(input.appName?[{name:'🤖 Uygulama',value:displayText(input.appName,120),inline:true}]:[]),{name:'🔗 Yönetim',value:`[Koruma panelini aç](${panelUrl}/guvenlik)`}],review?theme.gold:input.action.includes('TIMEOUT')?theme.red:theme.cyan);embed.footer={text:'TurkishPix • '+(input.caseId?'Kayıt '+input.caseId.slice(0,8):'Sunucu güvenliği')};if(input.avatarUrl)embed.thumbnail={url:input.avatarUrl};return embed;}
