// Public release notes shared by the website and Discord. Keep this module browser-safe.
export type ReleaseFeature={title:string;description:string;commands:string[];path:string;note?:string};
export type Release={version:string;date:string;title:string;summary:string;features:ReleaseFeature[]};
export const releases:Release[]=[
 {version:'2.14.1',date:'2026-10-09',title:'Otorol düzeltmesi & çoklu XP ödülleri',summary:'Normal üye rolleri kabul edilir; 50 seviye–rol kuralı ve kalıcı XP rol kuyruğu.',features:[
  {title:'Normal üye ve rütbe rolleri',description:'Etkinlik oluşturma, emoji oluşturma, kanal erişimi ve mesaj gönderme izinleri olan normal roller otorol, kayıt, emoji ve düğmeli rol sisteminde kullanılabilir. Hatalar artık seçilen rolün gerçek sorununu belirtir.',commands:['/topluluk roller panel','/topluluk roller otorol rol: @Üye','/rolmenu'],path:'/topluluk',note:'Rolleri Yönet izni gerekir; TurkishPix rolü verilen rollerin üstünde olmalı. Discord tarafından yönetilen ve yönetim/moderasyon yetkili roller otomatik verilmez.'},
  {title:'Birden fazla XP ödülü',description:'Discord ekranından 1–100 seviyeleri için toplam 50 kural ekle. Aynı seviyede birden fazla rol seç; önceki eşleşmeler korunur. Listeyi sayfalarla gez, tek bir kuralı kaldır veya hak edilenleri tara. Sitedeki ödül satırlarının seviyeleri de düzenlenebilir.',commands:['/topluluk roller seviye-panel','/topluluk roller seviye-ekle seviye: 5 rol: @Aktif','/topluluk roller seviye-ekle seviye: 10 rol: @Kıdemli','/topluluk roller seviye-sil seviye: 5 rol: @Aktif'],path:'/topluluk'},
  {title:'Eksik XP rollerini tamamla',description:'Sohbet ve ses XP’sinden kazanılan roller kalıcı iş kuyruğuna girer. Geçici hatalar tekrar denenir; düzenli üye taraması geçmiş seviyelerdeki eksik rolleri tamamlar. Silinen kuralların eski işleri iptal edilir, kazanılmış roller korunur.',commands:['/topluluk roller seviye-tara','/botpanel'],path:'/topluluk'}
 ]},
 {version:'2.14.0',date:'2026-10-09',title:'Discord kontrol merkezi & otomatik roller',summary:'Denetim kayıtları, bot giriş engeli, toplu rol, emoji rolü ve gerçek sunucu tagı otomasyonu.',features:[
  {title:'Discord içinde yönetim',description:'Yeni /botpanel; modül menüsü, özel kayıt ekranı, kategori filtreleri, kanal ve rol seçicileri, güvenlik düğmeleri ve kişisel ayar kartlarıyla açılır.',commands:['/botpanel'],path:'/topluluk'},
  {title:'Ayrıntılı denetim kaydı',description:'Mesajın yazarı, yeni ve eski içerik, silinen mesaj, engellenen içerik, duyuru yazarı, üye, rol, kanal ve bot işlemleri kaydedilir. Ayrıntılar yalnızca yetkililere görünür. Kategori kanalları, hariç kanallar ve 7 / 30 / 90 gün saklama seçilebilir.',commands:['/topluluk denetim kur','/topluluk denetim panel','/topluluk denetim kayitlar'],path:'/topluluk',note:'Botun görmediği eski mesaj içeriği bilinmiyor diye gösterilir. Silen kişi yalnızca Discord açıkça bildirdiğinde bilinir.'},
  {title:'Yeni bot giriş engeli',description:'Yeni katılan yabancı botlar otomatik çıkarılır. TurkishPix kendi hesabını korur; izinli bot listesi ve aç / kapat seçenekleri sunucu sahibi ve yöneticilere açıktır.',commands:['/topluluk botkoruma ac','/topluluk botkoruma kapat','/topluluk botkoruma izinver bot: @İzinliBot'],path:'/topluluk',note:'Üyeleri At izni ve hedef botun üstünde rol gerekir.'},
  {title:'Yeni üyeye otomatik rol',description:'Rol seçicisinden on role kadar belirle. Yeni insan üyeler doğrulamayı tamamlayınca rolleri verilir; mevcut üyeler de taranır. Botlar atlanır, diğer roller korunur ve başarısız işler tekrar denenir.',commands:['/topluluk roller panel','/topluluk roller otorol rol: @Üye','/topluluk roller otorol-kapat'],path:'/topluluk'},
  {title:'Herkese rol dağıtımı',description:'Mevcut insan üyelere seçilen rol, sayfalı üye taraması ve kalıcı kuyrukla dağıtılır. Önizleme, başlatma, ilerleme ve durdurma düğmeleri vardır. Yeniden başlatma kaldığı yerden sürer.',commands:['/topluluk roller herkese rol: @Üye','/topluluk roller toplu-durum'],path:'/topluluk'},
  {title:'Emojiye bas, rolünü al',description:'Kalıcı emoji rol mesajı oluştur. Üye tepki ekleyince rolü alır, tepkisini kaldırınca rolü bırakır. Unicode ve sunucudaki özel emojiler kullanılabilir; mesaj kapatıldığında mevcut roller korunur.',commands:['/topluluk roller emoji rol: @Oyuncu emoji: 🎮','/topluluk roller emoji-kapat mesaj: MesajID'],path:'/topluluk'},
  {title:'Gerçek Discord sunucu tagı',description:'Bu sunucunun profil tagını kullanan üyeye seçilen rol verilir. Tagı kaldırınca veya başka sunucu tagı seçince rol alınır. İsimdeki benzer metin kabul edilmez; bilinmeyen kimlik nedeniyle rol silinmez.',commands:['/topluluk roller tag rol: @Taglı','/topluluk roller tag-tara','/topluluk roller tag-kapat'],path:'/topluluk',note:'Düzenli kontrol döngüsü 5 dakikadır; büyük sunucularda tarama süresi eklenir. Rolleri Yönet izni ve uygun rol sırası gerekir.'}
 ]},
 {version:'2.13.0',date:'2026-10-09',title:'Dokuz oyun, Discord turları & oda rehberi',summary:'Altı yeni oyun; üçü Discord’da da oynanır. Giriş yapmadan ücretsiz dene.',features:[
  {title:'Daha büyük oyun salonu',description:'Neon Yılan, Tuğla Kıran, Uzay Savunması, 2048, Mayın Tarlası ve Dörtlü Bağla eklendi. Mobil kontroller, özgün oyun kartları, güçlendirmeler ve bölüm sonu savaşlarıyla dokuz oyun.',commands:['/topluluk oyun salon','/topluluk oyun salon oyun: Uzay Savunması'],path:'/oyunlar'},
  {title:'Discord mesajında oyna',description:'2048, Mayın Tarlası ve Dörtlü Bağla mesajdaki düğmelerle oynanır. Kurallar bot tarafından uygulanır. Başlat düğmesi bir kez 100 / 100 / 150 Bot TL düşer; oyunlar 12 dakika geçerlidir.',commands:['/topluluk oyun 2048','/topluluk oyun mayin','/topluluk oyun dortlu'],path:'/oyunlar',note:'Gerçek zamanlı 2D / 3D oyunlar komuttaki bağlantıyla tarayıcıda açılır.'},
  {title:'Ücretsiz deneme',description:'Dokuz oyunun tamamını Discord girişi ve Bot TL harcamadan dene. Deneme skorları geçmişe yazılmaz. Kayıtlı turlar aynı cüzdandan ücret alır.',commands:['/topluluk oyun salon'],path:'/oyunlar'},
  {title:'Özel oda nasıl çalışır?',description:'➕・Oda Oluştur kanalına katılınca kendi geçici ses odan açılır. Kilitle, davet et ve kapasiteyi ayarla. Bot ve site artık adım adım kullanım rehberi gösterir.',commands:['/topluluk oda yardim','/topluluk oda kur kategori: Ses Kanalları','/topluluk oda kilitle','/topluluk oda davet uye: @Arkadaş'],path:'/oyunlar',note:'Botun sunucuda bulunması, Kanalları Yönet ve Üyeleri Taşı izinleri gerekir.'}
 ]},
 {version:'2.12.0',date:'2026-10-09',title:'Güncellemeler merkezi',summary:'Botta ve sitede nelerin değiştiğini tek yerden keşfet.',features:[
  {title:'Sürüm notları ve yeni komutlar',description:'Yeni özellikler, kullanım örnekleri, sürüm tarihleri ve ilgili panel bağlantıları artık aynı katalogdan gösterilir. Önceki sürümleri de seçebilirsin.',commands:['/guncellemeler','/guncellemeler surum: 2.11.0','/yardim'],path:'/guncellemeler'},
  {title:'Komut rehberi bir arada',description:'50 topluluk özelliğinin rehberi /yardim içindeki kategorilerde. Ayrı /ozellikler rehberi bu menüde birleştirildi; özellikler kullanılmaya devam eder.',commands:['/yardim'],path:'/topluluk'},
  {title:'Bağlantı kontrolü',description:'Güncellemeler sayfasında web sürümünü, bot bağlantısını ve yeni komutların kayıt durumunu görebilirsin.',commands:['/guncellemeler'],path:'/guncellemeler'}
 ]},
 {version:'2.11.1',date:'2026-10-09',title:'Sunucu bağlantısı kontrolü',summary:'Botun yapılandırılmış sunucu üyeliği kontrol edilir.',features:[{title:'Bağlantıyı yeniden doğrula',description:'Gateway sunucuyu yükleyemezse bot üyeliği, rolleri ve kanalları REST üzerinden doğrular. Bot sunucuda bulunmuyorsa üye gerektiren işlemler bekletilir.',commands:['/guncellemeler'],path:'/guncellemeler',note:'Bot sunucudan çıkarılmışsa yeniden eklenmesi gerekir.'}]},
 {version:'2.11.0',date:'2026-10-09',title:'2D & 3D oyun salonu',summary:'Üç tarayıcı oyunu ve topluluğa tek seferlik Bot TL hediyesi.',features:[
  {title:'Neon Kaçış · 2D',description:'Engellerden kaç ve yıldızları topla. Tur başına giriş 100 Bot TL; klavye ve dokunmatik kontrol desteklenir.',commands:['/yardim'],path:'/oyunlar'},
  {title:'Hafıza Bahçesi · 2D',description:'Kartları eşleştir ve hafızanı dene. Tur başına giriş 150 Bot TL.',commands:['/yardim'],path:'/oyunlar'},
  {title:'Yörünge · 3D',description:'WebGL ile üç boyutlu oyun. Tur başına giriş 200 Bot TL. Oyun salonuna Discord hesabınla giriş yap.',commands:['/cuzdan'],path:'/oyunlar',note:'3D oyun için tarayıcında WebGL desteği gerekir.'},
  {title:'50.000 Bot TL topluluk hediyesi',description:'Kampanyaya alınan mevcut insan üyelerin bakiyesine bir kez 50.000 Bot TL eklenir. Kalıcı ödeme kayıtları aynı hediyenin yeniden verilmesini önler.',commands:['/cuzdan','/transfer'],path:'/oyunlar',note:'Hediye ödeme durumu botun sunucu bağlantısına bağlıdır; bu not ödeme yapıldığının teyidi değildir.'}
 ]},
 {version:'2.10.1',date:'2026-10-09',title:'Seviye bildirimi düzeltmesi',summary:'Canlı veritabanındaki seviye bildirimi kurulumu tamamlandı.',features:[
  {title:'Kalıcı seviye bildirimleri',description:'Seviye duyuruları için gereken veritabanı kurulumu tüm başlatma yollarına eklendi. Yeniden başlatma sırasında bekleyen bildirimler korunur.',commands:['/rank','/seviye'],path:'/topluluk'}
 ]},
 {version:'2.10.0',date:'2026-10-09',title:'Topluluk odaları & seviye kutlamaları',summary:'Katılınca oluşan kişisel ses odaları ve fotoğraflı seviye duyuruları.',features:[
  {title:'Katılınca ses odası oluştur',description:'Yetkili oda giriş kanalını kurar. Üye bu kanala girince kişisel odası açılır ve oraya taşınır. Boş odalar otomatik temizlenir.',commands:['/topluluk oda kur','/topluluk oda ac','/topluluk oda liste'],path:'/topluluk',note:'Botun Kanalları Yönet ve Üyeleri Taşı izinleri gerekir.'},
  {title:'Odanı yönet',description:'Odayı kilitle, aç, adını veya kapasitesini değiştir; üye davet et, çıkar, sahipliği devret veya kapat.',commands:['/topluluk oda kilitle','/topluluk oda kilitac','/topluluk oda ad ad: Sohbet','/topluluk oda limit adet: 5','/topluluk oda davet uye: @Üye','/topluluk oda devret uye: @Üye'],path:'/topluluk'},
  {title:'Fotoğraflı seviye atlama mesajı',description:'Üye seviye atlayınca etiketlenir ve profil fotoğraflı seviye kartı gönderilir. Duyuru kanalını Topluluk araçları → Seviye & Ödül ayarlarından seçebilirsin.',commands:['/rank','/siralama'],path:'/topluluk',note:'Seviye duyurusunu aç; botun seçilen kanalda Mesaj Gönder, Bağlantıları Yerleştir ve Dosya Ekle izinlerini kontrol et.'}
 ]},
 {version:'2.9.0',date:'2026-10-09',title:'YouTube arama & rank kartları',summary:'Şarkı seçimi, ortak izleme ve sunucu sıralamalı profil kartları.',features:[
  {title:'YouTube’da ara ve seç',description:'Müzik menüsünden arama formunu aç, şarkıyı yaz ve çıkan sonuçlardan seç. Video görselleri ve favori araçları eklendi.',commands:['/muzik oynat ara: Şarkı adı','/muzik ekran'],path:'/muzik',note:'YouTube araması yapılandırılmış API anahtarı gerektirir. Ses oynatma kaynak erişimine bağlıdır.'},
  {title:'Birlikte izle',description:'Ses kanalında Watch Together oturumu açarak YouTube videolarını birlikte izleyin.',commands:['/muzik ekran'],path:'/muzik',note:'Botun Davet Oluştur izni gerekir; ortak izleme Discord etkinliği üzerinden açılır.'},
  {title:'Fotoğraflı /rank',description:'Profil fotoğrafı, seviye, sunucu sırası, mesaj ve ses XP’si ile sonraki seviyeye ilerlemeyi tek kartta gösterir.',commands:['/rank uye: @Üye','/seviye','/siralama'],path:'/topluluk'}
 ]},
 {version:'2.8.0',date:'2026-10-09',title:'Gelişmiş topluluk araçları',summary:'Kayıt, rol otomasyonu, ses XP’si ve etkinlik yönetimi.',features:[
  {title:'Kayıt ve özel komutlar',description:'Üye kaydı, rol otomasyonu ve sunucuya özel yanıt komutları; owner panelinde kanalları ve rolleri adlarıyla seç.',commands:['/topluluk kayit onayla','/topluluk kayit bilgi','/topluluk ozel liste'],path:'/topluluk'},
  {title:'Etkinlikler ve aktiflik',description:'AFK, doğum günleri, ses XP’si, seviye rolleri, tekrarlanan etkinlikler, katılım kapasitesi ve zamanlı duyurular eklendi.',commands:['/topluluk'],path:'/topluluk'}
 ]}
];
export const currentRelease=releases[0];
export function findRelease(version:string){return releases.find(release=>release.version===version);}
export function releaseMatches(release:Release,query:string){const search=query.trim().toLocaleLowerCase('tr-TR');return !search||[release.version,release.title,release.summary,...release.features.flatMap(f=>[f.title,f.description,...f.commands])].join(' ').toLocaleLowerCase('tr-TR').includes(search);}
