import {randomUUID} from 'node:crypto';
import {config,DomainError} from './config';
import {database,transaction} from './db';
import {communitySettings} from './community';
import {audit} from './audit';
import {roleAutomationSchema,type RoleAutomationSettings} from './role-automation-policy';
export async function roleAutomationSettings():Promise<RoleAutomationSettings>{const row=(await database().query('SELECT settings FROM role_automation_settings WHERE guild_id=$1',[config().guildId])).rows[0];if(row)return roleAutomationSchema.parse(row.settings);const legacy=(await communitySettings()).expansion.autoRoleIds;return roleAutomationSchema.parse({autoEnabled:legacy.length>0,autoRoleIds:legacy});}
export async function saveRoleAutomation(actor:{id:string;username:string},input:Partial<RoleAutomationSettings>){const fallback=await roleAutomationSettings();const s=await transaction(async tx=>{
 await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['role-settings:'+config().guildId]);
 const row=(await tx.query('SELECT settings FROM role_automation_settings WHERE guild_id=$1 FOR UPDATE',[config().guildId])).rows[0];const s=roleAutomationSchema.parse({...row?.settings||fallback,...input});
 await tx.query('INSERT INTO role_automation_settings(guild_id,settings,updated_by) VALUES($1,$2,$3) ON CONFLICT(guild_id) DO UPDATE SET settings=EXCLUDED.settings,updated_by=EXCLUDED.updated_by,revision=role_automation_settings.revision+1,updated_at=now()',[config().guildId,s,actor.id]);
 // Keep the previous join handler in sync while the durable queue handles retries.
 await tx.query("UPDATE community_settings SET settings=jsonb_set(settings,'{expansion,autoRoleIds}',$2::jsonb),updated_at=now() WHERE guild_id=$1",[config().guildId,JSON.stringify(s.autoEnabled?s.autoRoleIds:[])]);
 await audit(tx,actor.id,'ROLE_AUTOMATION_SETTINGS_UPDATED',config().guildId,{settings:s});
 return s;});await requestRoleScan();return s;}
export async function queueRoleChange(userId:string,roleId:string,desired:boolean,source:'AUTO'|'TAG'|'REACTION'|'BULK',metadata:Record<string,any>={}){
 await transaction(async tx=>{
  if(source==='BULK'){const campaign=(await tx.query('SELECT status FROM role_bulk_campaigns WHERE id=$1 AND guild_id=$2 FOR UPDATE',[metadata.campaignId,config().guildId])).rows[0];if(!campaign||!['QUEUED','SCANNING'].includes(campaign.status))return;}
  await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['role-job:'+config().guildId+':'+userId+':'+roleId]);
  const old=(await tx.query('SELECT * FROM role_automation_jobs WHERE guild_id=$1 AND user_id=$2 AND role_id=$3 FOR UPDATE',[config().guildId,userId,roleId])).rows[0];
  if(old?.source==='BULK'&&['QUEUED','RUNNING'].includes(old.status)&&source==='AUTO'&&old.desired===desired)return;
  if(old?.source==='BULK'&&old.metadata.campaignId!==metadata.campaignId)await tx.query("UPDATE role_bulk_targets SET status='SKIPPED',last_error='SUPERSEDED' WHERE campaign_id=$1 AND user_id=$2 AND status='QUEUED'",[old.metadata.campaignId,userId]);
  if(source==='BULK')await tx.query("INSERT INTO role_bulk_targets(campaign_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[metadata.campaignId,userId]);
  await tx.query("INSERT INTO role_automation_jobs(guild_id,user_id,role_id,desired,source,metadata) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(guild_id,user_id,role_id) DO UPDATE SET desired=EXCLUDED.desired,source=EXCLUDED.source,metadata=EXCLUDED.metadata,revision=role_automation_jobs.revision+1,status='QUEUED',attempts=0,available_at=now(),updated_at=now() WHERE role_automation_jobs.desired<>EXCLUDED.desired OR role_automation_jobs.status IN ('DONE','SKIPPED','FAILED') OR role_automation_jobs.metadata<>EXCLUDED.metadata",[config().guildId,userId,roleId,desired,source,metadata]);
 });
}
export async function claimRoleChange(){return transaction(async tx=>(await tx.query("UPDATE role_automation_jobs SET status='RUNNING',attempts=attempts+1,updated_at=now() WHERE (guild_id,user_id,role_id)=(SELECT guild_id,user_id,role_id FROM role_automation_jobs WHERE guild_id=$1 AND ((status='QUEUED' AND available_at<=now()) OR (status='RUNNING' AND updated_at<now()-interval '1 minute')) ORDER BY available_at LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING *",[config().guildId])).rows[0]||null);}
export async function finishRoleChange(job:any,status:string,error:string|null=null){await transaction(async tx=>{const row=await tx.query("UPDATE role_automation_jobs SET status=$5,last_error=$6,available_at=now()+interval '30 seconds',updated_at=now() WHERE guild_id=$1 AND user_id=$2 AND role_id=$3 AND revision=$4 RETURNING user_id",[config().guildId,job.user_id,job.role_id,job.revision,status,error]);if(row.rows.length&&job.source==='BULK'&&status!=='QUEUED')await tx.query('UPDATE role_bulk_targets SET status=$3,last_error=$4 WHERE campaign_id=$1 AND user_id=$2',[job.metadata.campaignId,job.user_id,status,error]);});}
export async function createRoleBulk(actorId:string,roleId:string,estimated:number){const id=randomUUID();await database().query('INSERT INTO role_bulk_campaigns(id,guild_id,owner_id,role_id,estimated) VALUES($1,$2,$3,$4,$5)',[id,config().guildId,actorId,roleId,estimated]);return id;}
export async function activateRoleBulk(actorId:string,id:string){return transaction(async tx=>{const row=(await tx.query("UPDATE role_bulk_campaigns SET status='QUEUED',updated_at=now() WHERE id=$1 AND guild_id=$2 AND owner_id=$3 AND status='DRAFT' AND created_at>now()-interval '10 minutes' RETURNING *",[id,config().guildId,actorId])).rows[0];if(!row)throw new DomainError('BULK_EXPIRED','Bu dağıtım onayı kullanılmış veya süresi dolmuş. Komutu yeniden aç.');await audit(tx,actorId,'BULK_ROLE_STARTED',id,{roleId:row.role_id});return row;});}
export async function cancelRoleBulk(actorId:string,id:string){await transaction(async tx=>{const row=(await tx.query("UPDATE role_bulk_campaigns SET status='CANCELLED',updated_at=now() WHERE id=$1 AND guild_id=$2 AND owner_id=$3 AND status IN ('DRAFT','QUEUED','SCANNING','APPLYING') RETURNING id",[id,config().guildId,actorId])).rows[0];if(!row)throw new DomainError('BULK_CLOSED','Bu dağıtım sana ait değil veya artık kapalı.');await tx.query("UPDATE role_automation_jobs SET status='SKIPPED',revision=revision+1,last_error='BULK_CANCELLED' WHERE guild_id=$1 AND metadata->>'campaignId'=$2 AND status IN ('QUEUED','RUNNING')",[config().guildId,id]);await tx.query("UPDATE role_bulk_targets SET status='SKIPPED',last_error='BULK_CANCELLED' WHERE campaign_id=$1 AND status='QUEUED'",[id]);});}
export async function roleBulkStatus(){return (await database().query("SELECT c.*,count(j.user_id) FILTER(WHERE j.status='DONE')::int AS done,count(j.user_id) FILTER(WHERE j.status IN ('QUEUED','RUNNING'))::int AS pending,count(j.user_id) FILTER(WHERE j.status='FAILED')::int AS failed FROM role_bulk_campaigns c LEFT JOIN role_bulk_targets j ON j.campaign_id=c.id WHERE c.guild_id=$1 GROUP BY c.id ORDER BY c.created_at DESC LIMIT 5",[config().guildId])).rows;}
export async function reactionRolePanel(messageId:string,emojiKey:string){return (await database().query('SELECT * FROM role_reaction_panels WHERE guild_id=$1 AND message_id=$2 AND emoji_key=$3 AND active',[config().guildId,messageId,emojiKey])).rows[0]||null;}
export async function requestRoleScan(){await database().query("INSERT INTO role_scan_state(guild_id) VALUES($1) ON CONFLICT(guild_id) DO UPDATE SET cursor_id='0',next_scan=now(),revision=role_scan_state.revision+1,last_error=NULL,updated_at=now()",[config().guildId]);}
