import {z} from 'zod';
import {config,DomainError} from './config';
import {database,transaction} from './db';
import {discordRequest,syncUser} from './discord';
import {audit} from './audit';
import {ownerOnly} from './service';
import {effectiveChannelPermissions,listBotChannels} from './setup';
import {addFeatureRecord,getFeatureRecord,featureMutation,type FeatureActor,type FeatureRecord} from './features';
import {brightEmbed,displayText,userTag,roleTag,theme} from './presentation';
const snowflake=z.string().regex(/^\d{17,20}$/);
export const ticketSettingsSchema=z.object({enabled:z.boolean().default(true),channelId:snowflake,categoryId:snowflake,staffRoleIds:z.array(snowflake).min(1).max(5).transform(ids=>[...new Set(ids)]),title:z.string().trim().min(1).max(100).default('Destek merkezi'),description:z.string().trim().min(1).max(1000).default('Özel bir destek kanalı açmak için Bilet aç düğmesine bas.')});
export type TicketSettings=z.infer<typeof ticketSettingsSchema>;
export async function ticketSettings(){const row=(await database().query('SELECT * FROM ticket_settings WHERE guild_id=$1',[config().guildId])).rows[0];return row?{...row,settings:ticketSettingsSchema.parse(row.settings)}:null;}
async function directory(){const g=config().guildId,self=await discordRequest('/users/@me');const [roles,member,channels]=await Promise.all([discordRequest(`/guilds/${g}/roles`),discordRequest(`/guilds/${g}/members/${self.id}`),discordRequest(`/guilds/${g}/channels`)]);const base=roles.filter((r:any)=>r.id===g||member.roles.includes(r.id)).reduce((n:bigint,r:any)=>n|BigInt(r.permissions),0n);return {self,roles,member,channels,base};}
export async function ticketDirectory(actor:FeatureActor){ownerOnly(actor);const [d,c]=await Promise.all([directory(),listBotChannels()]);return {channels:c.channels,roles:d.roles.filter((r:any)=>r.id!==config().guildId&&!r.managed).map((r:any)=>({id:r.id,name:r.name,color:r.color}))};}
async function validateSettings(s:TicketSettings){const d=await directory(),g=config().guildId;const panel=d.channels.find((c:any)=>c.id===s.channelId&&[0,5].includes(c.type)),category=d.channels.find((c:any)=>c.id===s.categoryId&&c.type===4);if(!panel||!category)throw new DomainError('TICKET_CHANNEL','Bu sunucudan bilet paneli için metin kanalı ve bir kategori seçin.');const permissions=(c:any)=>effectiveChannelPermissions(d.base,d.member.roles,d.self.id,c,g);const required=1024n|2048n|16384n|65536n;if((permissions(panel)&required)!==required)throw new DomainError('TICKET_PERMISSION','Panel kanalında botun Görüntüle, Mesaj Gönder, Mesaj Geçmişini Oku ve Bağlantıları Yerleştir izinlerini açın.');if(!(d.base&8n)&&((d.base&(16n|268435456n|required))!==(16n|268435456n|required)||(permissions(category)&(16n|268435456n))!==(16n|268435456n)))throw new DomainError('TICKET_PERMISSION','Özel bilet kanalları için botun Kanalları Yönet ve Rolleri Yönet izinleri gerekli.');for(const id of s.staffRoleIds){const role=d.roles.find((r:any)=>r.id===id&&r.id!==g&&!r.managed);if(!role)throw new DomainError('TICKET_ROLE','Bu sunucudan yönetilmeyen bir yetkili rolü seçin.');if(!role.mentionable&&!(d.base&(8n|131072n)))throw new DomainError('TICKET_PING','Yetkili rolünü etiketlenebilir yapın veya bota Herkesten Bahset izni verin.');}return d;}
export async function configureTickets(actor:FeatureActor,input:unknown,staff=false){if(!staff)ownerOnly(actor);if(config().demo)throw new DomainError('DEMO_READONLY','Önizlemede bilet kurulamaz.',403);const s=ticketSettingsSchema.parse(input);await validateSettings(s);await transaction(async tx=>{await syncUser(tx,actor);await tx.query('INSERT INTO ticket_settings(guild_id,settings) VALUES($1,$2) ON CONFLICT(guild_id) DO UPDATE SET settings=EXCLUDED.settings,updated_at=now()',[config().guildId,s]);await audit(tx,actor.id,'TICKET_SETTINGS_UPDATED',config().guildId,{channelId:s.channelId,categoryId:s.categoryId,staffRoleIds:s.staffRoleIds});});await publishTicketPanel();return {message:s.enabled?'Bilet paneli seçilen kanalda hazır.':'Bilet açma kapatıldı.'};}
export async function publishTicketPanel(){return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['ticket-panel:'+config().guildId]);const row=(await tx.query('SELECT * FROM ticket_settings WHERE guild_id=$1 FOR UPDATE',[config().guildId])).rows[0];if(!row)return;const s=ticketSettingsSchema.parse(row.settings),nonce='ticket-'+new Date(row.updated_at).getTime(),view={embeds:[brightEmbed('🎫 '+displayText(s.title),displayText(s.description),[],theme.cyan)],components:[{type:1,components:[{type:2,style:1,custom_id:'ticket:open',label:'Bilet aç',emoji:{name:'🎫'},disabled:!s.enabled}]}],allowed_mentions:{parse:[]}};if(row.panel_message_id&&row.panel_channel_id!==s.channelId)await discordRequest(`/channels/${row.panel_channel_id}/messages/${row.panel_message_id}`,{method:'PATCH',body:JSON.stringify({components:[]})});let message;if(row.panel_message_id&&row.panel_channel_id===s.channelId){try{message=await discordRequest(`/channels/${s.channelId}/messages/${row.panel_message_id}`,{method:'PATCH',body:JSON.stringify(view)});}catch(e){if(!(e instanceof DomainError)||e.message.indexOf('(404)')<0)throw e;}}if(!message){const self=await discordRequest('/users/@me'),recent=await discordRequest(`/channels/${s.channelId}/messages?limit=50`);message=recent.find((m:any)=>m.author?.id===self.id&&m.nonce===nonce);if(!message)message=await discordRequest(`/channels/${s.channelId}/messages`,{method:'POST',body:JSON.stringify({...view,nonce,enforce_nonce:true})});}await tx.query('UPDATE ticket_settings SET panel_channel_id=$2,panel_message_id=$3,panel_updated_at=updated_at WHERE guild_id=$1',[config().guildId,s.channelId,message.id]);});}
export function ticketOverwrites(guildId:string,botId:string,requesterId:string,roleIds:string[],closed=false){const read=1024n|65536n,write=2048n|16384n;return [{id:guildId,type:0,allow:'0',deny:'1024'},{id:botId,type:1,allow:String(read|write|16n),deny:'0'},{id:requesterId,type:1,allow:String(read|(closed?0n:write)),deny:closed?String(write):'0'},...roleIds.map(id=>({id,type:0,allow:String(read|write),deny:'0'}))];}
export function ticketMessage(r:FeatureRecord){return {content:r.message_id?'':r.payload.staffRoleIds.map(roleTag).join(' ')+' · '+userTag(r.owner_id),embeds:[brightEmbed(r.status==='OPEN'?'🎫 '+displayText(r.title):'🔒 Bilet kapatıldı',displayText(r.payload.description||'',1000),[{name:'Talep sahibi',value:userTag(r.owner_id)},{name:'Yetkililer',value:r.payload.staffRoleIds.map(roleTag).join(' ')},{name:'Durum',value:r.status==='OPEN'?'Açık':'Kapalı'}],theme.cyan)],components:r.status==='OPEN'?[{type:1,components:[{type:2,style:4,custom_id:'ticket:close:'+r.id,label:'Bileti kapat'}]}]:[],allowed_mentions:r.message_id?{parse:[]}:{parse:[],roles:r.payload.staffRoleIds,users:[r.owner_id]},nonce:r.id.replaceAll('-','').slice(0,24),enforce_nonce:true};}
export async function materializeTicket(id:string){return transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['ticket-channel:'+id]);const r=await getFeatureRecord(id,tx,true);if(r.kind!=='TICKET'||!r.payload.privateChannel)return r;const d=await directory(),topic='turkishpix-ticket:'+r.id;let channel=r.channel_id?d.channels.find((c:any)=>c.id===r.channel_id):d.channels.find((c:any)=>c.topic===topic);if(!channel){if(r.status!=='OPEN')return r;await validateSettings({...r.payload.settings,enabled:true});channel=await discordRequest(`/guilds/${r.guild_id}/channels`,{method:'POST',body:JSON.stringify({name:'bilet-'+r.id.slice(0,8),type:0,parent_id:r.payload.settings.categoryId,topic,permission_overwrites:ticketOverwrites(r.guild_id,d.self.id,r.owner_id,r.payload.staffRoleIds)})});}r.channel_id=channel.id;if(r.status==='CLOSED')await discordRequest('/channels/'+channel.id,{method:'PATCH',body:JSON.stringify({permission_overwrites:ticketOverwrites(r.guild_id,d.self.id,r.owner_id,r.payload.staffRoleIds,true)})});let message=r.message_id;if(message)await discordRequest(`/channels/${channel.id}/messages/${message}`,{method:'PATCH',body:JSON.stringify(ticketMessage(r))});else {const existing=await discordRequest(`/channels/${channel.id}/messages?limit=50`);message=existing.find((m:any)=>m.author?.id===d.self.id&&m.nonce===r.id.replaceAll('-','').slice(0,24))?.id;if(!message)message=(await discordRequest(`/channels/${channel.id}/messages`,{method:'POST',body:JSON.stringify(ticketMessage(r))})).id;}await tx.query('UPDATE feature_records SET channel_id=$2,message_id=$3,discord_updated_at=updated_at WHERE id=$1',[id,channel.id,message]);return {...r,message_id:message} as FeatureRecord;});}
export async function openTicket(actor:FeatureActor,title:string,description:string,key:string){const row=await ticketSettings();if(!row?.settings.enabled)throw new DomainError('TICKETS_DISABLED','Bilet sistemi henüz kurulmamış veya kapalı.');title=z.string().trim().min(1).max(100).parse(title);description=z.string().trim().min(1).max(1000).parse(description);const member=await discordRequest(`/guilds/${config().guildId}/members/${actor.id}`);if(member.pending||member.user?.bot)throw new DomainError('NOT_MEMBER','Sunucu üyelik adımlarını tamamlayın.',403);await validateSettings(row.settings);const r=await addFeatureRecord(actor,'TICKET',title,{description,privateChannel:true,settings:row.settings,staffRoleIds:row.settings.staffRoleIds},{},key);return materializeTicket(r.id);}
export async function closeTicket(actor:FeatureActor,id:string,staff=false,key='close:'+id){const r=await featureMutation(actor,key,async tx=>{const r=await getFeatureRecord(id,tx,true);if(r.kind!=='TICKET')throw new DomainError('TICKET_KIND','Bu kayıt bilet değil.');if(!staff&&r.owner_id!==actor.id)throw new DomainError('FORBIDDEN','Bu bileti kapatamazsın.',403);await tx.query("UPDATE feature_records SET status='CLOSED',updated_at=now() WHERE id=$1",[id]);await audit(tx,actor.id,'TICKET_CLOSED',id);return {...r,status:'CLOSED'};});return materializeTicket(r.id);}
export async function ticketIsStaff(userId:string,r?:FeatureRecord){if(config().owners.includes(userId))return true;const member=await discordRequest(`/guilds/${config().guildId}/members/${userId}`);const s=r?.payload.staffRoleIds||(await ticketSettings())?.settings.staffRoleIds||[];return member.roles.some((id:string)=>s.includes(id));}
export async function ticketTick(){const panel=(await database().query('SELECT guild_id FROM ticket_settings WHERE guild_id=$1 AND (panel_updated_at IS NULL OR panel_updated_at<updated_at)',[config().guildId])).rows[0];if(panel)try{await publishTicketPanel();}catch{console.error('TICKET_PANEL_PENDING');}const pending=(await database().query("SELECT id FROM feature_records WHERE guild_id=$1 AND kind='TICKET' AND payload->>'privateChannel'='true' AND (discord_updated_at IS NULL OR discord_updated_at<updated_at) ORDER BY updated_at LIMIT 5",[config().guildId])).rows;for(const r of pending)try{await materializeTicket(r.id);}catch{console.error('TICKET_SYNC_PENDING');}}
