import {lookup} from 'node:dns/promises';
import {request} from 'node:https';
import type {IncomingMessage} from 'node:http';
export function publicIPv4(ip:string){const parts=ip.split('.').map(Number);if(parts.length!==4||parts.some(n=>!Number.isInteger(n)||n<0||n>255))return false;const [a,b,c]=parts;return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===168||b===0||b===2)||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19||b===51&&c===100)||a===203&&b===0&&c===113);}
export function audioURL(input:string){let url:URL;try{url=new URL(input);}catch{throw Error('Geçerli bir HTTPS ses bağlantısı gir.');}if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||url.hostname.endsWith('.')||url.href.length>1500)throw Error('Ses kaynağı kimlik bilgisi içermeyen bir HTTPS bağlantısı olmalı.');if(/(^|\.)(localhost|local|internal|home|lan)$/.test(url.hostname)||url.hostname.includes(':'))throw Error('Bu ses adresi kullanılamaz.');if(/(^|\.)(youtube\.com|youtu\.be|spotify\.com|soundcloud\.com)$/.test(url.hostname))throw Error('Bu sayfa bir ses akışı değil. MP3/OGG/WAV dosyası yükle, doğrudan ses bağlantısı veya /muzik radyo kullan.');url.hash='';return url;}
/** Pin each connection to a validated public DNS answer; revalidate redirects. */
export async function openAudio(input:string,redirects=0):Promise<IncomingMessage>{
 const url=audioURL(input);let addresses;try{addresses=await lookup(url.hostname,{all:true,family:4});}catch{throw Error('Ses kaynağının adresi çözümlenemedi. Başka kaynak veya radyo deneyin.');}if(!addresses.length||addresses.some(a=>!publicIPv4(a.address)))throw Error('Ses kaynağı herkese açık bir adres olmalı.');
 const stream=await new Promise<IncomingMessage>((resolve,reject)=>{const req=request(url,{headers:{'User-Agent':'TurkishPix/2.5','Accept':'audio/*,application/ogg'},lookup:((_host:any,_options:any,cb:any)=>_options?.all?cb(null,[{address:addresses[0].address,family:4}]):cb(null,addresses[0].address,4)) as any},resolve);req.once('error',reject);req.setTimeout(15000,()=>req.destroy(Error('Ses kaynağı yanıt vermedi.')));req.end();});
 if([301,302,303,307,308].includes(stream.statusCode||0)){stream.destroy();if(redirects>=3||!stream.headers.location)throw Error('Ses bağlantısı çok fazla yönlendirme içeriyor.');return openAudio(new URL(stream.headers.location,url).href,redirects+1);}
 if(stream.statusCode!==200){stream.destroy();throw Error('Ses kaynağına ulaşılamadı.');}
 const type=String(stream.headers['content-type']||'').toLowerCase().split(';')[0],size=Number(stream.headers['content-length']||0);if(!(type.startsWith('audio/')||type==='application/ogg'||type==='application/octet-stream'&&/\.(mp3|ogg|wav|flac|m4a|aac|webm)$/i.test(url.pathname))||size>100*1024*1024){stream.destroy();throw Error('Kaynak bir ses dosyası / akışı olmalı; dosya sınırı 100 MB.');}return stream;
}
