import {createMemberRoom,ensureVoiceRoomLobby} from './rooms';
import {RELEASE_VERSION} from '@turkishpix/core';
import {roomHelpText} from '@turkishpix/core';
import {ChannelType,MessageFlags,PermissionFlagsBits} from 'discord.js';
import {AUTOMATIC_ROLE_DANGER_MASK,roleMappings,config,DomainError,database,transaction,audit,syncUser,featureMutation,featureRate,brightEmbed,displayText,userTag,channelTag,theme,inspectContent,communitySettings,setAFK,clearAFK,mentionedAFK,setBirthday,birthdayCalendar,changeCustomCommand,customResponse,awardVoiceXP,memberProfile,expansionCommand,expansionUsageCount,eventAttendees,editEvent,listFeatureRecords,getFeatureRecord,scheduledAnnouncement,scheduledList,cancelScheduled,birthdayMaintenance,youtubeStatus,type CommunitySettings} from '@turkishpix/core';
async function optionalChannel(guild:any,id:string){try{return await guild.channels.fetch(id);}catch(e){if((e as any).code===10003)return null;throw e;}}
async function optionalMember(guild:any,id:string){try{return await guild.members.fetch(id);}catch(e){if((e as any).code===10007)return null;throw e;}}
const actorOf=(i:any)=>({id:i.user.id,username:i.user.username,avatar:i.user.avatar});
const screen=(title:string,description:string)=>({embeds:[brightEmbed(title,description.slice(0,3900),[],theme.purple)],allowedMentions:{parse:[],repliedUser:false}});
const permission=(i:any,value:bigint)=>{if(!i.memberPermissions?.has(value))throw new DomainError('FORBIDDEN','Bu işlem için gerekli Discord yetkin yok.',403);};
function checkText(text:string,settings:CommunitySettings){if(inspectContent(text,settings.security.content))throw new DomainError('CONTENT_RULE','Bu metin sohbet korumasına takıldı.');}
const safeRolePermissions=AUTOMATIC_ROLE_DANGER_MASK;
async function safeRole(guild:any,id:string,executor?:any){if(Object.values(await roleMappings()).includes(id))throw new DomainError('ROLE_PROTECTED','Meclis ve siyasi görev rolleri bu araçtan verilemez.',403);const channels=await guild.channels.fetch();if(channels.some((ch:any)=>ch.permissionOverwrites?.cache?.some((o:any)=>o.id===id&&(o.allow.bitfield&safeRolePermissions))))throw new DomainError('ROLE_NOT_SAFE','Rol kanal içinde yönetim yetkisi içeriyor.',403);const role=await guild.roles.fetch(id),bot=guild.members.me;if(!role||role.id===guild.id||role.managed||!role.editable||(role.permissions.bitfield&safeRolePermissions)||!bot?.permissions.has(PermissionFlagsBits.ManageRoles))throw new DomainError('ROLE_NOT_SAFE','Rol yönetim yetkisi içermemeli, entegrasyon rolü olmamalı ve botun altında olmalı.',403);if(executor&&executor.id!==guild.ownerId&&executor.roles.highest.comparePositionTo(role)<=0)throw new DomainError('ROLE_HIERARCHY','Rol senin en yüksek rolünün altında olmalı.',403);return role;}
async function moderatedMember(i:any,id:string){const member=await i.guild.members.fetch(id),executor=await i.guild.members.fetch(i.user.id);if(id===i.user.id||id===i.guild.ownerId||id===i.client?.user?.id||config().owners.includes(id)||member.user.bot||executor.id!==i.guild.ownerId&&executor.roles.highest.comparePositionTo(member.roles.highest)<=0)throw new DomainError('MEMBER_HIERARCHY','Kendine, owner hesaplarına veya eşit/üst role sahip üyeye işlem yapamazsın.',403);return member;}
async function roomCommand(i:any,sub:string,settings:CommunitySettings){
 const s=settings.expansion.rooms;if(sub==='yardim')return roomHelpText(s.emptySeconds);if(!s.enabled)throw new DomainError('ROOM_DISABLED','Özel oda sistemi kapalı.',403);const actor=actorOf(i),guild=i.guild;
 if(sub==='liste'){const rows=(await database().query('SELECT channel_id,owner_id FROM community_voice_rooms WHERE guild_id=$1 ORDER BY created_at DESC LIMIT 20',[guild.id])).rows;return rows.map(r=>channelTag(r.channel_id)+' · '+userTag(r.owner_id)).join('\n')||'Henüz özel oda yok. `/topluluk oda ac` ile ilk odanı oluştur.';}
 if(!guild.members.me?.permissions.has(PermissionFlagsBits.ManageChannels))throw new DomainError('BOT_PERMISSION','Botun Kanalları Yönet yetkisi gerekli.');
 if(sub==='kur'){permission(i,PermissionFlagsBits.ManageChannels);const category=i.options.getChannel('kategori');const lobby=await ensureVoiceRoomLobby(guild,{actor,categoryId:category?.id});return '➕ Oda oluştur kanalı hazır: '+channelTag(lobby!.id)+'\nBu ses kanalına katılan üyeye kendi odası açılır ve üye otomatik taşınır.';}
 if(sub==='ac'){
  const member=await guild.members.fetch(actor.id),name=i.options.getString('ad');if(name)checkText(name,settings);
  const result=await createMemberRoom(member,settings,i.id,name||undefined);
  if(member.voice.channelId&&member.movable)await member.voice.setChannel(result.id,'TurkishPix kendi odası').catch(()=>{});
  return (result.existing?'Zaten bir odan var: ':'Odan hazır: ')+channelTag(result.id)+'\nOda boş kalınca '+s.emptySeconds+' saniye içinde kapanır. Kilitlemek için `/topluluk oda kilitle` kullan.';
 }
 return featureMutation(actor,i.id,async tx=>{const row=(await tx.query('SELECT * FROM community_voice_rooms WHERE guild_id=$1 AND owner_id=$2 FOR UPDATE',[guild.id,actor.id])).rows[0];if(!row)throw new DomainError('ROOM_NOT_FOUND','Önce `/topluluk oda ac` ile kendi odanı oluştur.');const room=await guild.channels.fetch(row.channel_id);if(!room||room.type!==ChannelType.GuildVoice)throw new DomainError('ROOM_NOT_FOUND','Oda artık bulunamadı.');
  if(sub==='kapat'){await room.delete('Oda sahibi kapattı');await tx.query('DELETE FROM community_voice_rooms WHERE guild_id=$1 AND owner_id=$2',[guild.id,actor.id]);return 'Özel odan kapatıldı.';}
  if(sub==='kilitle'||sub==='kilitac'){if(sub==='kilitle'){const current=room.permissionOverwrites.cache.get(guild.id);if(!row.lock_snapshot)await tx.query('UPDATE community_voice_rooms SET lock_snapshot=$3 WHERE guild_id=$1 AND owner_id=$2',[guild.id,actor.id,{connect:current?.allow.has(PermissionFlagsBits.Connect)?true:current?.deny.has(PermissionFlagsBits.Connect)?false:null}]);await room.permissionOverwrites.edit(guild.id,{Connect:false});}else{if(!row.lock_snapshot)return 'Oda kilidi zaten açık.';await room.permissionOverwrites.edit(guild.id,{Connect:row.lock_snapshot.connect??null});await tx.query('UPDATE community_voice_rooms SET lock_snapshot=NULL WHERE guild_id=$1 AND owner_id=$2',[guild.id,actor.id]);}return sub==='kilitle'?'Oda yeni katılımlara kapatıldı. `/topluluk oda davet` ile üye ekleyebilirsin.':'Oda kilidi açıldı.';}
  if(sub==='ad'){const name=i.options.getString('ad',true);checkText(name,settings);await room.setName(displayText(name,60));return 'Oda adı güncellendi.';}
  if(sub==='limit'){await room.setUserLimit(i.options.getInteger('adet',true));return 'Oda kapasitesi güncellendi.';}
  const selected=i.options.getUser('uye',true),target=await guild.members.fetch(selected.id);if(target.user.bot||target.pending)throw new DomainError('ROOM_MEMBER','Doğrulanmış bir sunucu üyesi seç.');
  if(sub==='devret'){if(target.id===actor.id||target.voice.channelId!==room.id)throw new DomainError('ROOM_TRANSFER','Oda sahipliğini odada bulunan başka bir üyeye devret.');if((await tx.query('SELECT owner_id FROM community_voice_rooms WHERE guild_id=$1 AND owner_id=$2',[guild.id,target.id])).rows.length)throw new DomainError('ROOM_TRANSFER','Bu üyenin zaten bir odası var.');await syncUser(tx,{id:target.id,username:target.user.username});await room.permissionOverwrites.edit(target.id,{ViewChannel:true,Connect:true});await room.permissionOverwrites.delete(actor.id);await tx.query('UPDATE community_voice_rooms SET owner_id=$3 WHERE guild_id=$1 AND owner_id=$2',[guild.id,actor.id,target.id]);return 'Oda sahipliği '+userTag(target.id)+' üyesine devredildi.';}
  if(target.id===actor.id||target.id===guild.ownerId||config().owners.includes(target.id))throw new DomainError('ROOM_MEMBER','Oda sahibi veya sunucu owner hesabı çıkarılamaz.');
  if(sub==='davet'){await room.permissionOverwrites.edit(target.id,{ViewChannel:true,Connect:true});return userTag(target.id)+' için odaya giriş izni verildi.';}
  if(sub==='cikar'){await room.permissionOverwrites.edit(target.id,{Connect:false});if(target.voice.channelId===room.id){if(!target.movable)throw new DomainError('BOT_PERMISSION','Üye rolü botun üstünde veya botun Üyeleri Taşı yetkisi eksik.');await target.voice.disconnect('Özel oda sahibi çıkardı');}return userTag(target.id)+' odadan çıkarıldı.';}
  throw new DomainError('ROOM_ACTION','Oda işlemi bulunamadı.');
 });
}
async function registration(i:any,sub:string,settings:CommunitySettings){const s=settings.expansion.registration;if(!s.enabled)throw new DomainError('REGISTRATION_DISABLED','Kayıt sistemi kapalı.');const actor=actorOf(i);
 if(sub==='istatistik'){const rows=(await database().query("SELECT staff_id,count(*)::int AS n FROM community_registrations WHERE guild_id=$1 AND status='DONE' GROUP BY staff_id ORDER BY n DESC LIMIT 15",[i.guildId])).rows;return rows.map(r=>userTag(r.staff_id)+' · **'+r.n+'** kayıt').join('\n')||'Henüz kayıt yapılmadı.';}
 const user=i.options.getUser('uye')||i.user;if(sub==='bilgi'){const r=(await database().query("SELECT * FROM community_registrations WHERE guild_id=$1 AND user_id=$2 AND status='DONE'",[i.guildId,user.id])).rows[0];return r?userTag(user.id)+' kayıtlı.\nYetkili: '+userTag(r.staff_id)+' · <t:'+Math.floor(new Date(r.created_at).getTime()/1000)+':R>':userTag(user.id)+' için henüz kayıt yok.';}
 const staff=await i.guild.members.fetch(actor.id);if(!staff.permissions.has(PermissionFlagsBits.ManageRoles)&&!s.staffRoleIds.some(id=>staff.roles.cache.has(id)))throw new DomainError('FORBIDDEN','Kayıt yetkilisi rolü veya Rolleri Yönet izni gerekli.',403);
 if(!s.memberRoleId)throw new DomainError('REGISTRATION_SETUP','Owner, Topluluk panelinden kayıtlı üye rolünü seçmeli.');const member=await moderatedMember(i,user.id);if(member.pending)throw new DomainError('MEMBERSHIP_PENDING','Üye önce sunucu doğrulamasını tamamlamalı.');const role=await safeRole(i.guild,s.memberRoleId,staff);if(s.unregisteredRoleId)await safeRole(i.guild,s.unregisteredRoleId,staff);const name=i.options.getString('isim',true);checkText(name,settings);
 return featureMutation(actor,i.id,async tx=>{const previous=(await tx.query('SELECT status FROM community_registrations WHERE guild_id=$1 AND user_id=$2 FOR UPDATE',[i.guildId,user.id])).rows[0];if(previous?.status==='DONE')throw new DomainError('ALREADY_REGISTERED','Üye zaten kayıtlı.');await syncUser(tx,{id:user.id,username:user.username,avatar:user.avatar});await tx.query("INSERT INTO community_registrations(guild_id,user_id,staff_id,name,status) VALUES($1,$2,$3,$4,'PENDING') ON CONFLICT(guild_id,user_id) DO UPDATE SET staff_id=EXCLUDED.staff_id,name=EXCLUDED.name,status='PENDING'",[i.guildId,user.id,actor.id,name]);
  if(!member.manageable||!i.guild.members.me?.permissions.has(PermissionFlagsBits.ManageNicknames))throw new DomainError('BOT_PERMISSION','Botun üyenin adını değiştirme yetkisi eksik.');await member.setNickname(name,'TurkishPix kayıt');await member.roles.add(role,'TurkishPix kayıt onayı');if(s.unregisteredRoleId)await member.roles.remove(s.unregisteredRoleId,'TurkishPix kayıt tamamlandı');await tx.query("UPDATE community_registrations SET status='DONE' WHERE guild_id=$1 AND user_id=$2",[i.guildId,user.id]);await audit(tx,actor.id,'MEMBER_REGISTERED',user.id,{roleId:role.id});if(s.logChannelId)await tx.query("INSERT INTO community_deliveries(id,guild_id,kind,payload) VALUES(gen_random_uuid(),$1,'SECURITY_LOG',$2)",[i.guildId,{channelId:s.logChannelId,content:userTag(user.id)+' kaydedildi. Yetkili: '+userTag(actor.id)}]);return userTag(user.id)+' kaydı tamamlandı; üye rolü verildi.';
 });
}
async function moderation(i:any,sub:string,settings:CommunitySettings){
 if(sub==='roller')return (await i.guild.roles.fetch()).filter((r:any)=>r.id!==i.guildId).sort((a:any,b:any)=>b.position-a.position).first(30).map((r:any)=>'<@&'+r.id+'> · '+r.members.size+' üye').join('\n')||'Henüz rol yok.';
 const required:Record<string,bigint>={ban:PermissionFlagsBits.BanMembers,kick:PermissionFlagsBits.KickMembers,unban:PermissionFlagsBits.BanMembers,takmaad:PermissionFlagsBits.ManageNicknames,sustur:PermissionFlagsBits.ModerateMembers,susturmaac:PermissionFlagsBits.ModerateMembers,surelirol:PermissionFlagsBits.ManageRoles,sestasi:PermissionFlagsBits.MoveMembers};permission(i,required[sub]);
 if(!i.guild.members.me?.permissions.has(required[sub]))throw new DomainError('BOT_PERMISSION','Botta bu işlem için gerekli Discord izni eksik.');const actor=actorOf(i),reason=(i.options.getString('sebep')||'TurkishPix yetkili işlemi')+' · '+actor.username;
 if(sub==='unban'){const id=i.options.getString('kullanici',true);if(!/^\d{17,20}$/.test(id))throw new DomainError('INVALID_USER','Geçerli bir Discord kullanıcı ID’si gir.');return featureMutation(actor,i.id,async tx=>{await i.guild.members.unban(id,reason);await audit(tx,actor.id,'MEMBER_UNBANNED',id);return 'Kullanıcının sunucu yasağı kaldırıldı.';});}
 const target=i.options.getUser('uye',true),member=await moderatedMember(i,target.id);
 if(sub==='surelirol'){const grant=await featureMutation(actor,i.id,async tx=>{const role=await safeRole(i.guild,i.options.getRole('rol',true).id,await i.guild.members.fetch(actor.id));await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['role-lease:'+i.guildId+':'+target.id+':'+role.id]);const lease=(await tx.query("SELECT status FROM community_role_leases WHERE guild_id=$1 AND user_id=$2 AND role_id=$3 AND status<>'DONE' FOR UPDATE",[i.guildId,target.id,role.id])).rows[0];if(member.roles.cache.has(role.id)&&!lease)throw new DomainError('ROLE_ALREADY_OWNED','Üyede bulunan kalıcı rol süreli role çevrilemez.');await syncUser(tx,{id:target.id,username:target.username,avatar:target.avatar});await tx.query("INSERT INTO community_role_leases(guild_id,user_id,role_id,expires_at) VALUES($1,$2,$3,now()+$4*interval '1 minute') ON CONFLICT(guild_id,user_id,role_id) DO UPDATE SET expires_at=EXCLUDED.expires_at,status='PENDING'",[i.guildId,target.id,role.id,i.options.getInteger('dakika',true)]);await audit(tx,actor.id,'TIMED_ROLE_REQUESTED',target.id,{roleId:role.id});return {roleId:role.id};});await member.roles.add(grant.roleId,reason);await database().query("UPDATE community_role_leases SET status='ACTIVE' WHERE guild_id=$1 AND user_id=$2 AND role_id=$3",[i.guildId,target.id,grant.roleId]);return userTag(target.id)+' için süreli rol verildi. Süresi dolunca otomatik alınır.';}
 return featureMutation(actor,i.id,async tx=>{
  if(sub==='ban'){if(!member.bannable)throw new DomainError('MEMBER_HIERARCHY','Bot bu üyeyi yasaklayamaz.');await member.ban({reason,deleteMessageSeconds:0});}
  if(sub==='kick'){if(!member.kickable)throw new DomainError('MEMBER_HIERARCHY','Bot bu üyeyi çıkaramaz.');await member.kick(reason);}
  if(sub==='takmaad'){if(!member.manageable)throw new DomainError('MEMBER_HIERARCHY','Bot bu üyenin adını değiştiremez.');const name=i.options.getString('isim',true);checkText(name,settings);await member.setNickname(name,reason);}
  if(sub==='sustur'||sub==='susturmaac'){if(!member.moderatable)throw new DomainError('MEMBER_HIERARCHY','Bot bu üyeyi susturamaz.');await member.timeout(sub==='sustur'?i.options.getInteger('dakika',true)*60000:null,reason);}
  if(sub==='sestasi'){const channel=i.options.getChannel('kanal',true);if(channel.guildId!==i.guildId||channel.type!==ChannelType.GuildVoice||!member.voice.channelId||!member.movable)throw new DomainError('VOICE_CHANNEL','Üye seste olmalı ve hedef bu sunucunun ses kanalı olmalı.');await member.voice.setChannel(channel,reason);}

  await audit(tx,actor.id,'MEMBER_'+sub.toUpperCase(),target.id);return userTag(target.id)+' için işlem tamamlandı.';
 });
}
export async function handleExpansionInteraction(i:any,settings:CommunitySettings){
 if(!i.isChatInputCommand()||i.commandName!=='topluluk')return false;
 await i.deferReply({});try{if(!settings.expansion.enabled)throw new DomainError('EXPANSION_DISABLED','Gelişmiş topluluk araçları kapalı.',403);if(settings.features.channelIds.length&&!settings.features.channelIds.includes(i.channelId))throw new DomainError('FEATURE_CHANNEL','Bu kanalda topluluk araçları açık değil.',403);await featureRate(actorOf(i));const group=i.options.getSubcommandGroup(),sub=i.options.getSubcommand(),actor=actorOf(i);let text='';
  if(group==='oda')text=await roomCommand(i,sub,settings);
  else if(group==='kayit')text=await registration(i,sub,settings);
  else if(group==='yetkili')text=await moderation(i,sub,settings);
  else if(group==='ozel'){
   const commands=settings.expansion.customCommands;if(sub==='liste')text=commands.map(c=>'`!'+c.name+'` · `/topluluk ozel calistir ad: '+c.name+'`').join('\n')||'Henüz özel komut yok.';
   else {const name=i.options.getString('ad',true);if(sub==='ekle'||sub==='sil'){permission(i,PermissionFlagsBits.ManageGuild);const response=sub==='ekle'?i.options.getString('cevap',true):undefined;if(response)checkText(response,settings);await changeCustomCommand(actor,{name,response,channelId:i.options.getChannel('kanal')?.id});text='`!'+displayText(name)+'` '+(response?'komutu kaydedildi.':'komutu kaldırıldı.');}else{const c=commands.find(c=>c.name===name);if(!c||c.channelId&&c.channelId!==i.channelId)throw new DomainError('CUSTOM_COMMAND','Komut bu kanalda bulunamadı.');text=customResponse(c.response,actor,i.guild.name);}}
  }
  else if(group==='afk'){if(!settings.expansion.afkEnabled)throw new DomainError('AFK_DISABLED','AFK sistemi kapalı.');const reason=sub==='ac'?(i.options.getString('sebep')||'Biraz uzaktayım.'):null;if(reason)checkText(reason,settings);await setAFK(actor,reason,i.id);text=reason?userTag(actor.id)+' artık AFK: '+displayText(reason)+'\nMesaj yazınca AFK durumun otomatik kapanır.':'AFK durumun kapatıldı.';}
  else if(group==='dogum'){if(!settings.expansion.birthdays.enabled)throw new DomainError('BIRTHDAY_DISABLED','Doğum günü takvimi kapalı.');if(sub==='takvim'){const rows=await birthdayCalendar();text=rows.map(r=>userTag(r.user_id)+' · '+r.birthday_day+'/'+r.birthday_month).join('\n')||'Henüz gönüllü doğum günü kaydı yok.';}else{await setBirthday(actor,sub==='ayarla'?i.options.getInteger('gun',true):null,sub==='ayarla'?i.options.getInteger('ay',true):null,i.id);text=sub==='ayarla'?'Doğum günün sunucu kutlama takvimine eklendi. `/topluluk dogum sil` ile kaldırabilirsin.':'Doğum günün takvimden kaldırıldı.';}}
  else if(group==='etkinlik'){
   if(!settings.features.enabled||!settings.features.community)throw new DomainError('EVENT_DISABLED','Etkinlik sistemi kapalı.');
   if(sub==='takvim'){const rows=(await listFeatureRecords('EVENT',actor.id)).filter(r=>r.status==='OPEN'&&i.guild.channels.cache.get(r.channel_id)?.permissionsFor(i.member)?.has(PermissionFlagsBits.ViewChannel));text=rows.map(r=>'**'+displayText(r.title)+'** · <t:'+Math.floor(new Date(r.due_at!).getTime()/1000)+':F>\n'+channelTag(r.channel_id||'')+' · `'+r.id+'`').join('\n\n')||'Yaklaşan etkinlik yok.';}
   else {const id=i.options.getString('kayit',true),record=await getFeatureRecord(id),channel=await i.guild.channels.fetch(record.channel_id);if(!channel?.permissionsFor(i.member)?.has(PermissionFlagsBits.ViewChannel))throw new DomainError('FORBIDDEN','Etkinlik kanalına erişimin yok.',403);if(sub==='katilimcilar'){const rows=await eventAttendees(id),labels:Record<string,string>={GOING:'Katılıyor',MAYBE:'Belki',DECLINED:'Katılmıyor',WAITLIST:'Bekleme listesi'};text=Object.entries(labels).map(([choice,label])=>'**'+label+'**\n'+(rows.filter(r=>r.choice===choice).map(r=>userTag(r.user_id)).join(', ')||'—')).join('\n\n');}else{const title=i.options.getString('baslik');if(title)checkText(title,settings);await editEvent(actor,id,i.options.getInteger('dakika',true),title||undefined,!!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild),i.id);text='Etkinlik başlangıcı güncellendi. Katılımlar korunur; kart ve hatırlatmalar yenilenir.';}}
  }
  else if(group==='duyuru'){if(!settings.announcements.enabled)throw new DomainError('ANNOUNCEMENTS_DISABLED','Duyuru modülü kapalı.');if(sub==='planla'){permission(i,PermissionFlagsBits.ManageGuild);const channel=i.options.getChannel('kanal',true),content=i.options.getString('metin',true);checkText(content,settings);if(channel.guildId!==i.guildId||![0,5].includes(channel.type)||!channel.permissionsFor(i.member)?.has(PermissionFlagsBits.SendMessages)||!channel.permissionsFor(i.guild.members.me)?.has(PermissionFlagsBits.SendMessages|PermissionFlagsBits.EmbedLinks))throw new DomainError('INVALID_CHANNEL','Mesaj gönderilebilen bir sunucu metin kanalı seç.');const r=await scheduledAnnouncement(actor,channel.id,content,i.options.getInteger('dakika',true),i.id);text='Duyuru planlandı.\n`'+r.id+'`';}else if(sub==='iptal'){await cancelScheduled(actor,i.options.getString('kayit',true),i.id);text='Bekleyen duyuru iptal edildi.';}else text=(await scheduledList(actor.id)).map(r=>displayText(r.payload.content,150)+'\n<t:'+Math.floor(new Date(r.available_at).getTime()/1000)+':F> · `'+r.id+'`').join('\n\n')||'Bekleyen duyurun yok.';}
  await i.editReply(screen('✦ '+({oda:'Özel ses odası',kayit:'Üye kaydı',yetkili:'Yetkili araçları',ozel:'Özel komutlar',afk:'AFK durumu',dogum:'Doğum günü takvimi',etkinlik:'Etkinlik merkezi',duyuru:'Planlı duyurular'} as any)[group],text));
 }catch(e){console.error('EXPANSION_COMMAND_FAILED',{group:i.options.getSubcommandGroup(),sub:i.options.getSubcommand(),code:(e as any)?.code||'INTERNAL'});await i.editReply(screen('İşlem tamamlanamadı',e instanceof DomainError?e.message:'Discord işlemi tamamlanamadı. Botun izinlerini ve rol sırasını kontrol et.'));}return true;
}
const messageTimes=new Map<string,number>();
export async function expansionMessage(message:any,settings:CommunitySettings){
 const s=settings.expansion;if(!s.enabled)return false;const actor={id:message.author.id,username:message.author.username,avatar:message.author.avatar},key=message.guildId+':'+actor.id,now=Date.now();
 if(s.afkEnabled){const cleared=await clearAFK(actor.id),afk=await mentionedAFK([...message.mentions.users.keys()]);if((cleared||afk.length)&&now-(messageTimes.get(key)||0)>30000){messageTimes.set(key,now);if(messageTimes.size>4096)messageTimes.delete(messageTimes.keys().next().value!);await message.reply(screen('💬 Sohbet durumu',(cleared?'Tekrar hoş geldin '+userTag(actor.id)+', AFK durumun kapatıldı.\n':'')+afk.map(p=>userTag(p.user_id)+' uzakta: '+displayText(p.afk_reason,150)+' · <t:'+Math.floor(new Date(p.afk_at).getTime()/1000)+':R>').join('\n')));}}
 const match=/^!([a-z0-9-]{1,32})\s*$/.exec(message.content);if(!match)return false;const command=s.customCommands.find(c=>c.name===match[1]);if(!command||command.channelId&&command.channelId!==message.channelId)return false;await featureRate(actor);await message.reply({content:customResponse(command.response,actor,message.guild.name),allowedMentions:{parse:[],repliedUser:false}});return true;
}
export async function expansionMemberJoin(member:any,settings:CommunitySettings){if(!settings.expansion.enabled||member.pending)return;const s=settings.expansion,ids=[...new Set([...s.autoRoleIds,...(s.registration.enabled&&s.registration.unregisteredRoleId?[s.registration.unregisteredRoleId]:[])])];for(const id of ids){try{await safeRole(member.guild,id);await member.roles.add(id,'TurkishPix otomatik üye rolü');}catch{console.error('AUTOMATIC_ROLE_PENDING');}}}
export async function expansionMemberLeave(member:any,settings:CommunitySettings){const s=settings.expansion;if(!s.enabled||!s.farewell.enabled||!s.farewell.channelId)return;await database().query("INSERT INTO community_deliveries(id,guild_id,kind,payload) VALUES(gen_random_uuid(),$1,'SOCIAL',$2)",[member.guild.id,{source:'FAREWELL',channelId:s.farewell.channelId,content:customResponse(s.farewell.message,{id:member.id,username:member.user.username},member.guild.name)}]);}
let lastSocial=0;const voiceEligibleSince=new Map<string,number>();
export function expansionVoiceChange(oldState:any,newState:any){if(oldState.channelId!==newState.channelId||newState.selfMute||newState.selfDeaf||newState.serverMute||newState.serverDeaf)voiceEligibleSince.delete(newState.id);}
export async function expansionTick(client:any,settings:CommunitySettings){
 const guild=client.guilds.cache.get(config().guildId);if(!guild)return;const now=Date.now();
 // Clean up only channels tracked as our rooms, including after a restart or when creation has been disabled.
 const rooms=(await database().query('SELECT * FROM community_voice_rooms WHERE guild_id=$1',[guild.id])).rows;
 for(const row of rooms){const room=await optionalChannel(guild,row.channel_id);if(!room){await database().query('DELETE FROM community_voice_rooms WHERE guild_id=$1 AND channel_id=$2',[guild.id,row.channel_id]);continue;}if(room.members.size){await database().query('UPDATE community_voice_rooms SET empty_since=NULL WHERE guild_id=$1 AND channel_id=$2 AND empty_since IS NOT NULL',[guild.id,row.channel_id]);}else if(!row.empty_since)await database().query('UPDATE community_voice_rooms SET empty_since=now() WHERE guild_id=$1 AND channel_id=$2',[guild.id,row.channel_id]);else if(now-new Date(row.empty_since).getTime()>=settings.expansion.rooms.emptySeconds*1000){await room.delete('TurkishPix boş geçici oda');await database().query('DELETE FROM community_voice_rooms WHERE guild_id=$1 AND channel_id=$2',[guild.id,row.channel_id]);}}
 const leases=(await database().query("SELECT * FROM community_role_leases WHERE guild_id=$1 AND status<>'DONE' AND expires_at<=now() LIMIT 20",[guild.id])).rows;
 for(const lease of leases){try{await transaction(async tx=>{const due=(await tx.query("SELECT * FROM community_role_leases WHERE guild_id=$1 AND user_id=$2 AND role_id=$3 AND status<>'DONE' AND expires_at<=now() FOR UPDATE",[guild.id,lease.user_id,lease.role_id])).rows[0];if(!due)return;const role=await guild.roles.fetch(lease.role_id),member=await optionalMember(guild,lease.user_id);if(role&&member?.roles.cache.has(role.id))await member.roles.remove(role,'TurkishPix süreli rol sona erdi');await tx.query("UPDATE community_role_leases SET status='DONE' WHERE guild_id=$1 AND user_id=$2 AND role_id=$3",[guild.id,lease.user_id,lease.role_id]);});}catch{console.error('TIMED_ROLE_EXPIRY_PENDING');}}
 const eligible=new Set<string>();if(settings.expansion.enabled&&settings.expansion.voiceXP.enabled){for(const channel of guild.channels.cache.values()){if(channel.type!==ChannelType.GuildVoice||channel.id===guild.afkChannelId)continue;const members=[...channel.members.values()].filter((m:any)=>!m.user.bot&&!m.pending&&!m.voice.selfMute&&!m.voice.selfDeaf&&!m.voice.serverMute&&!m.voice.serverDeaf);if(members.length<2)continue;for(const member of members as any[]){eligible.add(member.id);const since=voiceEligibleSince.get(member.id);if(since===undefined){voiceEligibleSince.set(member.id,now);continue;}if(now-since<60000)continue;const earned=await awardVoiceXP({id:member.id,username:member.user.username,avatar:member.user.avatar},settings);voiceEligibleSince.set(member.id,now);if(earned)await syncLevelRoles(member,settings);}}}for(const id of voiceEligibleSince.keys())if(!eligible.has(id))voiceEligibleSince.delete(id);
 if(now-lastSocial>=60000){lastSocial=now;await birthdayMaintenance(settings);await database().query("DELETE FROM youtube_history WHERE created_at<now()-interval '30 days'");await database().query("UPDATE youtube_library SET title='YouTube videosu',metadata_updated_at=NULL WHERE metadata_updated_at<now()-interval '30 days'");}
}
export async function syncLevelRoles(member:any,settings:CommunitySettings){if(!settings.expansion.enabled||!settings.features.enabled||!settings.features.xpEnabled||!settings.expansion.levelRoles.length)return;const profile=await memberProfile(member.id);for(const reward of settings.expansion.levelRoles)if(profile.level>=reward.level&&!member.roles.cache.has(reward.roleId)){try{await safeRole(member.guild,reward.roleId);await member.roles.add(reward.roleId,'TurkishPix seviye ödülü');}catch{console.error('LEVEL_ROLE_PENDING');}}}
export async function reportExpansionReady(){console.log('COMMUNITY_EXPANSION_READY',JSON.stringify({version:RELEASE_VERSION,command:'topluluk',usages:expansionUsageCount,rooms:true,registration:true,customCommands:true,birthdays:true,afk:true,voiceXP:true,timedRoles:true,eventRSVP:true,youtube:await youtubeStatus()}));}
