import {eventOptionsSchema,eventRSVP,eventMaintenance} from '@turkishpix/core';
import {commandHelpView} from './help';
import {discordAvatarData,renderRankCard} from '../../../packages/core/src/cards';
import {memberRank} from '@turkishpix/core';
import {MessageFlags,PermissionFlagsBits} from 'discord.js';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {config,DomainError,database,transaction,audit,syncUser,featureCommands,featureNames,featureCategories,shopItems,checkFeature,featureRate,featureMutation,memberProfile,xpLeaderboard,memberBadges,claimDaily,transferCoins,purchaseBadge,giveReputation,addFeatureRecord,getFeatureRecord,listFeatureRecords,updateFeatureRecord,attachFeatureMessage,participateFeature,finishGiveaway,brightEmbed,displayText,userTag,channelTag,roleTag,theme,inspectContent,roleMappings,ticketTick,giveawayTick,giveawayMessage,type CommunitySettings,type FeatureRecord} from '@turkishpix/core';
const buttons=(...items:any[])=>[{type:1,components:items}];
const button=(id:string,label:string,emoji:string,style=1)=>({type:2,custom_id:id,label,emoji:{name:emoji},style});
const queues=new Map<string,Promise<unknown>>();
const refreshRetryAt=new Map<string,number>();
async function serial<T>(key:string,fn:()=>Promise<T>){const next=(queues.get(key)||Promise.resolve()).catch(()=>{}).then(fn);queues.set(key,next);try{return await next;}finally{if(queues.get(key)===next)queues.delete(key);}}
const actorOf=(i:any)=>({id:i.user.id,username:i.user.username,avatar:i.user.avatar});
const staffOf=(i:any)=>!!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild);
function requirePermission(i:any,permission:bigint){if(!i.memberPermissions?.has(permission))throw new DomainError('FORBIDDEN','Bu komut için gerekli Discord yetkin yok.',403);}
function screen(title:string,description:string,fields:any[]=[],color=theme.cyan){return {embeds:[brightEmbed(title,description,fields,color)],allowedMentions:{parse:[],repliedUser:false}};}
function recordList(records:FeatureRecord[],privateView=false){return records.length?records.map(r=>`**${displayText(r.title,250)}**\n${({OPEN:'🟢 Açık',DONE:'✅ Tamamlandı',CLOSED:'🔒 Kapalı',APPROVED:'✅ Kabul',REJECTED:'❌ Ret'} as any)[r.status]||r.status}${r.due_at?` · <t:${Math.floor(new Date(r.due_at).getTime()/1000)}:R>`:''}${r.participants===undefined?'':` · ${r.participants} katılım`}\n${privateView?'':userTag(r.owner_id)+' · '}\`${r.id}\``).join('\n\n').slice(0,3900):'Henüz kayıt yok.';}
const listNames:Record<string,string>={REMINDER:'hatirlatmalar',NOTE:'notlar',TASK:'gorevler',EVENT:'etkinlikler',SUGGESTION:'oneriler',TICKET:'destekler',WARNING:'uyarilar'};
async function featureListView(kind:string,viewerId:string,targetId:string,staff:boolean,page=0){const records=await listFeatureRecords(kind as any,targetId,staff,{limit:3,offset:page*2}),shown=records.slice(0,2),labels:Record<string,string>={NOTE:'📝 Kişisel not',TASK:'✅ Görev',REMINDER:'⏰ Hatırlatma',TICKET:'🎫 Destek',WARNING:'🛡️ Uyarı',EVENT:'📅 Etkinlik',SUGGESTION:'💡 Öneri'};const embeds=shown.length?shown.map(r=>{const description=displayText(r.title,2000)+(r.payload.description?'\n\n'+displayText(r.payload.description,1800):'');const e=brightEmbed(labels[kind]||'📋 Kayıt',description,[{name:'📌 Durum',value:({OPEN:'🟢 Açık',DONE:'✅ Tamamlandı',CLOSED:'🔒 Kapalı',APPROVED:'✅ Kabul',REJECTED:'❌ Ret'} as any)[r.status]||r.status,inline:true},...(r.due_at?[{name:'⏰ Zaman',value:`<t:${Math.floor(new Date(r.due_at).getTime()/1000)}:R>`,inline:true}]:[]),...(['EVENT','SUGGESTION'].includes(kind)?[{name:'👤 Organizatör',value:userTag(r.owner_id),inline:true},{name:'✨ Katılım',value:String(r.participants)}]:[])]);e.footer={text:'TurkishPix • Kayıt '+r.id};return e;}):[brightEmbed('📋 Kayıtların','Bu sayfada kayıt yok.')];const items=[];if(page>0)items.push(button(`featurelist:${viewerId}:${targetId}:${kind}:${page-1}`,'Önceki','⬅️',2));if(records.length>2)items.push(button(`featurelist:${viewerId}:${targetId}:${kind}:${page+1}`,'Sonraki','➡️',2));return {embeds,components:items.length?buttons(...items):[],allowedMentions:{parse:[],repliedUser:false}};}

export function featureRecordView(r:FeatureRecord,participants=0){
 if(r.kind==='GIVEAWAY'){const {allowed_mentions,...view}=giveawayMessage(r,participants);return {...view,allowedMentions:allowed_mentions};}
 const closed=r.status!=='OPEN';const icons:Record<string,string>={GIVEAWAY:'🎁',EVENT:'📅',SUGGESTION:'💡',ROLE_MENU:'🎭'};
 let description=displayText(r.title,900),components:any[]=[];
 if(r.kind==='EVENT')description+=`\n\n${displayText(r.payload.description||'',600)}\nBaşlangıç: <t:${Math.floor(new Date(r.due_at!).getTime()/1000)}:F>\n**${participants}** katılımcı${r.payload.capacity?' / '+r.payload.capacity+' kontenjan':''}${r.payload.repeat&&r.payload.repeat!=='OFF'?' · '+(r.payload.repeat==='DAILY'?'Her gün':'Her hafta'):''}\n${r.payload.requiredRoleId?'Katılım rolü: <@&'+r.payload.requiredRoleId+'>\n':''}Katılıyorum seçeneği hatırlatma etiketlerine katılır.${closed?' · Etkinlik '+(r.status==='DONE'?'başladı':'iptal edildi'):''}`;
 if(r.kind==='SUGGESTION')description+=`\n\n**${participants}** destek · ${closed?r.status==='APPROVED'?'✅ Kabul edildi':'❌ Reddedildi':'🗳️ Topluluk değerlendirmesinde'}`;
 if(r.kind==='ROLE_MENU')description+=`\n\n${roleTag(r.payload.roleId)}\n${closed?'Menü kapalı.':'Düğme ile rolüne katıl veya ayrıl.'}`;
 if(!closed&&r.kind==='EVENT')components=buttons(button(`feature:${r.id}:GOING`,'Katılıyorum','✅',3),button(`feature:${r.id}:MAYBE`,'Belki','🤔',2),button(`feature:${r.id}:DECLINED`,'Katılmıyorum','❌',2),button(`feature:${r.id}:LEAVE`,'Kaydı kaldır','↩️',2));
 if(!closed&&r.kind!=='EVENT')components=buttons(button(`feature:${r.id}:join`,r.kind==='SUGGESTION'?'Öneriyi destekle':'Rolü al / bırak',r.kind==='ROLE_MENU'?'🎭':'✨'));
 const embed=brightEmbed(`${icons[r.kind]||'📌'} TurkishPix · ${({GIVEAWAY:'Çekiliş',EVENT:'Etkinlik',SUGGESTION:'Öneri',ROLE_MENU:'Rol menüsü'} as any)[r.kind]||'Topluluk'}`,description,[{name:'👤 Organizatör',value:userTag(r.owner_id),inline:true},{name:'💬 Kanal',value:channelTag(r.channel_id||''),inline:true}],r.kind==='ROLE_MENU'?theme.purple:theme.cyan);embed.footer={text:'TurkishPix • Kayıt '+r.id};return {embeds:[embed],components,allowedMentions:{parse:[]}};
}
async function refreshRecord(i:any,record:FeatureRecord){return serial('message:'+record.id,async()=>{
 if((refreshRetryAt.get(record.id)||0)>Date.now())return;
 const r=await getFeatureRecord(record.id);if(!r.channel_id||!r.message_id)return;
 try{
  const channel=await i.guild.channels.fetch(r.channel_id);
  if(!channel)throw {code:10003};
  const message=await channel.messages.fetch(r.message_id);
  const count=(await database().query("SELECT count(*)::int AS n FROM feature_participants WHERE record_id=$1 AND choice='GOING'",[r.id])).rows[0].n;
  await message.edit(featureRecordView(r,count));
  await database().query('UPDATE feature_records SET discord_updated_at=$2 WHERE id=$1',[r.id,(r as any).updated_at]);
  refreshRetryAt.delete(r.id);
 }catch(e:any){
  if([10003,10008].includes(e?.code)){
   // Do not recreate a card that a moderator deliberately removed.
   await database().query('UPDATE feature_records SET discord_updated_at=$2 WHERE id=$1',[r.id,(r as any).updated_at]);
   refreshRetryAt.delete(r.id);
   console.log('FEATURE_MESSAGE_UNAVAILABLE',JSON.stringify({recordId:r.id,kind:r.kind,code:e.code}));
  }else{
   if(refreshRetryAt.size>=500)refreshRetryAt.delete(refreshRetryAt.keys().next().value!);
   refreshRetryAt.set(r.id,Date.now()+5*60000);
   console.error('FEATURE_MESSAGE_REFRESH_PENDING',JSON.stringify({recordId:r.id,kind:r.kind,code:typeof e?.code==='number'?e.code:'NETWORK'}));
  }
 }
});}

async function validRole(guild:any,roleId:string,executor?:any){await guild.channels.fetch();const role=await guild.roles.fetch(roleId),bot=guild.members.me;if(!role||role.id===guild.id||role.managed||role.permissions.bitfield!==0n||!role.editable||!bot?.permissions.has(PermissionFlagsBits.ManageRoles))throw new DomainError('ROLE_NOT_SAFE','Rol yönetilmeyen, botun altında ve izinleri sıfır olan kozmetik bir rol olmalı.',403);if(executor&&executor.id!==guild.ownerId&&executor.roles.highest.comparePositionTo(role)<=0)throw new DomainError('ROLE_HIERARCHY','Seçtiğin rol senin en yüksek rolünün altında olmalı.',403);if(guild.channels.cache.some((c:any)=>{const overwrite=c.permissionOverwrites?.cache.get(roleId);return !!overwrite&&overwrite.allow.bitfield!==0n;}))throw new DomainError('ROLE_ACCESS','Kanal erişimi sağlayan roller self-role menüsüne eklenemez.',403);if(Object.values(await roleMappings()).includes(roleId))throw new DomainError('POLITICAL_ROLE','Siyasi görev rolleri self-role menüsüne eklenemez.',403);return role;}
async function targetChannel(i:any){const channel=i.options.getChannel('kanal')||i.channel;if(!channel||channel.guildId!==i.guildId||![0,5].includes(channel.type))throw new DomainError('CHANNEL_REQUIRED','Bu sunucudan bir metin kanalı seç.');const member=await i.guild.members.fetch(i.user.id);if(!channel.permissionsFor(member)?.has(PermissionFlagsBits.ViewChannel))throw new DomainError('CHANNEL_ACCESS','Bu kanala erişimin yok.',403);return channel;}
function cleanSignature(value:string){return createHmac('sha256',config().auditKey).update(value).digest('hex').slice(0,24);}
function cleanId(i:any,count:number){const value=[i.user.id,i.channelId,count,Date.now()+60000].join(':');return 'featureclean:'+value+':'+cleanSignature(value);}
async function manageLock(i:any,channel:any,locked:boolean){requirePermission(i,PermissionFlagsBits.ManageChannels);const member=await i.guild.members.fetch(i.user.id);if(!channel.permissionsFor(member)?.has(PermissionFlagsBits.ManageChannels)||!channel.permissionsFor(i.guild.members.me)?.has(PermissionFlagsBits.ManageRoles))throw new DomainError('CHANNEL_PERMISSION','Kanal izinlerini değiştirmek için senin kanal yönetimi, botun rol/izin yönetimi yetkisi olmalı.',403);
 const roleId=i.guildId;const old=(await database().query('SELECT original FROM feature_channel_locks WHERE guild_id=$1 AND channel_id=$2',[i.guildId,channel.id])).rows[0];
 if(locked){const overwrite=channel.permissionOverwrites.cache.get(roleId),original=old?.original||{send:overwrite?.deny.has(PermissionFlagsBits.SendMessages)?false:overwrite?.allow.has(PermissionFlagsBits.SendMessages)?true:null,threads:overwrite?.deny.has(PermissionFlagsBits.SendMessagesInThreads)?false:overwrite?.allow.has(PermissionFlagsBits.SendMessagesInThreads)?true:null};if(!old)await transaction(async tx=>{await syncUser(tx,actorOf(i));await tx.query('INSERT INTO feature_channel_locks(guild_id,channel_id,original,locked_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[i.guildId,channel.id,original,i.user.id]);});await channel.permissionOverwrites.edit(roleId,{SendMessages:false,SendMessagesInThreads:false},{reason:'TurkishPix kanal kilidi'});}
 else{if(!old)throw new DomainError('LOCK_UNKNOWN','TurkishPix tarafından saklanmış bir kanal kilidi yok.');await channel.permissionOverwrites.edit(roleId,{SendMessages:old.original.send,SendMessagesInThreads:old.original.threads},{reason:'TurkishPix kilit kaldırma'});await database().query('DELETE FROM feature_channel_locks WHERE guild_id=$1 AND channel_id=$2',[i.guildId,channel.id]);}
 await transaction(async tx=>{await syncUser(tx,actorOf(i));await audit(tx,i.user.id,locked?'CHANNEL_LOCKED':'CHANNEL_UNLOCKED',channel.id);});
}
export async function handleFeatureInteraction(i:any,settings:CommunitySettings):Promise<boolean>{
 const slash=i.isChatInputCommand(),help=i.isStringSelectMenu()&&i.customId==='featurehelp:category',component=i.isButton()&&/^feature(?:clean|list)?:/.test(i.customId);
 if(!help&&!component&&!(slash&&featureNames.includes(i.commandName)))return false;
 const actor=actorOf(i),staff=staffOf(i),policy=settings.features;
 try{
  if(help){checkFeature(policy,'ozellikler',i.channelId);const category=i.values[0];await i.update(featureHelp(category));return true;}
  if(component){await i.deferReply({flags:MessageFlags.Ephemeral});await featureRate(actor);
   if(i.customId.startsWith('featurelist:')){const match=/^featurelist:(\d{17,20}):(\d{17,20}):(NOTE|TASK|REMINDER|TICKET|WARNING|EVENT|SUGGESTION):(\d{1,4})$/.exec(i.customId);if(!match||match[1]!==actor.id)throw new DomainError('FORBIDDEN','Bu liste başka bir üyeye ait.',403);const [_,viewer,target,kind,page]=match;checkFeature(policy,listNames[kind],i.channelId);if(kind==='WARNING'&&target!==actor.id)requirePermission(i,PermissionFlagsBits.ModerateMembers);else if(target!==actor.id)throw new DomainError('FORBIDDEN','Başka bir üyenin kişisel listesine erişemezsin.',403);await i.editReply(await featureListView(kind,viewer,target,staff,Number(page)));return true;}
   if(i.customId.startsWith('featureclean:')){checkFeature(policy,'temizle',i.channelId);requirePermission(i,PermissionFlagsBits.ManageMessages);const [_,userId,channelId,count,expires,signature]=i.customId.split(':'),value=[userId,channelId,count,expires].join(':');const expected=cleanSignature(value);if(userId!==actor.id||channelId!==i.channelId||Date.now()>Number(expires)||!/^\d{1,3}$/.test(count)||Number(count)<1||Number(count)>100||signature?.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))throw new DomainError('CONFIRM_EXPIRED','Bu onay geçersiz veya süresi dolmuş. Komutu yeniden kullan.');if(!i.channel.permissionsFor(i.guild.members.me)?.has(PermissionFlagsBits.ManageMessages))throw new DomainError('BOT_PERMISSION','Botun bu kanalda Mesajları Yönet izni yok.');const result=await featureMutation(actor,i.customId,async tx=>{const deleted=await i.channel.bulkDelete(Number(count),true);await audit(tx,actor.id,'CHANNEL_CLEANED',i.channelId,{count:deleted.size});return {count:deleted.size};});await i.editReply(screen('🧹 Kanal temizlendi',`**${result.count}** mesaj silindi. 14 günden eski mesajlar atlandı.`));return true;}
   const match=/^feature:([0-9a-f-]{36}):(join|GOING|MAYBE|DECLINED|LEAVE)$/.exec(i.customId);if(!match)throw new DomainError('FEATURE_COMPONENT','Bu düğme geçerli değil.');const r=await getFeatureRecord(match[1]);const name=({GIVEAWAY:'cekilis',EVENT:'etkinlik',SUGGESTION:'oner',ROLE_MENU:'rolmenu'} as any)[r.kind];checkFeature(policy,name,i.channelId);if(r.channel_id!==i.channelId||r.message_id!==i.message.id)throw new DomainError('FEATURE_COMPONENT','Bu düğme başka bir mesaja ait.',403);if(r.status!=='OPEN')throw new DomainError('FEATURE_CLOSED','Bu kayıt artık açık değil.');
   if(r.kind==='ROLE_MENU'){await serial(actor.id+':'+r.id,async()=>{const role=await validRole(i.guild,r.payload.roleId),member=await i.guild.members.fetch(actor.id);if(member.pending)throw new DomainError('MEMBERSHIP_PENDING','Önce sunucu üyelik adımlarını tamamla.');const result=await featureMutation(actor,i.id,async tx=>{const had=member.roles.cache.has(role.id);if(had)await member.roles.remove(role,'TurkishPix self-role');else await member.roles.add(role,'TurkishPix self-role');await audit(tx,actor.id,'SELF_ROLE_CHANGED',role.id,{enabled:!had});return {enabled:!had};});await i.editReply(screen('🎭 Rol tercihin güncellendi',`${roleTag(role.id)} ${result.enabled?'rolüne katıldın.':'rolünden ayrıldın.'}`));});return true;}
   if(r.kind==='EVENT'){const member=await i.guild.members.fetch(actor.id);if(member.pending)throw new DomainError('MEMBERSHIP_PENDING','Önce sunucu doğrulamasını tamamla.');const result=await eventRSVP(actor,r.id,match[2]==='join'?'TOGGLE':match[2] as any,[...member.roles.cache.keys()],i.id);await refreshRecord(i,result.record);await i.editReply(screen('✅ Etkinlik tercihin',({GOING:'Katılımın kaydedildi.',MAYBE:'Belki yanıtın kaydedildi.',DECLINED:'Katılmıyorum yanıtın kaydedildi.',WAITLIST:'Kontenjan dolu. Bekleme listesine alındın; yer açılınca sırayla katılımın onaylanır.',LEAVE:'Katılım kaydın kaldırıldı.'} as any)[result.choice]));return true;}
   if(match[2]!=='join')throw new DomainError('FEATURE_COMPONENT','Bu düğme geçerli değil.');const result=await participateFeature(actor,r.id,i.id);await refreshRecord(i,result.record);await i.editReply(screen('✅ Tercihin kaydedildi',result.joined?'Katılımın / desteğin kaydedildi.':'Etkinlik katılımından ayrıldın.'));return true;
  }
  const name=i.commandName;checkFeature(policy,name,i.channelId);const definition=featureCommands.find(c=>c.name===name)!;
  if(definition.default_member_permissions)requirePermission(i,BigInt(definition.default_member_permissions));
  const isPublic=['cekilis','etkinlik','oner','rolmenu'].includes(name);const privateReply=definition.category==='planlama'||['destek','destekler','destekkapat','uyar','uyarilar','uyarikaldir','temizle'].includes(name);await i.deferReply(privateReply?{flags:MessageFlags.Ephemeral}:{});await featureRate(actor);
  if(!i.appPermissions?.has(PermissionFlagsBits.EmbedLinks))throw new DomainError('BOT_PERMISSION','Bu kanalda botun Bağlantıları Yerleştir iznini aç.');
  const get=(key:string,required=true)=>i.options.getString(key,required),number=(key:string)=>i.options.getInteger(key,true),selected=i.options.getUser('uye')||i.user,target={id:selected.id,username:selected.username,avatar:selected.avatar},key=i.id;
  if(['rank','seviye'].includes(name)){
   const p=await memberRank(target.id),member=await i.guild.members.fetch(target.id).catch(()=>null);
   const embed=brightEmbed('⭐ '+(member?.displayName||selected.username)+' · Rank',userTag(target.id)+' · **Seviye '+p.level+'** · **'+p.xp+' XP**',[
    {name:'🏆 Sunucu sırası',value:p.rank?'**#'+p.rank+'** / '+p.rankedMembers+' XP kazanan üye':'Henüz sıralamada değilsin.',inline:true},
    {name:'📈 İlerleme',value:'**%'+p.percent+'** · Sonraki seviyeye **'+p.remaining+' XP**',inline:true},
    {name:'💬 Katkılar',value:p.messages+' XP kazandıran mesaj · '+p.voice_minutes+' ses dakikası'},
    {name:'⭐ XP nasıl kazanılır?',value:policy.xpEnabled?'En az 8 karakterlik farklı sohbet katkıları **'+policy.xpPerMessage+' XP** kazandırır. Bekleme **'+policy.xpCooldownSeconds+' sn**, günlük ortak sınır **'+policy.xpDailyCap+' XP**.':'Sohbet XP’si owner ayarlarından kapalı.'}
   ],theme.gold);
   const view:any={embeds:[embed],allowedMentions:{parse:[]}};
   if(i.appPermissions?.has(PermissionFlagsBits.AttachFiles)){
    try{const avatarData=await discordAvatarData(target.id,target.avatar);const png=await renderRankCard({username:selected.username,displayName:member?.displayName||selected.username,guildName:i.guild.name||'TurkishPix',xp:p.xp,level:p.level,start:p.start,end:p.end,percent:p.percent,remaining:p.remaining,rank:p.rank,rankedMembers:p.rankedMembers,messages:p.messages,voiceMinutes:p.voice_minutes,avatarData});view.files=[{attachment:png,name:'turkishpix-rank.png'}];embed.image={url:'attachment://turkishpix-rank.png'};}catch{console.error('RANK_CARD_RENDER_FAILED');}
   }
   await i.editReply(view);return true;
  }
  if(['cuzdan','rozetler','itibar','envanter'].includes(name)){const p=await memberProfile(name==='envanter'?actor.id:target.id);let description=userTag(p.user_id),fields:any[]=[];
   if(name==='cuzdan')description+=`\n\n🪙 **${p.coins} sanal Bot TL**\n/gunluk ile ödül, /magaza ile rozet. Bot TL’in parasal değeri yoktur.`;
   if(name==='rozetler')description+='\n\n'+(memberBadges(p).join('\n')||'5. seviyede ilk aktiflik rozeti; 100 sohbet katkısında sohbet rozeti.');
   if(name==='itibar')description+=`\n\n🤝 **${p.reputation}** teşekkür puanı. /tesekkur ile günde bir üyeye puan ver.`;
   if(name==='envanter')description+='\n\n'+(shopItems.filter(x=>p.inventory.includes(x.id)).map(x=>x.name).join('\n')||'Henüz satın alınmış rozet yok. /magaza');
   await i.editReply(screen('✨ Üye kartı',description,fields,theme.gold));return true;}
  if(name==='siralama'){const list=await xpLeaderboard();await i.editReply(screen('🏆 Sohbet sıralaması',list.length?list.map((p,n)=>`**${n+1}.** ${userTag(p.user_id)} — **${p.xp} XP**`).join('\n'):'İlk sohbet katkınla sıralamayı başlat.'));return true;}
  if(name==='gunluk'){const r=await claimDaily(actor,policy,key);await i.editReply(screen('🎁 Günlük ödülün hazır',`**+${r.reward} sanal Bot TL**\n🔥 ${r.streak} günlük seri\n🪙 Yeni bakiye: **${r.coins}**`,[],theme.gold));return true;}
  if(['transfer','tesekkur'].includes(name)){if(selected.bot)throw new DomainError('BOT_TARGET','Bir insan üye seç.');const member=await i.guild.members.fetch(selected.id);if(member.pending)throw new DomainError('MEMBERSHIP_PENDING','Hedef üye sunucu katılım adımlarını tamamlamalı.');if(name==='transfer'){const r=await transferCoins(actor,target,number('miktar'),key);await i.editReply(screen('🪙 Transfer tamamlandı',`${userTag(target.id)} üyesine **${r.amount} sanal Bot TL** gönderildi.\nBakiyen: **${r.coins}**`));}else{await giveReputation(actor,target,key);await i.editReply(screen('🤝 Teşekkür kaydedildi',`${userTag(target.id)} üyesine **+1 itibar** verdin.`));}return true;}
  if(name==='magaza'){await i.editReply(screen('🛍️ Profil mağazası',shopItems.map(x=>`**${x.name}** · ${x.price} sanal Bot TL\n\`/satinal urun: ${x.id}\``).join('\n\n')+'\n\nRozetler profil içindir; Discord yetkisi sağlamaz.',[],theme.purple));return true;}
  if(name==='satinal'){const r=await purchaseBadge(actor,get('urun'),key);await i.editReply(screen('🛍️ Rozet envanterine eklendi',`${r.item.name}\nKalan bakiye: **${r.coins} sanal Bot TL**`));return true;}
  const createKinds:Record<string,any>={hatirlat:['REMINDER','mesaj'],notekle:['NOTE','not'],gorevekle:['TASK','gorev'],cekilis:['GIVEAWAY','odul'],etkinlik:['EVENT','baslik'],oner:['SUGGESTION','metin'],destek:['TICKET','konu'],uyar:['WARNING','sebep'],rolmenu:['ROLE_MENU','baslik'],sssekle:['FAQ','soru']};
  if(createKinds[name]){const [kind,field]=createKinds[name],title=get(field);let payload:any={},channelId=isPublic?i.channelId:undefined;
   if(['GIVEAWAY','EVENT','SUGGESTION','FAQ','ROLE_MENU'].includes(kind)&&inspectContent(title,settings.security.content))throw new DomainError('CONTENT_RULE','Bu metin sohbet korumasına takıldı. Saygılı bir ifadeyle yeniden dene.');
   if(kind==='EVENT')payload=eventOptionsSchema.parse({description:get('aciklama',false)||'',capacity:i.options.getInteger('kontenjan')??0,repeat:get('tekrar',false)||'OFF',reminders:get('hatirlatmalar',false)?get('hatirlatmalar',false).split(',').map((v:string)=>Number(v.trim())):[15],requiredRoleId:i.options.getRole('katilim-rolu')?.id||''});if(kind==='TICKET')payload.description=get('mesaj');if(kind==='FAQ')payload.answer=get('cevap');if(['EVENT','FAQ'].includes(kind)&&inspectContent(payload.description||payload.answer||'',settings.security.content))throw new DomainError('CONTENT_RULE','Bu metin sohbet korumasına takıldı.');
   if(kind==='WARNING'){const member=await i.guild.members.fetch(target.id),executor=await i.guild.members.fetch(actor.id);if(target.id===actor.id||selected.bot||target.id===i.guild.ownerId||!member.moderatable||(actor.id!==i.guild.ownerId&&executor.roles.highest.comparePositionTo(member.roles.highest)<=0))throw new DomainError('TARGET_HIERARCHY','Bu üyeye uyarı veremezsin; Discord yetki ve rol sırasını kontrol et.',403);payload={userId:target.id,username:target.username};}
   if(kind==='ROLE_MENU'){const executor=await i.guild.members.fetch(actor.id),role=await validRole(i.guild,i.options.getRole('rol',true).id,executor);payload={roleId:role.id};}
   if(kind==='SUGGESTION'&&policy.suggestionChannel)channelId=policy.suggestionChannel;
   if(kind==='SUGGESTION'&&channelId!==i.channelId){const target=await i.guild.channels.fetch(channelId);if(!target?.isTextBased()||!target.permissionsFor(i.guild.members.me)?.has([PermissionFlagsBits.SendMessages,PermissionFlagsBits.EmbedLinks]))throw new DomainError('SUGGESTION_CHANNEL','Öneri kanalında botun gönderme izni eksik.');}
   const r=await addFeatureRecord(actor,kind,title,payload,{channelId,minutes:['REMINDER','GIVEAWAY','EVENT'].includes(kind)?number('dakika'):undefined},key);
   if(isPublic){if(channelId!==i.channelId){const channel=await i.guild.channels.fetch(channelId);if(!channel?.isTextBased()||!channel.permissionsFor(i.guild.members.me)?.has([PermissionFlagsBits.SendMessages,PermissionFlagsBits.EmbedLinks]))throw new DomainError('SUGGESTION_CHANNEL','Öneri kanalında botun gönderme izni eksik.');const message=await channel.send(featureRecordView(r));await attachFeatureMessage(r.id,channelId,message.id);await i.editReply(screen('💡 Önerin gönderildi',channelTag(channelId)));}else{const message=await i.editReply(featureRecordView(r));await attachFeatureMessage(r.id,i.channelId,message.id);}}
   else await i.editReply(screen(({REMINDER:'⏰ Hatırlatma kuruldu',NOTE:'📝 Notun kaydedildi',TASK:'✅ Görev eklendi',TICKET:'🎫 Destek talebin açıldı',WARNING:'🛡️ Uyarı kaydedildi',FAQ:'📚 Rehber güncellendi'} as any)[kind],`${kind==='WARNING'?userTag(target.id)+'\n':''}${displayText(title)}\n\n${r.due_at?`<t:${Math.floor(new Date(r.due_at).getTime()/1000)}:R> · Sana DM gönderilecek.\n`:''}Kayıt: \`${r.id}\`${kind==='TICKET'?'\nAyrıntılar sadece sana ve yetkililere görünür.':''}`));return true;}
  const listKinds:Record<string,any>={hatirlatmalar:'REMINDER',notlar:'NOTE',gorevler:'TASK',etkinlikler:'EVENT',oneriler:'SUGGESTION',destekler:'TICKET',uyarilar:'WARNING',sss:'FAQ'};
  if(listKinds[name]){const kind=listKinds[name];if(name==='uyarilar'&&target.id!==actor.id)requirePermission(i,PermissionFlagsBits.ModerateMembers);let records=await listFeatureRecords(kind,name==='uyarilar'?target.id:actor.id,staff,{limit:name==='sss'?100:25});if(name==='sss'){const search=(get('ara',false)||'').toLocaleLowerCase('tr-TR');records=records.filter(r=>r.status==='OPEN'&&(r.title+' '+r.payload.answer).toLocaleLowerCase('tr-TR').includes(search));await i.editReply(screen('📚 Sunucu rehberi',records.length?records.map(r=>`**${displayText(r.title)}**\n${displayText(r.payload.answer)}${staff?`\n\`${r.id}\``:''}`).join('\n\n').slice(0,3900):'Eşleşen soru bulunamadı.'));}else await i.editReply(await featureListView(kind,actor.id,name==='uyarilar'?target.id:actor.id,staff));return true;}
  const updates:Record<string,any>={hatirlatmasil:['REMINDER','CANCELLED'],notsil:['NOTE','CANCELLED'],gorevtamamla:['TASK','DONE'],gorevsil:['TASK','CANCELLED'],cekiliskapat:['GIVEAWAY','CANCELLED'],etkinlikkapat:['EVENT','CANCELLED'],oneridurum:['SUGGESTION',''],destekkapat:['TICKET','CLOSED'],uyarikaldir:['WARNING','CANCELLED'],rolmenukapat:['ROLE_MENU','CLOSED'],ssssil:['FAQ','CANCELLED']};
  if(updates[name]){const [kind,state]=updates[name],id=get('kayit'),old=await getFeatureRecord(id);if(old.kind!==kind)throw new DomainError('FEATURE_KIND','Kayıt kodu bu komutun türüne ait değil.');const r=await updateFeatureRecord(actor,id,state||get('durum'),staff||name==='uyarikaldir'||name==='rolmenukapat',key);if(['GIVEAWAY','EVENT','SUGGESTION','ROLE_MENU'].includes(kind))await refreshRecord(i,r);await i.editReply(screen('✅ Kayıt güncellendi',`**${displayText(r.title)}**\nYeni durum: ${({DONE:'Tamamlandı',CLOSED:'Kapalı',CANCELLED:'İptal / kaldırıldı',APPROVED:'Kabul',REJECTED:'Ret'} as any)[r.status]}`));return true;}
  if(name==='cekilissonuc'){const r=await getFeatureRecord(get('kayit'));if(r.kind!=='GIVEAWAY')throw new DomainError('FEATURE_KIND','Bir çekiliş kodu seç.');if(r.status==='OPEN'&&(staff||r.owner_id===actor.id)){const result=await finishGiveaway(actor,r.id,staff,key);await refreshRecord(i,result);await i.editReply(featureRecordView(result));}else await i.editReply({...featureRecordView(r),components:[]});return true;}
  if(name==='kilitle'||name==='kilitac'){const channel=await targetChannel(i);await serial(channel.id,()=>manageLock(i,channel,name==='kilitle'));await i.editReply(screen(name==='kilitle'?'🔒 Kanal kilitlendi':'🔓 Kanal kilidi kaldırıldı',`${channelTag(channel.id)} · @everyone yazma izni ${name==='kilitle'?'kapatıldı. Diğer rollerin açık yazma izinleri korunur.':'eski durumuna getirildi.'}`));return true;}
  if(name==='yavasmod'){const channel=await targetChannel(i),seconds=number('saniye');if(!channel.permissionsFor(i.guild.members.me)?.has(PermissionFlagsBits.ManageChannels))throw new DomainError('BOT_PERMISSION','Bu kanalda botun Kanalı Yönet izni yok.');if(!channel.permissionsFor(await i.guild.members.fetch(actor.id))?.has(PermissionFlagsBits.ManageChannels))throw new DomainError('FORBIDDEN','Bu kanalı yönetemezsin.',403);await channel.setRateLimitPerUser(seconds,'TurkishPix yavaş mod');await i.editReply(screen('⏳ Yavaş mod güncellendi',`${channelTag(channel.id)} · ${seconds?`**${seconds} saniye**`:'Kapalı'}`));return true;}
  if(name==='temizle'){const count=number('adet');await i.editReply({...screen('🧹 Kanal temizleme onayı',`${channelTag(i.channelId)} kanalında son **${count}** mesajı silmek için aşağıdaki düğmeye bas.\nOnay 60 saniye geçerli; mesaj silme geri alınamaz.`,[],theme.red),components:buttons(button(cleanId(i,count),'Mesajları sil','🗑️',4))});return true;}
  if(name==='duyuru'){const channel=await targetChannel(i);if(!channel.permissionsFor(i.guild.members.me)?.has([PermissionFlagsBits.SendMessages,PermissionFlagsBits.EmbedLinks]))throw new DomainError('BOT_PERMISSION','Hedef kanalda botun gönderme ve embed izinleri eksik.');const message=await channel.send(screen('📣 '+displayText(get('baslik'),100),displayText(get('metin'),1600),[{name:'👤 Paylaşan',value:userTag(actor.id)}],theme.gold));await i.editReply(screen('📣 Duyuru paylaşıldı',`${channelTag(channel.id)}\n[Mesajı aç](${message.url})`));return true;}
  if(name==='sabitle'){const raw=get('mesaj'),match=/^(?:https:\/\/(?:canary\.|ptb\.)?discord\.com\/channels\/(\d+)\/(\d+)\/)?(\d{17,20})$/.exec(raw);if(!match||match[1]&&match[1]!==i.guildId||match[2]&&match[2]!==i.channelId)throw new DomainError('MESSAGE_LINK','Bu sunucu ve kanaldan bir mesaj seç.');if(!i.channel.permissionsFor(i.guild.members.me)?.has(PermissionFlagsBits.ManageMessages))throw new DomainError('BOT_PERMISSION','Botun bu kanalda Mesajları Yönet izni yok.');const message=await i.channel.messages.fetch(match[3]);await message.pin('TurkishPix yetkili komutu');await i.editReply(screen('📌 Mesaj sabitlendi',`[Mesajı aç](${message.url}) · ${channelTag(i.channelId)}`));return true;}
  if(name==='kanalbilgi'){const channel=await targetChannel(i);await i.editReply(screen('💬 Kanal kartı',channelTag(channel.id),[{name:'📝 Konu',value:displayText(channel.topic||'Konu belirtilmemiş')},{name:'⏳ Yavaş mod',value:`${channel.rateLimitPerUser||0} saniye`,inline:true},{name:'📍 Oluşturulma',value:`<t:${Math.floor(channel.createdTimestamp/1000)}:F>`,inline:true}]));return true;}
  if(name==='ozellikler'){await i.editReply(featureHelp());return true;}
  throw new DomainError('FEATURE_NOT_IMPLEMENTED','Komut şu anda kullanılamıyor.');
 }catch(e){const view=screen('⚠️ İşlem tamamlanamadı',e instanceof DomainError?e.message:e instanceof Error&&e.name==='ZodError'?'Alanları ve kayıt kodunu kontrol et.':'Bir bağlantı veya izin sorunu oluştu. Biraz sonra yeniden dene.',[],theme.red);try{if(i.deferred||i.replied)await i.editReply(view);else await i.reply({...view,flags:MessageFlags.Ephemeral});}catch{console.error('FEATURE_REPLY_FAILED');}return true;}
}
export function featureHelp(category='ekonomi'){return commandHelpView('feature-'+category);}
export async function featureTick(client:any,settings:CommunitySettings){
 await ticketTick();await giveawayTick();await eventMaintenance(settings);
 const f=settings.features;if(!f.enabled)return;const guild=client.guilds.cache.get(config().guildId);if(!guild)return;
 if(f.planner){await transaction(async tx=>{const due=(await tx.query("SELECT * FROM feature_records WHERE guild_id=$1 AND kind='REMINDER' AND status='OPEN' AND due_at<=now() ORDER BY due_at LIMIT 25 FOR UPDATE SKIP LOCKED",[guild.id])).rows;for(const r of due)await tx.query("INSERT INTO community_deliveries(id,guild_id,kind,payload,dedupe_key) VALUES(gen_random_uuid(),$1,'REMINDER',$2,$3) ON CONFLICT(dedupe_key) DO NOTHING",[guild.id,{userId:r.owner_id,recordId:r.id,embeds:[brightEmbed('⏰ Hatırlatma zamanı',displayText(r.title),[],theme.gold)]},'reminder:'+r.id]);});}
 const unpublished=(await database().query("SELECT * FROM feature_records WHERE guild_id=$1 AND kind='EVENT' AND status='OPEN' AND message_id IS NULL AND (payload ? 'previousId' OR payload ? 'publishPending') ORDER BY created_at LIMIT 10",[guild.id])).rows;for(const r of unpublished){try{const channel=await guild.channels.fetch(r.channel_id);const message=await channel.send({...featureRecordView(r,0),nonce:BigInt('0x'+r.id.replace(/-/g,'').slice(0,16)).toString(),enforceNonce:true});await attachFeatureMessage(r.id,channel.id,message.id);}catch{console.error('RECURRING_EVENT_POST_PENDING');}}
 const dirty=(await database().query("SELECT * FROM feature_records WHERE guild_id=$1 AND message_id IS NOT NULL AND kind IN ('GIVEAWAY','EVENT','SUGGESTION','ROLE_MENU') AND (discord_updated_at IS NULL OR discord_updated_at<updated_at) ORDER BY updated_at LIMIT 20",[guild.id])).rows;for(const record of dirty)await refreshRecord({guild},record);
 if(f.community){const due=(await database().query("SELECT r.*,u.username FROM feature_records r JOIN users u ON u.id=r.owner_id WHERE guild_id=$1 AND kind='GIVEAWAY' AND status='OPEN' AND due_at<=now() ORDER BY due_at LIMIT 20",[guild.id])).rows;
 for(const r of due){try{const actor={id:r.owner_id,username:r.username},next=r.kind==='GIVEAWAY'?await finishGiveaway(actor,r.id,true,'due:'+r.id):await updateFeatureRecord(actor,r.id,'DONE',true,'due:'+r.id);await refreshRecord({guild},next);}catch{console.error('FEATURE_EXPIRY_FAILED');}}}
}
