import {MessageFlags,PermissionFlagsBits} from 'discord.js';
import {config,DomainError,database,checkFeature,featureRate,configureTickets,ticketSettings,ticketIsStaff,openTicket,closeTicket,getFeatureRecord,listFeatureRecords,createGiveaway,giveawayRequestId,manageGiveaway,brightEmbed,displayText,channelTag,ticketTopicButtons,type CommunitySettings} from '@turkishpix/core';
export async function handleSupportInteraction(i:any,settings:CommunitySettings){
 const slash=i.isChatInputCommand(),button=i.isButton(),modal=i.isModalSubmit?.();if(!(slash&&['bilet','destek','destekkapat','cekilis','cekilisler'].includes(i.commandName))&&!(button&&/^(ticket:|giveaway:)/.test(i.customId))&&!(modal&&i.customId==='ticket:create'))return false;
 const actor={id:i.user.id,username:i.user.username,avatar:i.user.avatar},staff=config().owners.includes(actor.id)||!!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild);
 try{
  if(button&&i.customId==='ticket:open'){
   checkFeature(settings.features,'destek',i.channelId);const row=await ticketSettings();
   if(!row?.settings.enabled||row.panel_channel_id!==i.channelId||row.panel_message_id!==i.message.id)throw new DomainError('TICKET_PANEL','Bu bilet paneli artık etkin değil.');
   await i.reply({embeds:[brightEmbed('🎫 Bilet kategorini seç','Ayrıntıları açılan özel kanala yazabilirsin.')],components:ticketTopicButtons().map(row=>({...row,components:row.components.map(b=>({...b,custom_id:b.custom_id.replace('ticket:open:','ticket:choose:')+':'+actor.id}))})),flags:MessageFlags.Ephemeral,allowedMentions:{parse:[]}});return true;
  }
  await i.deferReply(slash&&['cekilis','cekilisler'].includes(i.commandName)?{}:{flags:MessageFlags.Ephemeral});await featureRate(actor);
  let message='';
  if(modal)throw new DomainError('TICKET_TOPIC','Bilet panelindeki kategori düğmelerinden birini seç. Konu yazmana gerek yok.');
  else if(button&&/^ticket:(open|choose):/.test(i.customId)){
   checkFeature(settings.features,'destek',i.channelId);const row=await ticketSettings(),parts=i.customId.split(':');
   const validOrigin=parts[1]==='choose'?parts.length===4&&parts[3]===actor.id:parts.length===3&&row?.panel_message_id===i.message.id;
   if(!row?.settings.enabled||row.panel_channel_id!==i.channelId||!validOrigin)throw new DomainError('TICKET_PANEL','Bu bilet paneli artık etkin değil.');
   const r=await openTicket(actor,parts[2],i.id);message='Biletin açıldı: '+channelTag(r.channel_id!);
  }
  else if(button&&i.customId.startsWith('ticket:close:')){const id=i.customId.slice('ticket:close:'.length),r=await getFeatureRecord(id);if(r.channel_id!==i.channelId||r.message_id!==i.message.id)throw new DomainError('TICKET_MESSAGE','Bu düğme bilete ait değil.');await closeTicket(actor,id,staff||await ticketIsStaff(actor.id,r),i.id);message='Bilet kapatıldı. Görüşmeler bu kanalda korunuyor.';}
  else if(button&&i.customId.startsWith('giveaway:')){const match=/^giveaway:(end|cancel|reroll):([0-9a-f-]{36})$/.exec(i.customId);if(!match)throw new DomainError('GIVEAWAY_ACTION','Geçersiz çekiliş işlemi.');const r=await getFeatureRecord(match[2]);checkFeature(settings.features,'cekilis',r.channel_id||i.channelId);await manageGiveaway(actor,r.id,match[1] as any,staff,i.id);message='Çekiliş mesajı güncellendi.';}
  else if(slash&&i.commandName==='cekilis'){if(!staff)throw new DomainError('FORBIDDEN','Çekiliş başlatmak için Sunucuyu Yönet izni gerekli.',403);const r=await createGiveaway(actor,{title:i.options.getString('odul',true),minutes:i.options.getInteger('dakika',true),winnerCount:i.options.getInteger('kazanan')||1,channelId:i.options.getChannel('kanal')?.id||i.channelId,requestId:giveawayRequestId(i.id)});message='Çekiliş başladı: '+`https://discord.com/channels/${r.guild_id}/${r.channel_id}/${r.message_id}`;}
  else if(slash&&i.commandName==='cekilisler'){checkFeature(settings.features,'cekilis',i.channelId);const rows=await listFeatureRecords('GIVEAWAY',actor.id,staff,{limit:5});await i.editReply({embeds:rows.length?rows.map(r=>brightEmbed('🎁 '+displayText(r.title),`${r.status==='OPEN'?'🟢 Katılım açık':r.status==='DONE'?'🏆 Tamamlandı':'🚫 İptal'} · ${r.participants||0} katılım\n[Mesajı aç](https://discord.com/channels/${r.guild_id}/${r.channel_id}/${r.message_id})`)):[brightEmbed('🎁 Çekilişler','Henüz çekiliş yok.')],components:rows.filter(r=>(staff||r.owner_id===actor.id)&&['OPEN','DONE'].includes(r.status)).map(r=>({type:1,components:r.status==='DONE'?[{type:2,style:2,custom_id:'giveaway:reroll:'+r.id,label:displayText(r.title,45)+' · Yeniden seç'}]:[{type:2,style:1,custom_id:'giveaway:end:'+r.id,label:displayText(r.title,45)+' · Bitir'},{type:2,style:4,custom_id:'giveaway:cancel:'+r.id,label:'İptal et'}]})),allowedMentions:{parse:[]}});return true;}
  else if(!slash)throw new DomainError('TICKET_ACTION','Geçersiz bilet işlemi.');
  else {const sub=i.commandName==='bilet'?i.options.getSubcommand():i.commandName==='destek'?'ac':'kapat';if(sub!=='kapat')checkFeature(settings.features,sub==='liste'?'destekler':'destek',i.channelId);
   if(sub==='kur'){if(!staff)throw new DomainError('FORBIDDEN','Kurulum için Sunucuyu Yönet izni gerekli.',403);const result=await configureTickets(actor,{channelId:i.options.getChannel('kanal',true).id,categoryId:i.options.getChannel('kategori',true).id,staffRoleIds:['yetkili','yetkili2','yetkili3'].map(name=>i.options.getRole(name)?.id).filter(Boolean)},true);message=result.message;}
   if(sub==='ac'){const r=await openTicket(actor,i.options.getString('tur',true),i.id);message='Biletin açıldı: '+channelTag(r.channel_id!);}
   if(sub==='kapat'){const id=i.commandName==='destekkapat'?i.options.getString('kayit',true):(await database().query("SELECT id FROM feature_records WHERE guild_id=$1 AND kind='TICKET' AND channel_id=$2 ORDER BY created_at DESC LIMIT 1",[config().guildId,i.channelId])).rows[0]?.id;if(!id)throw new DomainError('TICKET_REQUIRED','Bu komutu bilet kanalında kullan.');const r=await getFeatureRecord(id);await closeTicket(actor,id,staff||await ticketIsStaff(actor.id,r),i.id);message='Bilet kapatıldı; görüşmeler korunuyor.';}
   if(sub==='liste'){const rows=await listFeatureRecords('TICKET',actor.id,staff||await ticketIsStaff(actor.id),{limit:20});message=rows.length?rows.map(r=>`${r.status==='OPEN'?'🟢':'🔒'} **${displayText(r.title,100)}** · ${r.channel_id?channelTag(r.channel_id):'Kanal hazırlanıyor'}`).join('\n'):'Henüz bilet yok.';}
  }
  await i.editReply({embeds:[brightEmbed('✅ TurkishPix',message)],allowedMentions:{parse:[]}});
 }catch(e){const view={embeds:[brightEmbed('İşlem tamamlanamadı',e instanceof DomainError?e.message:'İşlem kaydedilmiş olabilir; bilet/çekiliş listesini kontrol ederek yeniden deneyin.')],allowedMentions:{parse:[]}};if(i.deferred||i.replied)await i.editReply(view);else await i.reply({...view,flags:MessageFlags.Ephemeral});}return true;
}
