import {config,DomainError,rateLimit,searchYouTube,youtubeVideo,youtubeVideoId,recordYouTubeView,saveYouTubeFavourite,youtubeFavourites,youtubeHistory,createWatchTogether,brightEmbed,displayText,theme,type CommunitySettings,type YouTubeVideo} from '@turkishpix/core';
export function youtubeView(videos:YouTubeVideo[]){return {embeds:[brightEmbed('▶ YouTube',videos.length?'Bir video seç. Panelde görüntülü oynatabilir veya `/muzik birlikte` ile ses kanalında ortak oturum açabilirsin.':'Bu aramada video bulunamadı.',videos.map((v,n)=>({name:(n+1)+'. '+displayText(v.title,220),value:displayText(v.channel,120)+'\n[YouTube’da aç]('+v.url+') · [Panelde oynat]('+config().appUrl+'/izle?v='+v.id+')'})),theme.purple)],components:videos.length?[{type:1,components:videos.map((v,n)=>({type:2,style:5,label:'▶ Video '+(n+1),url:config().appUrl+'/izle?v='+v.id}))}]:[],allowedMentions:{parse:[]}};}
export async function handleYouTubeInteraction(i:any,settings:CommunitySettings){
 if(!i.isChatInputCommand()||i.commandName!=='muzik')return false;const sub=i.options.getSubcommand(),known=['youtube','video','birlikte','favori','favoriler','gecmis'];let input:string|undefined;
 if(sub==='oynat'){const link=i.options.getString('baglanti');if(link){try{youtubeVideoId(link);input=link;}catch{}}if(!input)return false;}else if(!known.includes(sub))return false;
 await i.deferReply({});try{if(!settings.music.enabled)throw new DomainError('MUSIC_DISABLED','Müzik modülü kapalı.',403);await rateLimit('youtube-command:'+i.user.id,10,60);const actor={id:i.user.id,username:i.user.username,avatar:i.user.avatar};
  if(sub==='youtube'){await i.editReply(youtubeView(await searchYouTube(actor.id,i.options.getString('ara',true))));return true;}
  if(sub==='birlikte'){const member=await i.guild.members.fetch(actor.id),channelId=member.voice.channelId;if(!channelId)throw new DomainError('VOICE_CHANNEL','Önce bir ses kanalına katıl.');if(settings.music.channelIds.length&&!settings.music.channelIds.includes(channelId))throw new DomainError('MUSIC_CHANNEL','Bu ses kanalı müzik için açık değil.');const result=await createWatchTogether(channelId);await i.editReply({embeds:[brightEmbed('▶ Birlikte YouTube',result.message+'\nSes kanalında herkes aynı videoyu izleyip dinler. Video bağlantısını oturumdaki aramaya yapıştır.',[],theme.purple)],components:[{type:1,components:[{type:2,style:5,label:'Watch Together’a katıl',url:result.url}]}],allowedMentions:{parse:[]}});return true;}
  if(sub==='favoriler'||sub==='gecmis'){const rows=sub==='favoriler'?await youtubeFavourites(actor.id):await youtubeHistory();await i.editReply({embeds:[brightEmbed(sub==='favoriler'?'♡ YouTube favorilerin':'◷ Paylaşılan YouTube videoları',rows.map((r,n)=>`${n+1}. [${displayText(r.title,160)}](https://www.youtube.com/watch?v=${r.video_id})`).join('\n')||'Henüz video yok.',[],theme.purple)],allowedMentions:{parse:[]}});return true;}
  if(sub==='favori'){const result=await saveYouTubeFavourite(actor,i.options.getString('baglanti',true));await i.editReply({embeds:[brightEmbed('♡ YouTube favorisi',displayText(result.video.title)+(result.saved?' favorilerine eklendi.':' favorilerinden kaldırıldı.'),[],theme.purple)],allowedMentions:{parse:[]}});return true;}
  const v=await youtubeVideo(input||i.options.getString('baglanti',true));await recordYouTubeView(actor,v);await i.editReply(youtubeView([v]));
 }catch(e){await i.editReply({embeds:[brightEmbed('YouTube bağlantısı',e instanceof DomainError?e.message:'YouTube isteği tamamlanamadı. Biraz sonra yeniden dene.',[],theme.gold)],allowedMentions:{parse:[]}});}return true;
}
